#ifndef GUARD_CONSTANTS_BATTLE_TENT_TRAINERS_H
#define GUARD_CONSTANTS_BATTLE_TENT_TRAINERS_H

// CHAMP LEAGUE - TODO
#define BATTLE_TENT_CHAMP_TRAINER_JOLIE    0
#define BATTLE_TENT_CHAMP_TRAINER_MALACHI  1
#define BATTLE_TENT_CHAMP_TRAINER_KELSIE   2

#define NUM_BATTLE_TENT_CHAMP_TRAINERS      3

// MAJOR LEAGUE
#define BATTLE_TENT_MAJOR_TRAINER_JOLIE    0
#define BATTLE_TENT_MAJOR_TRAINER_MALACHI  1
#define BATTLE_TENT_MAJOR_TRAINER_KELSIE   2

#define NUM_BATTLE_TENT_MAJOR_TRAINERS      3

// MINOR LEAGUE
#define BATTLE_TENT_MINOR_TRAINER_JOLIE    0
#define BATTLE_TENT_MINOR_TRAINER_MALACHI  1
#define BATTLE_TENT_MINOR_TRAINER_KELSIE   2
#define BATTLE_TENT_MINOR_TRAINER_DAVON    3
#define BATTLE_TENT_MINOR_TRAINER_GLENDA   4
#define BATTLE_TENT_MINOR_TRAINER_HELENA   5
#define BATTLE_TENT_MINOR_TRAINER_RODOLFO  6
#define BATTLE_TENT_MINOR_TRAINER_DAVION   7
#define BATTLE_TENT_MINOR_TRAINER_KENDALL  8
#define BATTLE_TENT_MINOR_TRAINER_COLTEN   9
#define BATTLE_TENT_MINOR_TRAINER_IRVIN    10
#define BATTLE_TENT_MINOR_TRAINER_SHAUN    11
#define BATTLE_TENT_MINOR_TRAINER_KYLER    12
#define BATTLE_TENT_MINOR_TRAINER_MAGGIE   13
#define BATTLE_TENT_MINOR_TRAINER_STEPHON  14
#define BATTLE_TENT_MINOR_TRAINER_REBECCA  15
#define BATTLE_TENT_MINOR_TRAINER_REGGIE   16
#define BATTLE_TENT_MINOR_TRAINER_JANAE    17
#define BATTLE_TENT_MINOR_TRAINER_CAIDEN   18
#define BATTLE_TENT_MINOR_TRAINER_KIRSTEN  19
#define BATTLE_TENT_MINOR_TRAINER_KURTIS   20
#define BATTLE_TENT_MINOR_TRAINER_STEFAN   21
#define BATTLE_TENT_MINOR_TRAINER_AVERY    22
#define BATTLE_TENT_MINOR_TRAINER_DWANE    23
#define BATTLE_TENT_MINOR_TRAINER_MCKENNA  24
#define BATTLE_TENT_MINOR_TRAINER_CAMRYN   25
#define BATTLE_TENT_MINOR_TRAINER_NATASHA  26
#define BATTLE_TENT_MINOR_TRAINER_AUSTYN   27
#define BATTLE_TENT_MINOR_TRAINER_DONOVAN  28
#define BATTLE_TENT_MINOR_TRAINER_TAMIA    29

#define NUM_BATTLE_TENT_MINOR_TRAINERS      30

#define VERDANTURF_TENT_TRAINER_BRENNA  0
#define VERDANTURF_TENT_TRAINER_DILAN   1
#define VERDANTURF_TENT_TRAINER_ELIANA  2
#define VERDANTURF_TENT_TRAINER_MARKUS  3
#define VERDANTURF_TENT_TRAINER_CAITLYN 4
#define VERDANTURF_TENT_TRAINER_DESIREE 5
#define VERDANTURF_TENT_TRAINER_RONALD  6
#define VERDANTURF_TENT_TRAINER_ASHTEN  7
#define VERDANTURF_TENT_TRAINER_GERARD  8
#define VERDANTURF_TENT_TRAINER_BRADLY  9
#define VERDANTURF_TENT_TRAINER_DENNIS  10
#define VERDANTURF_TENT_TRAINER_PRESTIN 11
#define VERDANTURF_TENT_TRAINER_ERNESTO 12
#define VERDANTURF_TENT_TRAINER_NALA    13
#define VERDANTURF_TENT_TRAINER_DARNELL 14
#define VERDANTURF_TENT_TRAINER_ASHLYN  15
#define VERDANTURF_TENT_TRAINER_ADDISON 16
#define VERDANTURF_TENT_TRAINER_JUSTINE 17
#define VERDANTURF_TENT_TRAINER_TYSON   18
#define VERDANTURF_TENT_TRAINER_LAILA   19
#define VERDANTURF_TENT_TRAINER_WAREN   20
#define VERDANTURF_TENT_TRAINER_TOBIAS  21
#define VERDANTURF_TENT_TRAINER_JOSIAH  22
#define VERDANTURF_TENT_TRAINER_DION    23
#define VERDANTURF_TENT_TRAINER_KENZIE  24
#define VERDANTURF_TENT_TRAINER_LILLIAN 25
#define VERDANTURF_TENT_TRAINER_LESLEY  26
#define VERDANTURF_TENT_TRAINER_MARQUIS 27
#define VERDANTURF_TENT_TRAINER_FREDDY  28
#define VERDANTURF_TENT_TRAINER_CECILIA 29

#define FALLARBOR_TENT_TRAINER_AMBER    0
#define FALLARBOR_TENT_TRAINER_JAVIER   1
#define FALLARBOR_TENT_TRAINER_NATALIA  2
#define FALLARBOR_TENT_TRAINER_TREVE    3
#define FALLARBOR_TENT_TRAINER_ARIANNA  4
#define FALLARBOR_TENT_TRAINER_JADYN    5
#define FALLARBOR_TENT_TRAINER_GERARDO  6
#define FALLARBOR_TENT_TRAINER_JONN     7
#define FALLARBOR_TENT_TRAINER_ESTEBAN  8
#define FALLARBOR_TENT_TRAINER_JAMESON  9
#define FALLARBOR_TENT_TRAINER_ALANZO   10
#define FALLARBOR_TENT_TRAINER_HOWARD   11
#define FALLARBOR_TENT_TRAINER_CONRAD   12
#define FALLARBOR_TENT_TRAINER_MAKENNA  13
#define FALLARBOR_TENT_TRAINER_BRAYAN   14
#define FALLARBOR_TENT_TRAINER_MARIANA  15
#define FALLARBOR_TENT_TRAINER_SHELDON  16
#define FALLARBOR_TENT_TRAINER_GIANNA   17
#define FALLARBOR_TENT_TRAINER_YAHIR    18
#define FALLARBOR_TENT_TRAINER_BRITNEY  19
#define FALLARBOR_TENT_TRAINER_HECTER   20
#define FALLARBOR_TENT_TRAINER_TANNOR   21
#define FALLARBOR_TENT_TRAINER_BENJI    22
#define FALLARBOR_TENT_TRAINER_RORY     23
#define FALLARBOR_TENT_TRAINER_ELEANOR  24
#define FALLARBOR_TENT_TRAINER_EVELYN   25
#define FALLARBOR_TENT_TRAINER_ARIELLE  26
#define FALLARBOR_TENT_TRAINER_CONNAR   27
#define FALLARBOR_TENT_TRAINER_MAURICE  28
#define FALLARBOR_TENT_TRAINER_KIANNA   29

#define NUM_BATTLE_TENT_TRAINERS 30

#endif  // GUARD_CONSTANTS_BATTLE_TENT_TRAINERS_H
