#ifndef GUARD_CONSTANTS_BATTLE_MOVE_EFFECTS_H
#define GUARD_CONSTANTS_BATTLE_MOVE_EFFECTS_H

#define EFFECT_HIT                          0
#define EFFECT_SLEEP                        1
#define EFFECT_POISON_HIT                   2
#define EFFECT_ABSORB                       3
#define EFFECT_BURN_HIT                     4
#define EFFECT_FREEZE_HIT                   5
#define EFFECT_PARALYZE_HIT                 6
#define EFFECT_EXPLOSION                    7
#define EFFECT_DREAM_EATER                  8
#define EFFECT_MIRROR_MOVE                  9
#define EFFECT_ATTACK_UP                    10
#define EFFECT_DEFENSE_UP                   11
#define EFFECT_SPEED_UP                     12
#define EFFECT_SPECIAL_ATTACK_UP            13
#define EFFECT_SPECIAL_DEFENSE_UP           14
#define EFFECT_ACCURACY_UP                  15
#define EFFECT_EVASION_UP                   16
#define EFFECT_SPECIAL_ATTACK_UP_3          17
#define EFFECT_ATTACK_DOWN                  18
#define EFFECT_DEFENSE_DOWN                 19
#define EFFECT_SPEED_DOWN                   20
#define EFFECT_SPECIAL_ATTACK_DOWN          21
#define EFFECT_SPECIAL_DEFENSE_DOWN         22
#define EFFECT_ACCURACY_DOWN                23
#define EFFECT_EVASION_DOWN                 24
#define EFFECT_HAZE                         25
#define EFFECT_BIDE                         26
#define EFFECT_RAMPAGE                      27
#define EFFECT_ROAR                         28
#define EFFECT_MULTI_HIT                    29
#define EFFECT_CONVERSION                   30
#define EFFECT_FLINCH_HIT                   31
#define EFFECT_RESTORE_HP                   32
#define EFFECT_TOXIC                        33
#define EFFECT_PAY_DAY                      34
#define EFFECT_LIGHT_SCREEN                 35
#define EFFECT_TRI_ATTACK                   36
#define EFFECT_REST                         37
#define EFFECT_OHKO                         38
#define EFFECT_FUSION_COMBO                 39
#define EFFECT_SUPER_FANG                   40
#define EFFECT_DRAGON_RAGE                  41
#define EFFECT_TRAP                         42
#define EFFECT_HEAL_BLOCK                   43
#define EFFECT_RECOIL_IF_MISS               44
#define EFFECT_MIST                         45
#define EFFECT_FOCUS_ENERGY                 46
#define EFFECT_RECOIL_25                    47
#define EFFECT_CONFUSE                      48
#define EFFECT_ATTACK_UP_2                  49
#define EFFECT_DEFENSE_UP_2                 50
#define EFFECT_SPEED_UP_2                   51
#define EFFECT_SPECIAL_ATTACK_UP_2          52
#define EFFECT_SPECIAL_DEFENSE_UP_2         53
#define EFFECT_ACCURACY_UP_2                54
#define EFFECT_EVASION_UP_2                 55
#define EFFECT_TRANSFORM                    56
#define EFFECT_ATTACK_DOWN_2                57
#define EFFECT_DEFENSE_DOWN_2               58
#define EFFECT_SPEED_DOWN_2                 59
#define EFFECT_SPECIAL_ATTACK_DOWN_2        60
#define EFFECT_SPECIAL_DEFENSE_DOWN_2       61
#define EFFECT_ACCURACY_DOWN_2              62
#define EFFECT_EVASION_DOWN_2               63
#define EFFECT_REFLECT                      64
#define EFFECT_POISON                       65
#define EFFECT_PARALYZE                     66
#define EFFECT_ATTACK_DOWN_HIT              67
#define EFFECT_DEFENSE_DOWN_HIT             68
#define EFFECT_SPEED_DOWN_HIT               69
#define EFFECT_SPECIAL_ATTACK_DOWN_HIT      70
#define EFFECT_SPECIAL_DEFENSE_DOWN_HIT     71
#define EFFECT_ACCURACY_DOWN_HIT            72
#define EFFECT_EVASION_DOWN_HIT             73
#define EFFECT_TWO_TURNS_ATTACK             74
#define EFFECT_CONFUSE_HIT                  75
#define EFFECT_VITAL_THROW                  76
#define EFFECT_SUBSTITUTE                   77
#define EFFECT_RECHARGE                     78
#define EFFECT_RAGE                         79
#define EFFECT_MIMIC                        80
#define EFFECT_METRONOME                    81
#define EFFECT_LEECH_SEED                   82
#define EFFECT_DO_NOTHING                   83
#define EFFECT_DISABLE                      84
#define EFFECT_LEVEL_DAMAGE                 85
#define EFFECT_PSYWAVE                      86
#define EFFECT_COUNTER                      87
#define EFFECT_ENCORE                       88
#define EFFECT_PAIN_SPLIT                   89
#define EFFECT_SNORE                        90
#define EFFECT_CONVERSION_2                 91
#define EFFECT_LOCK_ON                      92
#define EFFECT_SKETCH                       93
#define EFFECT_HAMMER_ARM                   94
#define EFFECT_SLEEP_TALK                   95
#define EFFECT_DESTINY_BOND                 96
#define EFFECT_FLAIL                        97
#define EFFECT_SPITE                        98
#define EFFECT_FALSE_SWIPE                  99
#define EFFECT_HEAL_BELL                    100
#define EFFECT_ALWAYS_CRIT                  101
#define EFFECT_TRIPLE_KICK                  102
#define EFFECT_THIEF                        103
#define EFFECT_MEAN_LOOK                    104
#define EFFECT_NIGHTMARE                    105
#define EFFECT_MINIMIZE                     106
#define EFFECT_CURSE                        107
#define EFFECT_HEALING_WISH                 108
#define EFFECT_PROTECT                      109
#define EFFECT_SPIKES                       110
#define EFFECT_FORESIGHT                    111
#define EFFECT_PERISH_SONG                  112
#define EFFECT_SANDSTORM                    113
#define EFFECT_ENDURE                       114
#define EFFECT_ROLLOUT                      115
#define EFFECT_SWAGGER                      116
#define EFFECT_FURY_CUTTER                  117
#define EFFECT_ATTRACT                      118
#define EFFECT_RETURN                       119
#define EFFECT_PRESENT                      120
#define EFFECT_FRUSTRATION                  121
#define EFFECT_SAFEGUARD                    122
#define EFFECT_MAGNITUDE                    123
#define EFFECT_BATON_PASS                   124
#define EFFECT_PURSUIT                      125
#define EFFECT_RAPID_SPIN                   126
#define EFFECT_SONICBOOM                    127
#define EFFECT_CAPTIVATE                    128
#define EFFECT_MORNING_SUN                  129
#define EFFECT_SYNTHESIS                    130
#define EFFECT_MOONLIGHT                    131
#define EFFECT_HIDDEN_POWER                 132
#define EFFECT_RAIN_DANCE                   133
#define EFFECT_SUNNY_DAY                    134
#define EFFECT_DEFENSE_UP_HIT               135
#define EFFECT_ATTACK_UP_HIT                136
#define EFFECT_ALL_STATS_UP_HIT             137
#define EFFECT_FELL_STINGER                 138
#define EFFECT_BELLY_DRUM                   139
#define EFFECT_PSYCH_UP                     140
#define EFFECT_MIRROR_COAT                  141
#define EFFECT_SKULL_BASH                   142
#define EFFECT_EARTHQUAKE                   143
#define EFFECT_FUTURE_SIGHT                 144
#define EFFECT_GUST                         145
#define EFFECT_SOLAR_BEAM                   146
#define EFFECT_THUNDER                      147
#define EFFECT_TELEPORT                     148
#define EFFECT_BEAT_UP                      149
#define EFFECT_SEMI_INVULNERABLE            150
#define EFFECT_DEFENSE_CURL                 151
#define EFFECT_SOFTBOILED                   152
#define EFFECT_FAKE_OUT                     153
#define EFFECT_UPROAR                       154
#define EFFECT_STOCKPILE                    155
#define EFFECT_SPIT_UP                      156
#define EFFECT_SWALLOW                      157
#define EFFECT_WORRY_SEED                   158
#define EFFECT_HAIL                         159
#define EFFECT_TORMENT                      160
#define EFFECT_FLATTER                      161
#define EFFECT_WILL_O_WISP                  162
#define EFFECT_MEMENTO                      163
#define EFFECT_FACADE                       164
#define EFFECT_FOCUS_PUNCH                  165
#define EFFECT_SMELLINGSALT                 166
#define EFFECT_FOLLOW_ME                    167
#define EFFECT_NATURE_POWER                 168
#define EFFECT_CHARGE                       169
#define EFFECT_TAUNT                        170
#define EFFECT_HELPING_HAND                 171
#define EFFECT_TRICK                        172
#define EFFECT_ROLE_PLAY                    173
#define EFFECT_WISH                         174
#define EFFECT_ASSIST                       175
#define EFFECT_INGRAIN                      176
#define EFFECT_SUPERPOWER                   177
#define EFFECT_MAGIC_COAT                   178
#define EFFECT_RECYCLE                      179
#define EFFECT_REVENGE                      180
#define EFFECT_BRICK_BREAK                  181
#define EFFECT_YAWN                         182
#define EFFECT_KNOCK_OFF                    183
#define EFFECT_ENDEAVOR                     184
#define EFFECT_ERUPTION                     185
#define EFFECT_SKILL_SWAP                   186
#define EFFECT_IMPRISON                     187
#define EFFECT_REFRESH                      188
#define EFFECT_GRUDGE                       189
#define EFFECT_SNATCH                       190
#define EFFECT_LOW_KICK                     191
#define EFFECT_SECRET_POWER                 192
#define EFFECT_RECOIL_33                    193
#define EFFECT_TEETER_DANCE                 194
#define EFFECT_HIT_ESCAPE                   195
#define EFFECT_MUD_SPORT                    196
#define EFFECT_POISON_FANG                  197
#define EFFECT_WEATHER_BALL                 198
#define EFFECT_OVERHEAT                     199
#define EFFECT_TICKLE                       200
#define EFFECT_COSMIC_POWER                 201
#define EFFECT_SKY_UPPERCUT                 202
#define EFFECT_BULK_UP                      203
#define EFFECT_PLACEHOLDER                  204
#define EFFECT_WATER_SPORT                  205
#define EFFECT_CALM_MIND                    206
#define EFFECT_DRAGON_DANCE                 207
#define EFFECT_CAMOUFLAGE                   208

// New move effects
#define EFFECT_PLEDGE                       209
#define EFFECT_FLING                        210
#define EFFECT_NATURAL_GIFT                 211
#define EFFECT_WAKE_UP_SLAP                 212
#define EFFECT_WRING_OUT                    213
#define EFFECT_HEX                          214
#define EFFECT_ASSURANCE                    215
#define EFFECT_TRUMP_CARD                   216
#define EFFECT_ACROBATICS                   217
#define EFFECT_HEAT_CRASH                   218
#define EFFECT_PUNISHMENT                   219
#define EFFECT_STORED_POWER                 220
#define EFFECT_ELECTRO_BALL                 221
#define EFFECT_GYRO_BALL                    222
#define EFFECT_ECHOED_VOICE                 223
#define EFFECT_PAYBACK                      224
#define EFFECT_ROUND                        225
#define EFFECT_BRINE                        226
#define EFFECT_VENOSHOCK                    227
#define EFFECT_RETALIATE                    228
#define EFFECT_BULLDOZE                     229
#define EFFECT_FOUL_PLAY                    230
#define EFFECT_PSYSHOCK                     231
#define EFFECT_ROOST                        232
#define EFFECT_GRAVITY                      233
#define EFFECT_MIRACLE_EYE                  234
#define EFFECT_TAILWIND                     235
#define EFFECT_EMBARGO                      236
#define EFFECT_AQUA_RING                    237
#define EFFECT_TRICK_ROOM                   238
#define EFFECT_WONDER_ROOM                  239
#define EFFECT_MAGIC_ROOM                   240
#define EFFECT_MAGNET_RISE                  241
#define EFFECT_TOXIC_SPIKES                 242
#define EFFECT_GASTRO_ACID                  243
#define EFFECT_STEALTH_ROCK                 244
#define EFFECT_TELEKINESIS                  245
#define EFFECT_POWER_SWAP                   246
#define EFFECT_GUARD_SWAP                   247
#define EFFECT_HEART_SWAP                   248
#define EFFECT_POWER_SPLIT                  249
#define EFFECT_GUARD_SPLIT                  250
#define EFFECT_STICKY_WEB                   251
#define EFFECT_METAL_BURST                  252
#define EFFECT_LUCKY_CHANT                  253
#define EFFECT_SUCKER_PUNCH                 254
#define EFFECT_SPECIAL_DEFENSE_DOWN_HIT_2   255
#define EFFECT_SIMPLE_BEAM                  256
#define EFFECT_ENTRAINMENT                  257
#define EFFECT_HEAL_PULSE                   258
#define EFFECT_QUASH                        259
#define EFFECT_ION_DELUGE                   260
#define EFFECT_FREEZE_DRY                   261
#define EFFECT_TOPSY_TURVY                  262
#define EFFECT_MISTY_TERRAIN                263
#define EFFECT_GRASSY_TERRAIN               264
#define EFFECT_ELECTRIC_TERRAIN             265
#define EFFECT_PSYCHIC_TERRAIN              266
#define EFFECT_ATTACK_ACCURACY_UP           267
#define EFFECT_ATTACK_SPATK_UP              268
#define EFFECT_HURRICANE                    269
#define EFFECT_TWO_TYPED_MOVE               270
#define EFFECT_ME_FIRST                     271
#define EFFECT_SPEED_UP_HIT                 272
#define EFFECT_QUIVER_DANCE                 273
#define EFFECT_COIL                         274
#define EFFECT_ELECTRIFY                    275
#define EFFECT_REFLECT_TYPE                 276
#define EFFECT_SOAK                         277
#define EFFECT_GROWTH                       278
#define EFFECT_CLOSE_COMBAT                 279
#define EFFECT_LAST_RESORT                  280
#define EFFECT_RECOIL_33_STATUS             281
#define EFFECT_FLINCH_STATUS                282
#define EFFECT_RECOIL_50                    283
#define EFFECT_SHELL_SMASH                  284
#define EFFECT_SHIFT_GEAR                   285
#define EFFECT_DEFENSE_UP_3                 286
#define EFFECT_NOBLE_ROAR                   287
#define EFFECT_VENOM_DRENCH                 288
#define EFFECT_TOXIC_THREAD                 289
#define EFFECT_CLEAR_SMOG                   290
#define EFFECT_HIT_SWITCH_TARGET            291
#define EFFECT_FINAL_GAMBIT                 292
#define EFFECT_CHANGE_TYPE_ON_ITEM          293
#define EFFECT_AUTOTOMIZE                   294
#define EFFECT_COPYCAT                      295
#define EFFECT_DEFOG                        296
#define EFFECT_HIT_ENEMY_HEAL_ALLY          297
#define EFFECT_SMACK_DOWN                   298
#define EFFECT_SYNCHRONOISE                 299
#define EFFECT_PSYCHO_SHIFT                 300
#define EFFECT_POWER_TRICK                  301
#define EFFECT_FLAME_BURST                  302
#define EFFECT_AFTER_YOU                    303
#define EFFECT_BESTOW                       304
#define EFFECT_ROTOTILLER                   305
#define EFFECT_FLOWER_SHIELD                306
#define EFFECT_HIT_PREVENT_ESCAPE           307
#define EFFECT_SPEED_SWAP                   308
#define EFFECT_DEFENSE_UP2_HIT              309
#define EFFECT_REVELATION_DANCE             310
#define EFFECT_AURORA_VEIL                  311
#define EFFECT_THIRD_TYPE                   312
#define EFFECT_FEINT                        313
#define EFFECT_SPARKLING_ARIA               314
#define EFFECT_ACUPRESSURE                  315
#define EFFECT_AROMATIC_MIST                316
#define EFFECT_POWDER                       317
#define EFFECT_SP_ATTACK_UP_HIT             318
#define EFFECT_BELCH                        319
#define EFFECT_PARTING_SHOT                 320
#define EFFECT_SPECTRAL_THIEF               321
#define EFFECT_V_CREATE                     322
#define EFFECT_MAT_BLOCK                    323
#define EFFECT_STOMPING_TANTRUM             324
#define EFFECT_CORE_ENFORCER                325
#define EFFECT_INSTRUCT                     326
#define EFFECT_THROAT_CHOP                  327
#define EFFECT_LASER_FOCUS                  328
#define EFFECT_MAGNETIC_FLUX                329
#define EFFECT_GEAR_UP                      330
#define EFFECT_INCINERATE                   331
#define EFFECT_BUG_BITE                     332
#define EFFECT_STRENGTH_SAP                 333
#define EFFECT_MIND_BLOWN                   334
#define EFFECT_PURIFY                       335
#define EFFECT_BURN_UP                      336
#define EFFECT_SHORE_UP                     337
#define EFFECT_GEOMANCY                     338
#define EFFECT_FAIRY_LOCK                   339
#define EFFECT_ALLY_SWITCH                  340
#define EFFECT_RELIC_SONG                   341
#define EFFECT_ATTACKER_DEFENSE_DOWN_HIT    342
#define EFFECT_BODY_PRESS                   343
#define EFFECT_EERIE_SPELL                  344
#define EFFECT_JUNGLE_HEALING               345
#define EFFECT_COACHING                     346
#define EFFECT_LASH_OUT                     347
#define EFFECT_GRASSY_GLIDE                 348
#define EFFECT_DYNAMAX_DOUBLE_DMG           349
#define EFFECT_DECORATE                     350
#define EFFECT_SNIPE_SHOT                   351
#define EFFECT_RECOIL_HP_25                 352
#define EFFECT_STUFF_CHEEKS                 353
#define EFFECT_GRAV_APPLE                   354
#define EFFECT_EVASION_UP_HIT               355
#define EFFECT_GLITZY_GLOW                  356
#define EFFECT_BADDY_BAD                    357
#define EFFECT_SAPPY_SEED                   358
#define EFFECT_FREEZY_FROST                 359
#define EFFECT_SPARKLY_SWIRL                360
#define EFFECT_PLASMA_FISTS                 361
#define EFFECT_HYPERSPACE_FURY              362
#define EFFECT_AURA_WHEEL                   363
#define EFFECT_PHOTON_GEYSER                364
#define EFFECT_SHELL_SIDE_ARM               365
#define EFFECT_TERRAIN_PULSE                366
#define EFFECT_JAW_LOCK                     367
#define EFFECT_NO_RETREAT                   368
#define EFFECT_TAR_SHOT                     369
#define EFFECT_POLTERGEIST                  370
#define EFFECT_OCTOLOCK                     371
#define EFFECT_CLANGOROUS_SOUL              372
#define EFFECT_BOLT_BEAK                    373
#define EFFECT_SKY_DROP                     374
#define EFFECT_EXPANDING_FORCE              375
#define EFFECT_METEOR_BEAM                  376
#define EFFECT_RISING_VOLTAGE               377
#define EFFECT_BEAK_BLAST                   378
#define EFFECT_COURT_CHANGE                 379
#define EFFECT_STEEL_BEAM                   380
#define EFFECT_EXTREME_EVOBOOST             381
#define EFFECT_HIT_SET_REMOVE_TERRAIN       382 // genesis supernova
#define EFFECT_DARK_VOID                    383
#define EFFECT_SLEEP_HIT                    384
#define EFFECT_DOUBLE_SHOCK                 385
#define EFFECT_SPECIAL_ATTACK_UP_HIT        386
#define EFFECT_VICTORY_DANCE                387
#define EFFECT_TEATIME                      388
#define EFFECT_ATTACK_UP_USER_ALLY          389 // Howl 8th Gen
#define EFFECT_SHELL_TRAP                   390
#define EFFECT_PSYBLADE                     391
#define EFFECT_HYDRO_STEAM                  392
#define EFFECT_HIT_SET_ENTRY_HAZARD         393
#define EFFECT_DIRE_CLAW                    394
#define EFFECT_BARB_BARRAGE                 395
#define EFFECT_REVIVAL_BLESSING             396
#define EFFECT_FROSTBITE_HIT                397
#define EFFECT_SNOWSCAPE                    398
#define EFFECT_TRIPLE_ARROWS                399
#define EFFECT_INFERNAL_PARADE              400
#define EFFECT_TAKE_HEART                   401
#define EFFECT_AXE_KICK                     402
#define EFFECT_COLLISION_COURSE             403
#define EFFECT_SPIN_OUT                     404
#define EFFECT_MAKE_IT_RAIN                 405
#define EFFECT_CORROSIVE_GAS                406
#define EFFECT_POPULATION_BOMB              407
#define EFFECT_MORTAL_SPIN                  408
#define EFFECT_GIGATON_HAMMER               409
#define EFFECT_SALT_CURE                    410
#define EFFECT_GLACIATE                     411
#define EFFECT_CHILLY_AIR                   412
#define EFFECT_LAST_RESPECTS                413
#define EFFECT_RAGE_FIST                    414
#define EFFECT_FILLET_AWAY                  415
#define EFFECT_CHILLY_RECEPTION             416
#define EFFECT_SHED_TAIL                    417
#define EFFECT_FICKLE_BEAM                  418
#define EFFECT_DRAGON_CHEER                 419
#define EFFECT_PSYCHIC_NOISE                420
#define EFFECT_SNUFF_OUT                    421
#define EFFECT_COLD_MEND                    422
#define EFFECT_VIPER_STRIKE                 423
#define EFFECT_ALL_STATS_UP_2_HIT           424
#define EFFECT_SPOOK                        425
#define EFFECT_U_TURN                       426
#define EFFECT_SILVER_WIND                  427
#define EFFECT_SIGNAL_BEAM                  428
#define EFFECT_RAGE_POWDER                  429
#define EFFECT_SPIDER_WEB                   430
#define EFFECT_RECOIL_50_STATUS             431
#define EFFECT_EERIE_IMPULSE                432
#define EFFECT_FLASH                        433
#define EFFECT_CHARM                        434
#define EFFECT_BITTER_MALICE                435
#define EFFECT_HEART_STAMP                  436
#define EFFECT_MEDITATE                     437
#define EFFECT_METEOR_MASH                  438
#define EFFECT_FLIP_TURN                    439
#define EFFECT_MUDDY_WATER                  440
#define EFFECT_DRAGON_RUIN                  441
#define EFFECT_CINDER_TWIRL                 442
#define EFFECT_CINDER_DRILL                 443
#define EFFECT_SILENCE                      444
#define EFFECT_TORMENT_HIT                  445
#define EFFECT_DECAY_BEAM                   446
#define EFFECT_WARM_WELCOME                 447
#define EFFECT_RADIOACID                    448
#define EFFECT_PARTING_CURRY                449
#define EFFECT_SERPENT_SURGE                450
#define EFFECT_TIDY_UP                      451
#define EFFECT_DRAINING_KISS                452
#define EFFECT_HULLBREAKER                  453
#define EFFECT_HEART_CARVE_HIT              454
#define EFFECT_DRAGON_POKER                 455
#define EFFECT_WATERFALL                    456
#define EFFECT_CUT                          457
#define EFFECT_ROCK_SMASH                   458
#define EFFECT_STRENGTH                     459
#define EFFECT_ROCK_CLIMB                   460
#define EFFECT_SURF                         461
#define EFFECT_DIVE                         462
#define EFFECT_FLY                          463
#define EFFECT_WHIRLPOOL                    464
#define EFFECT_LONE_SHARK                   465
#define EFFECT_HEART_STEAL                  466
#define EFFECT_IGNA_STRIKE                  467
#define EFFECT_ACCURACY_DEFENSE_DOWN_HIT    468
#define EFFECT_VENOM_DRAIN                  469
#define EFFECT_ALL_STATS_DOWN_HIT           470
#define EFFECT_WILLPOWER                    471
#define EFFECT_MANEUVER                     472
#define EFFECT_SCORP_FANG                   473
#define EFFECT_RECOIL_50_HAZARD             474
#define EFFECT_WICKED_WINDS                 475
#define EFFECT_SAND_TOMB                    476
#define EFFECT_SONIC_BURST                  477
#define EFFECT_SOUL_CUTTER                  478
#define EFFECT_VOID                         479
#define EFFECT_KERFUFFLE                    480
#define EFFECT_VERGLASTROM                  481
#define EFFECT_EXORCISM                     482
#define EFFECT_LOVE_TAP                     483
#define EFFECT_SOLAR_FLARE                  484
#define EFFECT_PANIC_HIT                    485
#define EFFECT_BLOOMING_HIT                 486
#define EFFECT_EXPOSED_HIT                  487
#define EFFECT_TEARFUL_LOOK                 488
#define EFFECT_BLACK_BUFFET                 489
#define EFFECT_FINISH_OFF                   490
#define EFFECT_SEIZE_CHANCE                 491
#define EFFECT_RAZING_SUN                   492
#define EFFECT_TERRORIZE                    493
#define EFFECT_BRUTALIZE                    494
#define EFFECT_ROADBLOCK                    495
#define EFFECT_DEFENSE_DOWN_HIT_2           496
#define EFFECT_EARTH_SHATTER                497
#define EFFECT_PILGRIMAGE                   498
#define EFFECT_HEAVY_CANNON                 499
#define EFFECT_GIANTS_SPEAR                 500
#define EFFECT_REDLINE                      501
#define EFFECT_ZAPPER                       502
#define EFFECT_SKY_SPLITTER                 503
#define EFFECT_ALL_STATS_UP_2_HIT_FOE       504
#define EFFECT_TICK_TACK                    505
#define EFFECT_DEEP_GAZE                    506
#define EFFECT_ENERVATOR                    507
#define EFFECT_ERODE_FIELD                  508
#define EFFECT_HEAVY_CELL                   509
#define EFFECT_RECONSTRUCT                  510
#define EFFECT_REMODEL                      511
#define EFFECT_BARI_BARI_BEAM               512
#define EFFECT_BARI_BARI_BASH               513
#define EFFECT_SP_ATTACK_ACCURACY_UP        514
#define EFFECT_SUN_BASK                     515
#define EFFECT_HEARTHWARM                   516
#define EFFECT_DUNE_SLICER                  517
#define EFFECT_POWER_DRAIN                  518
#define EFFECT_FLORESCENCE                  519
#define EFFECT_GRIPPING_NAIL                520
#define EFFECT_SNAP_TRAP                    521
#define EFFECT_SPEED_DOWN_HIT_2             522
#define EFFECT_VIGOR_ROOT                   523
#define EFFECT_SEED_BOMB                    524
#define EFFECT_PETAL_BLIZZARD               525
#define EFFECT_SPIRIT_AWAY                  526
#define EFFECT_PHANTASM                     527
#define EFFECT_SNAPBLOSSOM                  528
#define EFFECT_GRASS_CANNON                 529
#define EFFECT_SPECIAL_DEFENSE_UP_HIT       530
#define EFFECT_DEF_SP_DEF_UP_HIT            531
#define EFFECT_SAVAGE_WING                  532
#define EFFECT_PLASMA_CUTTER                533
#define EFFECT_BOUNDARY                     534
#define EFFECT_PARTY_TRICK                  535
#define EFFECT_DANCE_MANIA                  536
#define EFFECT_BEATBOX                      537
#define EFFECT_SPEED_UP_USER_ALLY           538
#define EFFECT_IGNITION                     539
#define EFFECT_FAIRY_WIND                   540
#define EFFECT_FLORAL_HEALING               541
#define EFFECT_SHARP_GLIDE                  542
#define EFFECT_CRASH_LAND                   543
#define EFFECT_AIR_CANNON                   544
#define EFFECT_FEATHER_DANCE                545
#define EFFECT_BANSHRIEK                    546
#define EFFECT_VINE_WHIP                    547
#define EFFECT_TRAILBLAZE                   548
#define EFFECT_NEEDLE_ARM                   549
#define EFFECT_TROP_KICK                    550
#define EFFECT_DRUM_BEATING                 551
#define EFFECT_WOOD_HAMMER                  552
#define EFFECT_APPLE_ACID                   553
#define EFFECT_ENERGY_BALL                  554
#define EFFECT_PETAL_DANCE                  555
#define EFFECT_SNOWFADE                     556
#define EFFECT_FRENZY_PLANT                 557
#define EFFECT_AROMATHERAPY                 558
#define EFFECT_GREEN_GUISE                  559
#define EFFECT_FROST_SHRED                  560
#define EFFECT_COTTON_SPORE                 561
#define EFFECT_SLEEP_POWDER                 562
#define EFFECT_PLUNDER                      563
#define EFFECT_STUN_SPORE                   564
#define EFFECT_GOLD_PLAINS                  565
#define EFFECT_DOWNFALL                     566
#define EFFECT_MT_SPLENDOR                  567
#define EFFECT_GATTLING_PINS                568
#define EFFECT_CONSTRICT                    569
#define EFFECT_HYPER_DRILL                  570
#define EFFECT_RECHARGE_REDUCE              571
#define EFFECT_PURIFICATION                 572
#define EFFECT_MIND_READER                  573
#define EFFECT_ODOR_SLEUTH                  574
#define EFFECT_SURPRISE_EGG                 575
#define EFFECT_BLOCK                        576
#define EFFECT_CUTIE_CRY                    577
#define EFFECT_FLEUR_CANNON                 578
#define EFFECT_UPPER_HAND                   579
#define EFFECT_WHIRLWIND                    580
#define EFFECT_GLACIAL_SHIFT                581
#define EFFECT_FROST_NOVA                   582
#define EFFECT_POISON_DART                  583
#define EFFECT_SMOG                         584
#define EFFECT_GUNK_FUNK                    585
#define EFFECT_POISON_POWDER                586
#define EFFECT_GRAVITON_ARM                 587
#define EFFECT_MIST_BALL                    588
#define EFFECT_KINESIS                      589
#define EFFECT_RESERVOIR                    590
#define EFFECT_CANNONADE                    591
#define EFFECT_BURNING_ENVY                 592
#define EFFECT_ACID_ARMOR                   593
#define EFFECT_POWER_SHIFT                  594
#define EFFECT_MAGIC_POWDER                 595
#define EFFECT_PSY_SWAP                     596
#define EFFECT_SHIELDS_UP                   597
#define EFFECT_BERRY_BAD_JOKE               598
#define EFFECT_STALAG_BLAST                 599
#define EFFECT_MOON_BEAM                    600
#define EFFECT_HUNKER_DOWN                  601
#define EFFECT_OVERTAKE                     602
#define EFFECT_POISON_GAS                   603
#define EFFECT_HIGH_ROLL_HIT                604

#define NUM_BATTLE_MOVE_EFFECTS             605

#endif  // GUARD_CONSTANTS_BATTLE_MOVE_EFFECTS_H
