#ifndef GUARD_CONSTANTS_MAP_GROUPS_H
#define GUARD_CONSTANTS_MAP_GROUPS_H

//
// DO NOT MODIFY THIS FILE! It is auto-generated from data/maps/map_groups.json
//

// gMapGroup_PiscesPart1Major
#define MAP_SS_TIDAL_EXTERIOR       (0 | (0 << 8))
#define MAP_PACIFIDLOG_TOWN         (1 | (0 << 8))
#define MAP_BIRCH_MARITIME_LAB      (2 | (0 << 8))
#define MAP_SKY_PILLAR_NEW          (3 | (0 << 8))
#define MAP_SKY_PILLAR_INTERIORS    (4 | (0 << 8))
#define MAP_FLOTSHORE               (5 | (0 << 8))
#define MAP_BASALIN_COAST           (6 | (0 << 8))
#define MAP_NEW_SOOTO               (7 | (0 << 8))
#define MAP_SOOTOPOLIS_CITY_GYM_1F  (8 | (0 << 8))
#define MAP_SOOTOPOLIS_CITY_GYM_B1F (9 | (0 << 8))

// gMapGroup_PiscesPart1Minor
#define MAP_PACIFIDLOG_TOWN_POKEMON_CENTER_1F (0 | (1 << 8))
#define MAP_PACIFIDLOG_TOWN_POKEMON_CENTER_2F (1 | (1 << 8))
#define MAP_SOOTOPOLIS_CITY_POKEMON_CENTER_1F (2 | (1 << 8))
#define MAP_RIVAL_ROOM                        (3 | (1 << 8))
#define MAP_SS_TIDAL_INTERIORS                (4 | (1 << 8))
#define MAP_PACIFIDLOG_INTERIORS              (5 | (1 << 8))
#define MAP_LAB_BASEMENT                      (6 | (1 << 8))
#define MAP_LAB_BASEMENT2                     (7 | (1 << 8))
#define MAP_SOOTOPOLIS_INTERIORS              (8 | (1 << 8))
#define MAP_GYM1CORRIDOR                      (9 | (1 << 8))
#define MAP_SKY_PILLAR_ENTRANCE               (10 | (1 << 8))
#define MAP_SKY_PILLAR_1F                     (11 | (1 << 8))
#define MAP_SKY_PILLAR_2F                     (12 | (1 << 8))
#define MAP_SKY_PILLAR_3F                     (13 | (1 << 8))
#define MAP_SKY_PILLAR_4F                     (14 | (1 << 8))
#define MAP_SKY_PILLAR_5F                     (15 | (1 << 8))
#define MAP_SKY_PILLAR_TOP                    (16 | (1 << 8))
#define MAP_SKY_PILLAR_OUTSIDE                (17 | (1 << 8))
#define MAP_SOOTOPOLIS_CITY                   (18 | (1 << 8))
#define MAP_ROUTE131                          (19 | (1 << 8))
#define MAP_ROUTE129                          (20 | (1 << 8))
#define MAP_SOOTO_RESTAURANT                  (21 | (1 << 8))

// gMapGroup_PiscesPart2Major
#define MAP_CAVE_OF_ORIGIN       (0 | (2 << 8))
#define MAP_MANGROTTO_TUNNEL     (1 | (2 << 8))
#define MAP_MOSSDEEP_CITY        (2 | (2 << 8))
#define MAP_MOSSDEEP_CITY_GYM    (3 | (2 << 8))
#define MAP_COSMOSS_SPACE_CENTER (4 | (2 << 8))

// gMapGroup_PiscesPart2Minor
#define MAP_SOOTOPOLIS_CITY_POKEMON_CENTER_2F (0 | (3 << 8))
#define MAP_MOSSDEEP_CITY_POKEMON_CENTER_1F   (1 | (3 << 8))
#define MAP_MOSSDEEP_INTERIORS                (2 | (3 << 8))
#define MAP_GYM2CORRIDOR                      (3 | (3 << 8))
#define MAP_STEVEN_HOUSE                      (4 | (3 << 8))
#define MAP_STEVEN_CORRIDOR                   (5 | (3 << 8))
#define MAP_STEVEN_MAZE                       (6 | (3 << 8))
#define MAP_SECRET_MOSSDEEP_CAVE              (7 | (3 << 8))
#define MAP_MANGROTTO_ROCK_SMASH_ROOM         (8 | (3 << 8))
#define MAP_FAMILY_MOSS_CAVE                  (9 | (3 << 8))

// gMapGroup_PiscesPart3Major
#define MAP_ROUTE125           (0 | (4 << 8))
#define MAP_ROUTE124           (1 | (4 << 8))
#define MAP_LILYCOVE_CITY      (2 | (4 << 8))
#define MAP_ROUTE121           (3 | (4 << 8))
#define MAP_ROUTE123           (4 | (4 << 8))
#define MAP_MT_PYRE_1F         (5 | (4 << 8))
#define MAP_MT_PYRE_2F         (6 | (4 << 8))
#define MAP_ROUTE122           (7 | (4 << 8))
#define MAP_PETALBURG_CITY_GYM (8 | (4 << 8))
#define MAP_THE_COLD_MINES     (9 | (4 << 8))
#define MAP_ZOTPYRE_GYM        (10 | (4 << 8))
#define MAP_NEW_SUNBEACH       (11 | (4 << 8))

// gMapGroup_PiscesPart3Minor
#define MAP_MOSSDEEP_CITY_POKEMON_CENTER_2F   (0 | (5 << 8))
#define MAP_LILYCOVE_CITY_POKEMON_CENTER_1F   (1 | (5 << 8))
#define MAP_LILYCOVE_CITY_POKEMON_CENTER_2F   (2 | (5 << 8))
#define MAP_VERDANTURF_TOWN_POKEMON_CENTER_1F (3 | (5 << 8))
#define MAP_PRECIPIKE_INTERIORS               (4 | (5 << 8))
#define MAP_OZONE_LILYCOVE_HQ                 (5 | (5 << 8))
#define MAP_LILYCOVE_INTERIORS                (6 | (5 << 8))
#define MAP_LILYCOVE_MUSEUM_NEW               (7 | (5 << 8))
#define MAP_SS_TIDAL_MIDGAME                  (8 | (5 << 8))
#define MAP_SS_TIDAL_MID_TERIORS              (9 | (5 << 8))
#define MAP_PRETTY_PETALS_SCUTTILL            (10 | (5 << 8))
#define MAP_GYM3CORRIDOR                      (11 | (5 << 8))
#define MAP_ZOTPYRE_INTERIORS                 (12 | (5 << 8))
#define MAP_ZOTPYRE_SECRET_BASEMENT           (13 | (5 << 8))
#define MAP_BATTLE_STUDIO_LOBBY               (14 | (5 << 8))
#define MAP_NEW_MAP1                          (15 | (5 << 8))
#define MAP_BATTLE_STUDIO_STORAGE             (16 | (5 << 8))
#define MAP_BATTLE_STUDIO_OFFICE              (17 | (5 << 8))
#define MAP_BATTLE_STUDIO_FAKE_LOBBY          (18 | (5 << 8))
#define MAP_BATTLE_STUDIO_FAKE_ARENA          (19 | (5 << 8))
#define MAP_BATTLE_STUDIO_CAGES               (20 | (5 << 8))

// gMapGroup_PiscesPart4Major
#define MAP_ROUTE120         (0 | (6 << 8))
#define MAP_SCUTTILL_HUTS    (1 | (6 << 8))
#define MAP_CANOPOUR_WILDS   (2 | (6 << 8))
#define MAP_PERPLUME_MAZE    (3 | (6 << 8))
#define MAP_FORTREE_CITY     (4 | (6 << 8))
#define MAP_FORTREE_CITY_GYM (5 | (6 << 8))

// gMapGroup_PiscesPart4Minor
#define MAP_VERDANTURF_TOWN_POKEMON_CENTER_2F (0 | (7 << 8))
#define MAP_VERDANTURF_TOWN_MART              (1 | (7 << 8))
#define MAP_FORTREE_CITY_POKEMON_CENTER_1F    (2 | (7 << 8))
#define MAP_SCUTTILL_SECRET_TREE_HOUSE        (3 | (7 << 8))
#define MAP_GYM4CORRIDOR                      (4 | (7 << 8))

// gMapGroup_PiscesPart5Major
#define MAP_OZONE_INSTITUTE        (0 | (8 << 8))
#define MAP_MASORIED_HIKE          (1 | (8 << 8))
#define MAP_ROUTE113               (2 | (8 << 8))
#define MAP_CRIMNEY_CLIMB          (3 | (8 << 8))
#define MAP_JAGGRO_PASS            (4 | (8 << 8))
#define MAP_FALLARBOR_NEW          (5 | (8 << 8))
#define MAP_FIERY_PATH             (6 | (8 << 8))
#define MAP_LAVARIDGE_INT          (7 | (8 << 8))
#define MAP_LAVARIDGE_TOWN_GYM_1F  (8 | (8 << 8))
#define MAP_LAVARIDGE_TOWN_GYM_B1F (9 | (8 << 8))

// gMapGroup_PiscesPart5Minor
#define MAP_FORTREE_CITY_POKEMON_CENTER_2F   (0 | (9 << 8))
#define MAP_FORTREE_CITY_MART                (1 | (9 << 8))
#define MAP_FALLARBOR_TOWN_POKEMON_CENTER_1F (2 | (9 << 8))
#define MAP_LAVARIDGE_TOWN_POKEMON_CENTER_1F (3 | (9 << 8))
#define MAP_GYM5CORRIDOR                     (4 | (9 << 8))

// gMapGroup_PiscesPart6Major
#define MAP_SWELTORN_TRANSITION_CAVE  (0 | (10 << 8))
#define MAP_SWELTORN_DESERT           (1 | (10 << 8))
#define MAP_SWELTORN_PALACE           (2 | (10 << 8))
#define MAP_SWELTORN_PALACE_OUTSIDE   (3 | (10 << 8))
#define MAP_MAUVILLE_NEW              (4 | (10 << 8))
#define MAP_NEW_MAUVILLE_FLOOR1       (5 | (10 << 8))
#define MAP_NEW_MAUVILLE_FLOOR2       (6 | (10 << 8))
#define MAP_HATCHLOAM_FIELD           (7 | (10 << 8))
#define MAP_CYCLING_ROAD              (8 | (10 << 8))
#define MAP_SEA_MAUVILLE              (9 | (10 << 8))
#define MAP_MAINTENANCE               (10 | (10 << 8))
#define MAP_NEW_MAUVILLE_ENTRANCE     (11 | (10 << 8))
#define MAP_NEW_MAUVILLE_INSIDE       (12 | (10 << 8))
#define MAP_MAUVILLE_CITY_GAME_CORNER (13 | (10 << 8))
#define MAP_MAINTENANCE_BONDING_ARENA (14 | (10 << 8))
#define MAP_VERDANTURF_NEW            (15 | (10 << 8))
#define MAP_MAUVILLE_CITY_GYM         (16 | (10 << 8))

// gMapGroup_PiscesPart6Minor
#define MAP_LAVARIDGE_TOWN_POKEMON_CENTER_2F  (0 | (11 << 8))
#define MAP_NEW_MAUVILLE_CENTER1              (1 | (11 << 8))
#define MAP_NEW_MAUVILLE_CENTER2              (2 | (11 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_ENTRANCE     (3 | (11 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_END          (4 | (11 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_CORRIDOR     (5 | (11 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE1      (6 | (11 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE2      (7 | (11 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE3      (8 | (11 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE4      (9 | (11 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE5      (10 | (11 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE6      (11 | (11 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE7      (12 | (11 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE8      (13 | (11 << 8))
#define MAP_MAUVILLE_CITY_POKEMON_CENTER_2F   (14 | (11 << 8))
#define MAP_SLATEPORT_CITY_POKEMON_CENTER_1F  (15 | (11 << 8))
#define MAP_BATTLE_FRONTIER_POKEMON_CENTER_1F (16 | (11 << 8))
#define MAP_GYM6CORRIDOR                      (17 | (11 << 8))

// gMapGroup_PiscesPart7Major
#define MAP_SLATEPORT_SHORE       (0 | (12 << 8))
#define MAP_NAVIGULF_WAVES        (1 | (12 << 8))
#define MAP_DEWFORD_NEW           (2 | (12 << 8))
#define MAP_STRAE_SEAPATH         (3 | (12 << 8))
#define MAP_SAILORS_PAUSE         (4 | (12 << 8))
#define MAP_SAILORS_PAUSE_SHIPS   (5 | (12 << 8))
#define MAP_SHOAL_CAVE_NEW_FLOOR1 (6 | (12 << 8))
#define MAP_SHOAL_CAVE_NEW_FLOOR2 (7 | (12 << 8))
#define MAP_DEWFORD_TOWN_GYM      (8 | (12 << 8))

// gMapGroup_PiscesPart7Minor
#define MAP_DEWFORD_TOWN_POKEMON_CENTER_1F (0 | (13 << 8))
#define MAP_GYM7CORRIDOR                   (1 | (13 << 8))

// gMapGroup_PiscesPart8Major
#define MAP_DETERMANITE_BEACH    (0 | (14 << 8))
#define MAP_DETERMANITE_QUARRY   (1 | (14 << 8))
#define MAP_DETERMANITE_QUAR_B1F (2 | (14 << 8))
#define MAP_WISHWELL_OCEAN       (3 | (14 << 8))
#define MAP_RUSTBURG_WHARF       (4 | (14 << 8))
#define MAP_UNDURA_TUNNELS       (5 | (14 << 8))
#define MAP_UNDURA_TUNNELS_DEEP  (6 | (14 << 8))
#define MAP_WHISPER_CLIFF        (7 | (14 << 8))
#define MAP_MIDNEOR_FALLS        (8 | (14 << 8))
#define MAP_MIDNEOR_FALLS_CAVE   (9 | (14 << 8))
#define MAP_RUSTBORO_NEW         (10 | (14 << 8))
#define MAP_RUSTBORO_CITY_GYM    (11 | (14 << 8))

// gMapGroup_PiscesPart8Minor
#define MAP_DEWFORD_TOWN_POKEMON_CENTER_2F   (0 | (15 << 8))
#define MAP_FALLARBOR_TOWN_POKEMON_CENTER_2F (1 | (15 << 8))
#define MAP_RUSTBORO_CITY_POKEMON_CENTER_1F  (2 | (15 << 8))
#define MAP_GYM8CORRIDOR                     (3 | (15 << 8))

// gMapGroup_PiscesPart9Major
#define MAP_PETALBURG_NEW       (0 | (16 << 8))
#define MAP_PETALBURG_WOODS_NEW (1 | (16 << 8))
#define MAP_OLDALE_NEW          (2 | (16 << 8))
#define MAP_NOVICE_WALK         (3 | (16 << 8))
#define MAP_LITTLEROOT_NEW      (4 | (16 << 8))
#define MAP_PENDING_DEV         (5 | (16 << 8))
#define MAP_TEST_MAP            (6 | (16 << 8))

// gMapGroup_PiscesPart9Minor
#define MAP_PETALBURG_CITY_POKEMON_CENTER_1F (0 | (17 << 8))
#define MAP_OLDALE_TOWN_POKEMON_CENTER_1F    (1 | (17 << 8))
#define MAP_OLDALE_TOWN_POKEMON_CENTER_2F    (2 | (17 << 8))

// gMapGroup_PiscesPart10Major
#define MAP_CRIMNEY_CALDERA             (0 | (18 << 8))
#define MAP_METEOR_NADIR                (1 | (18 << 8))
#define MAP_EVER_GRANDE_TRANSITION_CAVE (2 | (18 << 8))
#define MAP_EVER_GRANDE_ROAD            (3 | (18 << 8))
#define MAP_EVER_GRANDE_PEAK            (4 | (18 << 8))

// gMapGroup_PiscesPart10Minor
#define MAP_EVER_GRANDE_CITY_POKEMON_CENTER_1F (0 | (19 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_CENTER_2F (1 | (19 << 8))

// gMapGroup_TownsAndRoutes
#define MAP_PETALBURG_CITY      (0 | (20 << 8))
#define MAP_SLATEPORT_CITY      (1 | (20 << 8))
#define MAP_MAUVILLE_CITY       (2 | (20 << 8))
#define MAP_RUSTBORO_CITY       (3 | (20 << 8))
#define MAP_EVER_GRANDE_CITY    (4 | (20 << 8))
#define MAP_LITTLEROOT_TOWN     (5 | (20 << 8))
#define MAP_OLDALE_TOWN         (6 | (20 << 8))
#define MAP_DEWFORD_TOWN        (7 | (20 << 8))
#define MAP_LAVARIDGE_TOWN      (8 | (20 << 8))
#define MAP_FALLARBOR_TOWN      (9 | (20 << 8))
#define MAP_VERDANTURF_TOWN     (10 | (20 << 8))
#define MAP_ROUTE101            (11 | (20 << 8))
#define MAP_ROUTE102            (12 | (20 << 8))
#define MAP_ROUTE103            (13 | (20 << 8))
#define MAP_ROUTE104            (14 | (20 << 8))
#define MAP_ROUTE105            (15 | (20 << 8))
#define MAP_ROUTE106            (16 | (20 << 8))
#define MAP_ROUTE107            (17 | (20 << 8))
#define MAP_ROUTE108            (18 | (20 << 8))
#define MAP_ROUTE109            (19 | (20 << 8))
#define MAP_ROUTE110            (20 | (20 << 8))
#define MAP_ROUTE111            (21 | (20 << 8))
#define MAP_ROUTE112            (22 | (20 << 8))
#define MAP_ROUTE114            (23 | (20 << 8))
#define MAP_ROUTE115            (24 | (20 << 8))
#define MAP_ROUTE116            (25 | (20 << 8))
#define MAP_ROUTE117            (26 | (20 << 8))
#define MAP_ROUTE118            (27 | (20 << 8))
#define MAP_ROUTE119            (28 | (20 << 8))
#define MAP_ROUTE126            (29 | (20 << 8))
#define MAP_ROUTE127            (30 | (20 << 8))
#define MAP_ROUTE128            (31 | (20 << 8))
#define MAP_ROUTE130            (32 | (20 << 8))
#define MAP_ROUTE132            (33 | (20 << 8))
#define MAP_ROUTE133            (34 | (20 << 8))
#define MAP_ROUTE134            (35 | (20 << 8))
#define MAP_UNDERWATER_ROUTE124 (36 | (20 << 8))
#define MAP_UNDERWATER_ROUTE126 (37 | (20 << 8))
#define MAP_UNDERWATER_ROUTE127 (38 | (20 << 8))
#define MAP_UNDERWATER_ROUTE128 (39 | (20 << 8))
#define MAP_UNDERWATER_ROUTE129 (40 | (20 << 8))
#define MAP_UNDERWATER_ROUTE105 (41 | (20 << 8))
#define MAP_UNDERWATER_ROUTE125 (42 | (20 << 8))

// gMapGroup_IndoorLittleroot
#define MAP_LITTLEROOT_TOWN_BRENDANS_HOUSE_1F    (0 | (21 << 8))
#define MAP_LITTLEROOT_TOWN_BRENDANS_HOUSE_2F    (1 | (21 << 8))
#define MAP_LITTLEROOT_TOWN_MAYS_HOUSE_1F        (2 | (21 << 8))
#define MAP_LITTLEROOT_TOWN_MAYS_HOUSE_2F        (3 | (21 << 8))
#define MAP_LITTLEROOT_TOWN_PROFESSOR_BIRCHS_LAB (4 | (21 << 8))

// gMapGroup_IndoorOldale
#define MAP_OLDALE_TOWN_HOUSE1 (0 | (22 << 8))
#define MAP_OLDALE_TOWN_HOUSE2 (1 | (22 << 8))
#define MAP_OLDALE_TOWN_MART   (2 | (22 << 8))

// gMapGroup_IndoorDewford
#define MAP_DEWFORD_TOWN_HOUSE1 (0 | (23 << 8))
#define MAP_DEWFORD_TOWN_HALL   (1 | (23 << 8))
#define MAP_DEWFORD_TOWN_HOUSE2 (2 | (23 << 8))

// gMapGroup_IndoorLavaridge
#define MAP_LAVARIDGE_TOWN_HERB_SHOP (0 | (24 << 8))
#define MAP_LAVARIDGE_TOWN_HOUSE     (1 | (24 << 8))
#define MAP_LAVARIDGE_TOWN_MART      (2 | (24 << 8))

// gMapGroup_IndoorFallarbor
#define MAP_FALLARBOR_TOWN_MART                    (0 | (25 << 8))
#define MAP_FALLARBOR_TOWN_BATTLE_TENT_LOBBY       (1 | (25 << 8))
#define MAP_FALLARBOR_TOWN_BATTLE_TENT_CORRIDOR    (2 | (25 << 8))
#define MAP_FALLARBOR_TOWN_BATTLE_TENT_BATTLE_ROOM (3 | (25 << 8))
#define MAP_FALLARBOR_TOWN_COZMOS_HOUSE            (4 | (25 << 8))
#define MAP_FALLARBOR_TOWN_MOVE_RELEARNERS_HOUSE   (5 | (25 << 8))

// gMapGroup_IndoorVerdanturf
#define MAP_VERDANTURF_TOWN_BATTLE_TENT_LOBBY       (0 | (26 << 8))
#define MAP_VERDANTURF_TOWN_BATTLE_TENT_CORRIDOR    (1 | (26 << 8))
#define MAP_VERDANTURF_TOWN_BATTLE_TENT_BATTLE_ROOM (2 | (26 << 8))
#define MAP_VERDANTURF_TOWN_WANDAS_HOUSE            (3 | (26 << 8))
#define MAP_VERDANTURF_TOWN_FRIENDSHIP_RATERS_HOUSE (4 | (26 << 8))
#define MAP_VERDANTURF_TOWN_HOUSE                   (5 | (26 << 8))

// gMapGroup_IndoorPacifidlog
#define MAP_PACIFIDLOG_TOWN_HOUSE1 (0 | (27 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE2 (1 | (27 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE3 (2 | (27 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE4 (3 | (27 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE5 (4 | (27 << 8))

// gMapGroup_IndoorPetalburg
#define MAP_PETALBURG_CITY_WALLYS_HOUSE      (0 | (28 << 8))
#define MAP_PETALBURG_CITY_HOUSE1            (1 | (28 << 8))
#define MAP_PETALBURG_CITY_HOUSE2            (2 | (28 << 8))
#define MAP_PETALBURG_CITY_POKEMON_CENTER_2F (3 | (28 << 8))
#define MAP_PETALBURG_CITY_MART              (4 | (28 << 8))

// gMapGroup_IndoorSlateport
#define MAP_SLATEPORT_CITY_STERNS_SHIPYARD_1F      (0 | (29 << 8))
#define MAP_SLATEPORT_CITY_STERNS_SHIPYARD_2F      (1 | (29 << 8))
#define MAP_SLATEPORT_CITY_BATTLE_TENT_LOBBY       (2 | (29 << 8))
#define MAP_SLATEPORT_CITY_BATTLE_TENT_CORRIDOR    (3 | (29 << 8))
#define MAP_SLATEPORT_CITY_BATTLE_TENT_BATTLE_ROOM (4 | (29 << 8))
#define MAP_SLATEPORT_CITY_NAME_RATERS_HOUSE       (5 | (29 << 8))
#define MAP_SLATEPORT_CITY_POKEMON_FAN_CLUB        (6 | (29 << 8))
#define MAP_SLATEPORT_CITY_OCEANIC_MUSEUM_1F       (7 | (29 << 8))
#define MAP_SLATEPORT_CITY_OCEANIC_MUSEUM_2F       (8 | (29 << 8))
#define MAP_SLATEPORT_CITY_HARBOR                  (9 | (29 << 8))
#define MAP_SLATEPORT_CITY_HOUSE                   (10 | (29 << 8))
#define MAP_SLATEPORT_CITY_POKEMON_CENTER_2F       (11 | (29 << 8))
#define MAP_SLATEPORT_CITY_MART                    (12 | (29 << 8))

// gMapGroup_IndoorMauville
#define MAP_MAUVILLE_CITY_BIKE_SHOP         (0 | (30 << 8))
#define MAP_MAUVILLE_CITY_HOUSE1            (1 | (30 << 8))
#define MAP_MAUVILLE_CITY_HOUSE2            (2 | (30 << 8))
#define MAP_MAUVILLE_CITY_POKEMON_CENTER_1F (3 | (30 << 8))
#define MAP_MAUVILLE_CITY_MART              (4 | (30 << 8))

// gMapGroup_IndoorRustboro
#define MAP_RUSTBORO_CITY_DEVON_CORP_1F     (0 | (31 << 8))
#define MAP_RUSTBORO_CITY_DEVON_CORP_2F     (1 | (31 << 8))
#define MAP_RUSTBORO_CITY_DEVON_CORP_3F     (2 | (31 << 8))
#define MAP_RUSTBORO_CITY_POKEMON_SCHOOL    (3 | (31 << 8))
#define MAP_RUSTBORO_CITY_POKEMON_CENTER_2F (4 | (31 << 8))
#define MAP_RUSTBORO_CITY_MART              (5 | (31 << 8))
#define MAP_RUSTBORO_CITY_FLAT1_1F          (6 | (31 << 8))
#define MAP_RUSTBORO_CITY_FLAT1_2F          (7 | (31 << 8))
#define MAP_RUSTBORO_CITY_HOUSE1            (8 | (31 << 8))
#define MAP_RUSTBORO_CITY_CUTTERS_HOUSE     (9 | (31 << 8))
#define MAP_RUSTBORO_CITY_HOUSE2            (10 | (31 << 8))
#define MAP_RUSTBORO_CITY_FLAT2_1F          (11 | (31 << 8))
#define MAP_RUSTBORO_CITY_FLAT2_2F          (12 | (31 << 8))
#define MAP_RUSTBORO_CITY_FLAT2_3F          (13 | (31 << 8))
#define MAP_RUSTBORO_CITY_HOUSE3            (14 | (31 << 8))

// gMapGroup_IndoorFortree
#define MAP_FORTREE_CITY_HOUSE1          (0 | (32 << 8))
#define MAP_FORTREE_CITY_HOUSE2          (1 | (32 << 8))
#define MAP_FORTREE_CITY_HOUSE3          (2 | (32 << 8))
#define MAP_FORTREE_CITY_HOUSE4          (3 | (32 << 8))
#define MAP_FORTREE_CITY_HOUSE5          (4 | (32 << 8))
#define MAP_FORTREE_CITY_DECORATION_SHOP (5 | (32 << 8))

// gMapGroup_IndoorLilycove
#define MAP_LILYCOVE_CITY_COVE_LILY_MOTEL_1F        (0 | (33 << 8))
#define MAP_LILYCOVE_CITY_COVE_LILY_MOTEL_2F        (1 | (33 << 8))
#define MAP_LILYCOVE_CITY_LILYCOVE_MUSEUM_1F        (2 | (33 << 8))
#define MAP_LILYCOVE_CITY_LILYCOVE_MUSEUM_2F        (3 | (33 << 8))
#define MAP_LILYCOVE_CITY_CONTEST_LOBBY             (4 | (33 << 8))
#define MAP_LILYCOVE_CITY_CONTEST_HALL              (5 | (33 << 8))
#define MAP_LILYCOVE_CITY_UNUSED_MART               (6 | (33 << 8))
#define MAP_LILYCOVE_CITY_POKEMON_TRAINER_FAN_CLUB  (7 | (33 << 8))
#define MAP_LILYCOVE_CITY_HARBOR                    (8 | (33 << 8))
#define MAP_LILYCOVE_CITY_MOVE_DELETERS_HOUSE       (9 | (33 << 8))
#define MAP_LILYCOVE_CITY_HOUSE1                    (10 | (33 << 8))
#define MAP_LILYCOVE_CITY_HOUSE2                    (11 | (33 << 8))
#define MAP_LILYCOVE_CITY_HOUSE3                    (12 | (33 << 8))
#define MAP_LILYCOVE_CITY_HOUSE4                    (13 | (33 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_1F       (14 | (33 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_2F       (15 | (33 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_3F       (16 | (33 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_4F       (17 | (33 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_5F       (18 | (33 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_ROOFTOP  (19 | (33 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_ELEVATOR (20 | (33 << 8))

// gMapGroup_IndoorMossdeep
#define MAP_MOSSDEEP_CITY_HOUSE1          (0 | (34 << 8))
#define MAP_MOSSDEEP_CITY_HOUSE2          (1 | (34 << 8))
#define MAP_MOSSDEEP_CITY_MART            (2 | (34 << 8))
#define MAP_MOSSDEEP_CITY_HOUSE3          (3 | (34 << 8))
#define MAP_MOSSDEEP_CITY_STEVENS_HOUSE   (4 | (34 << 8))
#define MAP_MOSSDEEP_CITY_HOUSE4          (5 | (34 << 8))
#define MAP_MOSSDEEP_CITY_SPACE_CENTER_1F (6 | (34 << 8))
#define MAP_MOSSDEEP_CITY_SPACE_CENTER_2F (7 | (34 << 8))
#define MAP_MOSSDEEP_CITY_GAME_CORNER_1F  (8 | (34 << 8))
#define MAP_MOSSDEEP_CITY_GAME_CORNER_B1F (9 | (34 << 8))

// gMapGroup_IndoorSootopolis
#define MAP_SOOTOPOLIS_CITY_MART                     (0 | (35 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE1                   (1 | (35 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE2                   (2 | (35 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE3                   (3 | (35 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE4                   (4 | (35 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE5                   (5 | (35 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE6                   (6 | (35 << 8))
#define MAP_SOOTOPOLIS_CITY_HOUSE7                   (7 | (35 << 8))
#define MAP_SOOTOPOLIS_CITY_LOTAD_AND_SEEDOT_HOUSE   (8 | (35 << 8))
#define MAP_SOOTOPOLIS_CITY_MYSTERY_EVENTS_HOUSE_1F  (9 | (35 << 8))
#define MAP_SOOTOPOLIS_CITY_MYSTERY_EVENTS_HOUSE_B1F (10 | (35 << 8))

// gMapGroup_IndoorEverGrande
#define MAP_EVER_GRANDE_CITY_SIDNEYS_ROOM      (0 | (36 << 8))
#define MAP_EVER_GRANDE_CITY_PHOEBES_ROOM      (1 | (36 << 8))
#define MAP_EVER_GRANDE_CITY_GLACIAS_ROOM      (2 | (36 << 8))
#define MAP_EVER_GRANDE_CITY_DRAKES_ROOM       (3 | (36 << 8))
#define MAP_EVER_GRANDE_CITY_CHAMPIONS_ROOM    (4 | (36 << 8))
#define MAP_EVER_GRANDE_CITY_HALL1             (5 | (36 << 8))
#define MAP_EVER_GRANDE_CITY_HALL2             (6 | (36 << 8))
#define MAP_EVER_GRANDE_CITY_HALL3             (7 | (36 << 8))
#define MAP_EVER_GRANDE_CITY_HALL4             (8 | (36 << 8))
#define MAP_EVER_GRANDE_CITY_HALL5             (9 | (36 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_LEAGUE_1F (10 | (36 << 8))
#define MAP_EVER_GRANDE_CITY_HALL_OF_FAME      (11 | (36 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_LEAGUE_2F (12 | (36 << 8))

// gMapGroup_IndoorRoute104
#define MAP_ROUTE104_MR_BRINEYS_HOUSE         (0 | (37 << 8))
#define MAP_ROUTE104_PRETTY_PETAL_FLOWER_SHOP (1 | (37 << 8))

// gMapGroup_IndoorRoute111
#define MAP_ROUTE111_WINSTRATE_FAMILYS_HOUSE (0 | (38 << 8))
#define MAP_ROUTE111_OLD_LADYS_REST_STOP     (1 | (38 << 8))

// gMapGroup_IndoorRoute112
#define MAP_ROUTE112_CABLE_CAR_STATION   (0 | (39 << 8))
#define MAP_MT_CHIMNEY_CABLE_CAR_STATION (1 | (39 << 8))

// gMapGroup_IndoorRoute114
#define MAP_ROUTE114_FOSSIL_MANIACS_HOUSE  (0 | (40 << 8))
#define MAP_ROUTE114_FOSSIL_MANIACS_TUNNEL (1 | (40 << 8))
#define MAP_ROUTE114_LANETTES_HOUSE        (2 | (40 << 8))

// gMapGroup_IndoorRoute116
#define MAP_ROUTE116_TUNNELERS_REST_HOUSE (0 | (41 << 8))

// gMapGroup_IndoorRoute117
#define MAP_ROUTE117_POKEMON_DAY_CARE (0 | (42 << 8))

// gMapGroup_IndoorRoute121
#define MAP_ROUTE121_SAFARI_ZONE_ENTRANCE (0 | (43 << 8))

// gMapGroup_Dungeons
#define MAP_METEOR_FALLS_1F_1R                       (0 | (44 << 8))
#define MAP_METEOR_FALLS_1F_2R                       (1 | (44 << 8))
#define MAP_METEOR_FALLS_B1F_1R                      (2 | (44 << 8))
#define MAP_METEOR_FALLS_B1F_2R                      (3 | (44 << 8))
#define MAP_RUSTURF_TUNNEL                           (4 | (44 << 8))
#define MAP_UNDERWATER_SOOTOPOLIS_CITY               (5 | (44 << 8))
#define MAP_DESERT_RUINS                             (6 | (44 << 8))
#define MAP_GRANITE_CAVE_1F                          (7 | (44 << 8))
#define MAP_GRANITE_CAVE_B1F                         (8 | (44 << 8))
#define MAP_GRANITE_CAVE_B2F                         (9 | (44 << 8))
#define MAP_GRANITE_CAVE_STEVENS_ROOM                (10 | (44 << 8))
#define MAP_PETALBURG_WOODS                          (11 | (44 << 8))
#define MAP_MT_CHIMNEY                               (12 | (44 << 8))
#define MAP_JAGGED_PASS                              (13 | (44 << 8))
#define MAP_MT_PYRE_3F                               (14 | (44 << 8))
#define MAP_MT_PYRE_4F                               (15 | (44 << 8))
#define MAP_MT_PYRE_5F                               (16 | (44 << 8))
#define MAP_MT_PYRE_6F                               (17 | (44 << 8))
#define MAP_MT_PYRE_EXTERIOR                         (18 | (44 << 8))
#define MAP_MT_PYRE_SUMMIT                           (19 | (44 << 8))
#define MAP_AQUA_HIDEOUT_1F                          (20 | (44 << 8))
#define MAP_AQUA_HIDEOUT_B1F                         (21 | (44 << 8))
#define MAP_AQUA_HIDEOUT_B2F                         (22 | (44 << 8))
#define MAP_UNDERWATER_SEAFLOOR_CAVERN               (23 | (44 << 8))
#define MAP_SEAFLOOR_CAVERN_ENTRANCE                 (24 | (44 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM1                    (25 | (44 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM2                    (26 | (44 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM3                    (27 | (44 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM4                    (28 | (44 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM5                    (29 | (44 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM6                    (30 | (44 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM7                    (31 | (44 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM8                    (32 | (44 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM9                    (33 | (44 << 8))
#define MAP_CAVE_OF_ORIGIN_ENTRANCE                  (34 | (44 << 8))
#define MAP_CAVE_OF_ORIGIN_1F                        (35 | (44 << 8))
#define MAP_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP1 (36 | (44 << 8))
#define MAP_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP2 (37 | (44 << 8))
#define MAP_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP3 (38 | (44 << 8))
#define MAP_CAVE_OF_ORIGIN_B1F                       (39 | (44 << 8))
#define MAP_VICTORY_ROAD_1F                          (40 | (44 << 8))
#define MAP_VICTORY_ROAD_B1F                         (41 | (44 << 8))
#define MAP_VICTORY_ROAD_B2F                         (42 | (44 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_ENTRANCE_ROOM        (43 | (44 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_INNER_ROOM           (44 | (44 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_STAIRS_ROOM          (45 | (44 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_LOWER_ROOM           (46 | (44 << 8))
#define MAP_SHOAL_CAVE_HIGH_TIDE_ENTRANCE_ROOM       (47 | (44 << 8))
#define MAP_SHOAL_CAVE_HIGH_TIDE_INNER_ROOM          (48 | (44 << 8))
#define MAP_ABANDONED_SHIP_DECK                      (49 | (44 << 8))
#define MAP_ABANDONED_SHIP_CORRIDORS_1F              (50 | (44 << 8))
#define MAP_ABANDONED_SHIP_ROOMS_1F                  (51 | (44 << 8))
#define MAP_ABANDONED_SHIP_CORRIDORS_B1F             (52 | (44 << 8))
#define MAP_ABANDONED_SHIP_ROOMS_B1F                 (53 | (44 << 8))
#define MAP_ABANDONED_SHIP_ROOMS2_B1F                (54 | (44 << 8))
#define MAP_ABANDONED_SHIP_UNDERWATER1               (55 | (44 << 8))
#define MAP_ABANDONED_SHIP_ROOM_B1F                  (56 | (44 << 8))
#define MAP_ABANDONED_SHIP_ROOMS2_1F                 (57 | (44 << 8))
#define MAP_ABANDONED_SHIP_CAPTAINS_OFFICE           (58 | (44 << 8))
#define MAP_ABANDONED_SHIP_UNDERWATER2               (59 | (44 << 8))
#define MAP_ABANDONED_SHIP_HIDDEN_FLOOR_CORRIDORS    (60 | (44 << 8))
#define MAP_ABANDONED_SHIP_HIDDEN_FLOOR_ROOMS        (61 | (44 << 8))
#define MAP_ISLAND_CAVE                              (62 | (44 << 8))
#define MAP_ANCIENT_TOMB                             (63 | (44 << 8))
#define MAP_UNDERWATER_ROUTE134                      (64 | (44 << 8))
#define MAP_UNDERWATER_SEALED_CHAMBER                (65 | (44 << 8))
#define MAP_SEALED_CHAMBER_OUTER_ROOM                (66 | (44 << 8))
#define MAP_SEALED_CHAMBER_INNER_ROOM                (67 | (44 << 8))
#define MAP_SCORCHED_SLAB                            (68 | (44 << 8))
#define MAP_AQUA_HIDEOUT_UNUSED_RUBY_MAP1            (69 | (44 << 8))
#define MAP_AQUA_HIDEOUT_UNUSED_RUBY_MAP2            (70 | (44 << 8))
#define MAP_AQUA_HIDEOUT_UNUSED_RUBY_MAP3            (71 | (44 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_ICE_ROOM             (72 | (44 << 8))
#define MAP_MAGMA_HIDEOUT_1F                         (73 | (44 << 8))
#define MAP_MAGMA_HIDEOUT_2F_1R                      (74 | (44 << 8))
#define MAP_MAGMA_HIDEOUT_2F_2R                      (75 | (44 << 8))
#define MAP_MAGMA_HIDEOUT_3F_1R                      (76 | (44 << 8))
#define MAP_MAGMA_HIDEOUT_3F_2R                      (77 | (44 << 8))
#define MAP_MAGMA_HIDEOUT_4F                         (78 | (44 << 8))
#define MAP_MAGMA_HIDEOUT_3F_3R                      (79 | (44 << 8))
#define MAP_MAGMA_HIDEOUT_2F_3R                      (80 | (44 << 8))
#define MAP_MIRAGE_TOWER_1F                          (81 | (44 << 8))
#define MAP_MIRAGE_TOWER_2F                          (82 | (44 << 8))
#define MAP_MIRAGE_TOWER_3F                          (83 | (44 << 8))
#define MAP_MIRAGE_TOWER_4F                          (84 | (44 << 8))
#define MAP_DESERT_UNDERPASS                         (85 | (44 << 8))
#define MAP_ARTISAN_CAVE_B1F                         (86 | (44 << 8))
#define MAP_ARTISAN_CAVE_1F                          (87 | (44 << 8))
#define MAP_UNDERWATER_MARINE_CAVE                   (88 | (44 << 8))
#define MAP_MARINE_CAVE_ENTRANCE                     (89 | (44 << 8))
#define MAP_MARINE_CAVE_END                          (90 | (44 << 8))
#define MAP_TERRA_CAVE_ENTRANCE                      (91 | (44 << 8))
#define MAP_TERRA_CAVE_END                           (92 | (44 << 8))
#define MAP_ALTERING_CAVE                            (93 | (44 << 8))
#define MAP_METEOR_FALLS_STEVENS_CAVE                (94 | (44 << 8))

// gMapGroup_IndoorDynamic
#define MAP_SECRET_BASE_RED_CAVE1    (0 | (45 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE1  (1 | (45 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE1   (2 | (45 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE1 (3 | (45 << 8))
#define MAP_SECRET_BASE_TREE1        (4 | (45 << 8))
#define MAP_SECRET_BASE_SHRUB1       (5 | (45 << 8))
#define MAP_SECRET_BASE_RED_CAVE2    (6 | (45 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE2  (7 | (45 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE2   (8 | (45 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE2 (9 | (45 << 8))
#define MAP_SECRET_BASE_TREE2        (10 | (45 << 8))
#define MAP_SECRET_BASE_SHRUB2       (11 | (45 << 8))
#define MAP_SECRET_BASE_RED_CAVE3    (12 | (45 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE3  (13 | (45 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE3   (14 | (45 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE3 (15 | (45 << 8))
#define MAP_SECRET_BASE_TREE3        (16 | (45 << 8))
#define MAP_SECRET_BASE_SHRUB3       (17 | (45 << 8))
#define MAP_SECRET_BASE_RED_CAVE4    (18 | (45 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE4  (19 | (45 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE4   (20 | (45 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE4 (21 | (45 << 8))
#define MAP_SECRET_BASE_TREE4        (22 | (45 << 8))
#define MAP_SECRET_BASE_SHRUB4       (23 | (45 << 8))
#define MAP_BATTLE_COLOSSEUM_2P      (24 | (45 << 8))
#define MAP_TRADE_CENTER             (25 | (45 << 8))
#define MAP_RECORD_CORNER            (26 | (45 << 8))
#define MAP_BATTLE_COLOSSEUM_4P      (27 | (45 << 8))
#define MAP_CONTEST_HALL             (28 | (45 << 8))
#define MAP_UNUSED_CONTEST_HALL1     (29 | (45 << 8))
#define MAP_UNUSED_CONTEST_HALL2     (30 | (45 << 8))
#define MAP_UNUSED_CONTEST_HALL3     (31 | (45 << 8))
#define MAP_UNUSED_CONTEST_HALL4     (32 | (45 << 8))
#define MAP_UNUSED_CONTEST_HALL5     (33 | (45 << 8))
#define MAP_UNUSED_CONTEST_HALL6     (34 | (45 << 8))
#define MAP_CONTEST_HALL_BEAUTY      (35 | (45 << 8))
#define MAP_CONTEST_HALL_TOUGH       (36 | (45 << 8))
#define MAP_CONTEST_HALL_COOL        (37 | (45 << 8))
#define MAP_CONTEST_HALL_SMART       (38 | (45 << 8))
#define MAP_CONTEST_HALL_CUTE        (39 | (45 << 8))
#define MAP_INSIDE_OF_TRUCK          (40 | (45 << 8))
#define MAP_SS_TIDAL_CORRIDOR        (41 | (45 << 8))
#define MAP_SS_TIDAL_LOWER_DECK      (42 | (45 << 8))
#define MAP_SS_TIDAL_ROOMS           (43 | (45 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE01  (44 | (45 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE02  (45 | (45 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE03  (46 | (45 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE04  (47 | (45 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE05  (48 | (45 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE06  (49 | (45 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE07  (50 | (45 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE08  (51 | (45 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE09  (52 | (45 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE10  (53 | (45 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE11  (54 | (45 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE12  (55 | (45 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE13  (56 | (45 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE14  (57 | (45 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE15  (58 | (45 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE16  (59 | (45 << 8))
#define MAP_UNION_ROOM               (60 | (45 << 8))

// gMapGroup_SpecialArea
#define MAP_SAFARI_ZONE_NORTHWEST                           (0 | (46 << 8))
#define MAP_SAFARI_ZONE_NORTH                               (1 | (46 << 8))
#define MAP_SAFARI_ZONE_SOUTHWEST                           (2 | (46 << 8))
#define MAP_SAFARI_ZONE_SOUTH                               (3 | (46 << 8))
#define MAP_BATTLE_FRONTIER_OUTSIDE_WEST                    (4 | (46 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_LOBBY              (5 | (46 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_ELEVATOR           (6 | (46 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_CORRIDOR           (7 | (46 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_BATTLE_ROOM        (8 | (46 << 8))
#define MAP_SOUTHERN_ISLAND_EXTERIOR                        (9 | (46 << 8))
#define MAP_SOUTHERN_ISLAND_INTERIOR                        (10 | (46 << 8))
#define MAP_SAFARI_ZONE_REST_HOUSE                          (11 | (46 << 8))
#define MAP_SAFARI_ZONE_NORTHEAST                           (12 | (46 << 8))
#define MAP_SAFARI_ZONE_SOUTHEAST                           (13 | (46 << 8))
#define MAP_BATTLE_FRONTIER_OUTSIDE_EAST                    (14 | (46 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_PARTNER_ROOM (15 | (46 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_CORRIDOR     (16 | (46 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_BATTLE_ROOM  (17 | (46 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_LOBBY               (18 | (46 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_CORRIDOR            (19 | (46 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_PRE_BATTLE_ROOM     (20 | (46 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_BATTLE_ROOM         (21 | (46 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_LOBBY             (22 | (46 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_CORRIDOR          (23 | (46 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_BATTLE_ROOM       (24 | (46 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_LOBBY            (25 | (46 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_FLOOR            (26 | (46 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_TOP              (27 | (46 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_LOBBY              (28 | (46 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_CORRIDOR           (29 | (46 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_BATTLE_ROOM        (30 | (46 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_LOBBY            (31 | (46 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_PRE_BATTLE_ROOM  (32 | (46 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_BATTLE_ROOM      (33 | (46 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_LOBBY               (34 | (46 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_CORRIDOR            (35 | (46 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_THREE_PATH_ROOM     (36 | (46 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_NORMAL         (37 | (46 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_FINAL          (38 | (46 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_WILD_MONS      (39 | (46 << 8))
#define MAP_BATTLE_FRONTIER_RANKING_HALL                    (40 | (46 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE1                         (41 | (46 << 8))
#define MAP_BATTLE_FRONTIER_EXCHANGE_SERVICE_CORNER         (42 | (46 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE2                         (43 | (46 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE3                         (44 | (46 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE4                         (45 | (46 << 8))
#define MAP_BATTLE_FRONTIER_SCOTTS_HOUSE                    (46 | (46 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE5                         (47 | (46 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE6                         (48 | (46 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE7                         (49 | (46 << 8))
#define MAP_BATTLE_FRONTIER_RECEPTION_GATE                  (50 | (46 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE8                         (51 | (46 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE9                         (52 | (46 << 8))
#define MAP_BATTLE_FRONTIER_POKEMON_CENTER_2F               (53 | (46 << 8))
#define MAP_BATTLE_FRONTIER_MART                            (54 | (46 << 8))
#define MAP_FARAWAY_ISLAND_ENTRANCE                         (55 | (46 << 8))
#define MAP_FARAWAY_ISLAND_INTERIOR                         (56 | (46 << 8))
#define MAP_BIRTH_ISLAND_EXTERIOR                           (57 | (46 << 8))
#define MAP_BIRTH_ISLAND_HARBOR                             (58 | (46 << 8))
#define MAP_TRAINER_HILL_ENTRANCE                           (59 | (46 << 8))
#define MAP_TRAINER_HILL_1F                                 (60 | (46 << 8))
#define MAP_TRAINER_HILL_2F                                 (61 | (46 << 8))
#define MAP_TRAINER_HILL_3F                                 (62 | (46 << 8))
#define MAP_TRAINER_HILL_4F                                 (63 | (46 << 8))
#define MAP_TRAINER_HILL_ROOF                               (64 | (46 << 8))
#define MAP_NAVEL_ROCK_EXTERIOR                             (65 | (46 << 8))
#define MAP_NAVEL_ROCK_HARBOR                               (66 | (46 << 8))
#define MAP_NAVEL_ROCK_ENTRANCE                             (67 | (46 << 8))
#define MAP_NAVEL_ROCK_B1F                                  (68 | (46 << 8))
#define MAP_NAVEL_ROCK_FORK                                 (69 | (46 << 8))
#define MAP_NAVEL_ROCK_UP1                                  (70 | (46 << 8))
#define MAP_NAVEL_ROCK_UP2                                  (71 | (46 << 8))
#define MAP_NAVEL_ROCK_UP3                                  (72 | (46 << 8))
#define MAP_NAVEL_ROCK_UP4                                  (73 | (46 << 8))
#define MAP_NAVEL_ROCK_TOP                                  (74 | (46 << 8))
#define MAP_NAVEL_ROCK_DOWN01                               (75 | (46 << 8))
#define MAP_NAVEL_ROCK_DOWN02                               (76 | (46 << 8))
#define MAP_NAVEL_ROCK_DOWN03                               (77 | (46 << 8))
#define MAP_NAVEL_ROCK_DOWN04                               (78 | (46 << 8))
#define MAP_NAVEL_ROCK_DOWN05                               (79 | (46 << 8))
#define MAP_NAVEL_ROCK_DOWN06                               (80 | (46 << 8))
#define MAP_NAVEL_ROCK_DOWN07                               (81 | (46 << 8))
#define MAP_NAVEL_ROCK_DOWN08                               (82 | (46 << 8))
#define MAP_NAVEL_ROCK_DOWN09                               (83 | (46 << 8))
#define MAP_NAVEL_ROCK_DOWN10                               (84 | (46 << 8))
#define MAP_NAVEL_ROCK_DOWN11                               (85 | (46 << 8))
#define MAP_NAVEL_ROCK_BOTTOM                               (86 | (46 << 8))
#define MAP_TRAINER_HILL_ELEVATOR                           (87 | (46 << 8))

// gMapGroup_IndoorRoute104Prototype
#define MAP_ROUTE104_PROTOTYPE                          (0 | (47 << 8))
#define MAP_ROUTE104_PROTOTYPE_PRETTY_PETAL_FLOWER_SHOP (1 | (47 << 8))

// gMapGroup_IndoorRoute109
#define MAP_ROUTE109_SEASHORE_HOUSE (0 | (48 << 8))

// gMapGroup_IndoorRoute110
#define MAP_ROUTE110_SEASIDE_CYCLING_ROAD_NORTH_ENTRANCE (0 | (49 << 8))
#define MAP_ROUTE110_SEASIDE_CYCLING_ROAD_SOUTH_ENTRANCE (1 | (49 << 8))

// gMapGroup_IndoorRoute113
#define MAP_ROUTE113_GLASS_WORKSHOP (0 | (50 << 8))

// gMapGroup_IndoorRoute123
#define MAP_ROUTE123_BERRY_MASTERS_HOUSE (0 | (51 << 8))

// gMapGroup_IndoorRoute119
#define MAP_ROUTE119_WEATHER_INSTITUTE_1F (0 | (52 << 8))
#define MAP_ROUTE119_WEATHER_INSTITUTE_2F (1 | (52 << 8))
#define MAP_ROUTE119_HOUSE                (2 | (52 << 8))

// gMapGroup_IndoorRoute124
#define MAP_ROUTE124_DIVING_TREASURE_HUNTERS_HOUSE (0 | (53 << 8))

#define MAP_GROUPS_COUNT 54

#endif // GUARD_CONSTANTS_MAP_GROUPS_H
