#ifndef GUARD_CONSTANTS_OPPONENTS_H
#define GUARD_CONSTANTS_OPPONENTS_H

#define TRAINER_NONE                          0
#define TRAINER_SAWYER_1                      1
#define TRAINER_P_MENDEL          2
#define TRAINER_GRUNT_AQUA_HIDEOUT_2          3
#define TRAINER_GRUNT_AQUA_HIDEOUT_3          4
#define TRAINER_GRUNT_AQUA_HIDEOUT_4          5
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_1       6
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_2       7
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_3       8
#define TRAINER_P_GRANGER                     9 //SKY PILLAR FIRST VISIT
#define TRAINER_P_RICKY                      10
#define TRAINER_P_JEANNIE                    11
#define TRAINER_P_SADFISHER_1                12 //PACIFIDLOG FIRST VISIT
#define TRAINER_P_SEAN                       13 //FLOTSHORE TRAIL
#define TRAINER_P_JANICE                     14
#define TRAINER_P_JIMMY                      15
#define TRAINER_P_DAN                        16
#define TRAINER_P_LAD                        17
#define TRAINER_P_SAMMIE                     18
#define TRAINER_P_BARBARA                    19
#define TRAINER_P_BEATRICE                   20 //BASALIN COAST
#define TRAINER_P_NANCY                      21
#define TRAINER_GRUNT_SPACE_CENTER_1         22 //Outlier
#define TRAINER_P_SADIE                      23
#define TRAINER_P_MELANIE                    24
#define TRAINER_P_TIMMY                      25
#define TRAINER_P_CAT                    26
#define TRAINER_P_YANNY                      27
#define TRAINER_P_REMY                       28
#define TRAINER_P_SELKO                      29
#define TRAINER_MATT                         30 //Outlier
#define TRAINER_P_ARTHUR                     31 //SOOTOPOLIS GYM
#define TRAINER_SHELLY_WEATHER_INSTITUTE     32 //Outlier
#define TRAINER_SHELLY_SEAFLOOR_CAVERN       33 //Outlier
#define TRAINER_ARCHIE                       34 //Outlier
#define TRAINER_P_LISA                       35
#define TRAINER_P_EMILY                      36
#define TRAINER_P_HASPAROTH                  37
#define TRAINER_P_MIIKACHAN                  38
#define TRAINER_P_JUAN                       39 //LEADERS 1
#define TRAINER_P_SEBASTIAN                  40 //LEADERS 1
#define TRAINER_P_DUNDEE                     41 //MANGROTTO TUNNEL
#define TRAINER_P_MOKA                       42
#define TRAINER_P_WOODS                      43
#define TRAINER_P_FAUNA                      44
#define TRAINER_P_DECLAN                     45
#define TRAINER_P_SHINJI                     46
#define TRAINER_P_SKEETER                    47
#define TRAINER_P_JAJA                       48
#define TRAINER_P_JANE                       49
#define TRAINER_P_JO_AND_JO                  50
#define TRAINER_GABBY_AND_TY_1               51 //OUTLIERS
#define TRAINER_GABBY_AND_TY_2               52 //
#define TRAINER_GABBY_AND_TY_3               53 //
#define TRAINER_GABBY_AND_TY_4               54 //
#define TRAINER_GABBY_AND_TY_5               55 //
#define TRAINER_GABBY_AND_TY_6               56 //
#define TRAINER_P_PANDOU_1                   57 //BREADWINNER 1
#define TRAINER_P_STELLA                     58 //COSMOSS BRIDGE
#define TRAINER_P_ISAAC                      59
#define TRAINER_P_RISE                       60
#define TRAINER_P_YU                         61
#define TRAINER_P_GEIGER                     62
#define TRAINER_P_YORK                       63
#define TRAINER_P_RIKA                       64
#define TRAINER_P_PETE                       65
#define TRAINER_P_MINKOWSKI                  66
#define TRAINER_P_RAY_1                      67 //RAY ENCOUNTER 1
#define TRAINER_P_PLANCK                     68 //MOSSDEEP GYM
#define TRAINER_P_LEGRI                      69
#define TRAINER_P_SPITZER                    70
#define TRAINER_P_TESS                       71
#define TRAINER_P_HITOMI                     72
#define TRAINER_P_LIZA                       73 //LEADER 2
#define TRAINER_P_S_STEVEN_1                 74 //STEVEN DOJO PANIC TUTORIAL
#define TRAINER_P_S_STEVEN_2                 75
#define TRAINER_P_S_STEVEN_3                 76
#define TRAINER_P_S_STEVEN_4                 77
#define TRAINER_P_S_STEVEN_5                 78
#define TRAINER_P_S_STEVEN_6                 79
#define TRAINER_P_POM_AND_ATIA               80 //HIDDEN MOSSDEEP CAVE
#define TRAINER_P_VAN                        81 //PRECIPIKE BLUFF
#define TRAINER_P_APRIL_AND_MAE              82
#define TRAINER_P_WREN                       83
#define TRAINER_P_RAINE                      84
#define TRAINER_P_SKYE                       85
#define TRAINER_P_GUUNTHER                   86
#define TRAINER_P_AVA                        87
#define TRAINER_P_JUNICHI                    88
#define TRAINER_P_NELLY                      89
#define TRAINER_P_SADFISHER_2                90
#define TRAINER_P_ARIEL                      91 //SUNBEACH STRAIT
#define TRAINER_P_DOLLY                      92
#define TRAINER_P_SINJIN                     93
#define TRAINER_P_JOSUKE                     94
#define TRAINER_P_TOBY                       95
#define TRAINER_P_ARBUCKLE                   96
#define TRAINER_P_NAOMI                      97
#define TRAINER_P_BETHA                      98
#define TRAINER_P_EBB                        99
#define TRAINER_P_FLO                       100
#define TRAINER_P_JULIO                     101
#define TRAINER_P_HOMER                     102
#define TRAINER_P_MARGE                     103
#define TRAINER_P_SHALA                     104 //PARASOL LADY GAUNTLET
#define TRAINER_P_LALA                      105
#define TRAINER_P_LA                        106
#define TRAINER_P_SHALALA                   107
#define TRAINER_P_INDA                      108
#define TRAINER_P_MORNING                   109
#define TRAINER_P_LANDON                    110 //OZONE LILYCOVE BRANCH
#define TRAINER_P_TERRA                     111
#define TRAINER_P_OZONE_SEAN                112
#define TRAINER_P_MARINA                    113
#define TRAINER_P_OZONE_MATT_1              114
#define TRAINER_P_OZONE_TABITHA_1           115
#define TRAINER_GRUNT_SPACE_CENTER_2        116
#define TRAINER_P_COLBY                     117 //SCUTTILL FIRST VISIT
#define TRAINER_P_NATALIE                   118
#define TRAINER_P_NICOLE                    119
#define TRAINER_P_RITA                      120
#define TRAINER_P_FELIX                     121 //THE COLD MINES
#define TRAINER_P_RAN                       122
#define TRAINER_P_BIG_HERTZ                 123
#define TRAINER_P_SUPERBOSS_MONK_1          124
#define TRAINER_P_BARNEY                    125 //ARCTAIGA ROAD
#define TRAINER_P_CHARON                    126
#define TRAINER_P_GARNET                    127
#define TRAINER_P_LAPIZ                     128
#define TRAINER_P_VERGIL                    129
#define TRAINER_P_YOSH                      130
#define TRAINER_P_KAIJI                     131
#define TRAINER_P_LARS                      132
#define TRAINER_P_DARCIE                    133
#define TRAINER_P_WYNTON                    134
#define TRAINER_P_PANDOU_2                  135 //BREADWINNER 2
#define TRAINER_P_RAMI                      136 //BRUMIST CLIFFS
#define TRAINER_P_TSUNAMI                   137
#define TRAINER_P_JINXIE                    138
#define TRAINER_P_CAROLINA                  139
#define TRAINER_P_BETTY                     140
#define TRAINER_P_HAZAKURA                  141
#define TRAINER_P_MIA                       142
#define TRAINER_P_MAYA                      143
#define TRAINER_P_KUMORI                    144
#define TRAINER_P_HOTH                      145
#define TRAINER_GRUNT_MT_CHIMNEY_1          146 //
#define TRAINER_P_PEARL                     147 // ZOTPYRE SHRINE
#define TRAINER_P_NEKO                      148
#define TRAINER_P_AYUMU                     149
#define TRAINER_P_DEACON                    150
#define TRAINER_P_ALODIA                    151
#define TRAINER_P_RAELIANA                  152
#define TRAINER_P_MORGAN                    153
#define TRAINER_P_MISTY                     154
#define TRAINER_P_REIMU                     155
#define TRAINER_P_MIKO                      156
#define TRAINER_P_RAY_2                     157 // RAY ENCOUNTER 2
#define TRAINER_P_JUNJI                     158 // ZOTPYRE GYM
#define TRAINER_P_KIRIE                     159
#define TRAINER_P_SHUICHI                   160
#define TRAINER_P_TOMIE                     161
#define TRAINER_P_AZAMI                     162
#define TRAINER_P_MISAKI                    163
#define TRAINER_P_YUINA                     164
#define TRAINER_P_PHOEBE                    165 //LEADERS 3
#define TRAINER_P_SPENSER                   166 //LEADERS 3
#define TRAINER_P_LAYTON                    167 //MANGROTTO TUNNEL (ADDED LATER)
#define TRAINER_P_KAT_AND_ANA                    168
#define TRAINER_P_THATCHER                     169
#define TRAINER_P_CHERIE                    170
#define TRAINER_P_FINN                       171
#define TRAINER_P_JUNIE                        172
#define TRAINER_P_KIWI                      173
#define TRAINER_P_JIM_BOB                        174
#define TRAINER_P_MADDY_AND_CROSS                      175
#define TRAINER_P_HECTOR                      176
#define TRAINER_P_PATRASCHE                      177
#define TRAINER_P_AMIRA                      178
#define TRAINER_P_LEILEI                       179
#define TRAINER_P_VESPA                     180
#define TRAINER_P_CRABRO                        181
#define TRAINER_P_JUSTIN                      182
#define TRAINER_P_JUONO                       183
#define TRAINER_P_WALLPRESS                       184
#define TRAINER_P_TAWNY                       185
#define TRAINER_P_JAIDEN                       186
#define TRAINER_P_GRISELDIS                       187
#define TRAINER_P_CAMERON                        188
#define TRAINER_P_FLAITINE                     189
#define TRAINER_P_JAMPER                     190
#define TRAINER_P_ENGLATERE                        191
#define TRAINER_P_KOIZUMI        192
#define TRAINER_P_CHARLI        193
#define TRAINER_P_SHAMOO                       194
#define TRAINER_P_MARISA                  195
#define TRAINER_P_GUNNESS                    196
#define TRAINER_P_JASON                    197
#define TRAINER_P_LEAH                    198
#define TRAINER_P_LELE                    199
#define TRAINER_P_PICKLE_LOU                    200
#define TRAINER_P_PANDOU_3                        201
#define TRAINER_P_KRIS                        202
#define TRAINER_P_SUSIE                        203
#define TRAINER_P_RALSEI                        204
#define TRAINER_P_FUJI                      205
#define TRAINER_P_DENALI                    206
#define TRAINER_P_RAINIER                    207
#define TRAINER_P_EVEREST                    208
#define TRAINER_P_LHOTSE                    209
#define TRAINER_P_GALE                    210
#define TRAINER_P_SMOKEY                        211
#define TRAINER_P_DESS_AND_EMBER                        212
#define TRAINER_P_SUNNY                       213
#define TRAINER_P_SUMMER                       214
#define TRAINER_P_NINO                      215
#define TRAINER_P_NINA                     216
#define TRAINER_P_CLO_AND_PHIL                      217
#define TRAINER_P_GABBY_AND_TY_1                      218
#define TRAINER_P_GABBY_AND_TY_2                     219
#define TRAINER_P_GABBY_AND_TY_3                     220
#define TRAINER_P_GABBY_AND_TY_4                     221
#define TRAINER_P_GABBY_AND_TY_5                     222
#define TRAINER_P_GABBY_AND_TY_6                       223
#define TRAINER_P_GABBY_AND_TY_7                      224
#define TRAINER_P_MICHAEL                      225
#define TRAINER_P_CHLOE                   226
#define TRAINER_P_BICHAEL                       227
#define TRAINER_P_FLOWERS                   228
#define TRAINER_P_JAY_AND_EM                   229
#define TRAINER_P_ASHE                   230
#define TRAINER_P_SARA                   231
#define TRAINER_P_TOGEDEMARU                      232
#define TRAINER_P_JUCIKA                     233
#define TRAINER_P_NARUTO                      234
#define TRAINER_P_KUSHINA                       235
#define TRAINER_P_CALLUM                     236
#define TRAINER_P_KUSUO                      237
#define TRAINER_P_MIRAI                   238
#define TRAINER_P_KURENAI                   239
#define TRAINER_P_SAKURAI                   240
#define TRAINER_P_LARA                   241
#define TRAINER_P_ERICA                   242
#define TRAINER_P_JIN                      243
#define TRAINER_P_AKI_AND_MITSU                      244
#define TRAINER_P_DAISY                    245
#define TRAINER_P_GWUNIVERE                       246
#define TRAINER_P_YISAN                       247
#define TRAINER_P_HAMM                      248
#define TRAINER_P_FRANK                     249
#define TRAINER_P_WEINER                     250
#define TRAINER_P_EVELYNN                     251
#define TRAINER_P_DYNA                     252
#define TRAINER_P_AUDREY                     253
#define TRAINER_P_AUDREY_II                    254
#define TRAINER_P_EMMY                       255
#define TRAINER_P_DAYTON                      256
#define TRAINER_P_LIBRA                    257
#define TRAINER_P_BAZE                    258
#define TRAINER_P_CHINZAO                    259
#define TRAINER_P_MARIMAR                    260
#define TRAINER_DO_NOT_TOUCHIE                      261
#define TRAINER_PHOEBE                      262
#define TRAINER_GLACIA                      263
#define TRAINER_DRAKE                       264
#define TRAINER_ROXANNE_1                   265
#define TRAINER_BRAWLY_1                    266
#define TRAINER_WATTSON_1                   267
#define TRAINER_FLANNERY_1                  268
#define TRAINER_NORMAN_1                    269
#define TRAINER_WINONA_1                    270
#define TRAINER_TATE_AND_LIZA_1             271
#define TRAINER_JUAN_1                      272
#define TRAINER_P_JELLY                     273
#define TRAINER_P_KRAY                         274
#define TRAINER_P_ZII                        275
#define TRAINER_P_IVAN                     276
#define TRAINER_P_LIBYA                     277
#define TRAINER_P_CARVILLE                     278
#define TRAINER_P_BOOM                     279
#define TRAINER_P_IWAN                     280
#define TRAINER_P_CASS                     281
#define TRAINER_P_SANDY                     282
#define TRAINER_P_JAN                     283
#define TRAINER_P_CATT                     284
#define TRAINER_P_CELIA                     285
#define TRAINER_P_REDACTED                286
#define TRAINER_P_DIMITRI              287
#define TRAINER_P_CLIFF_AND_ISSA              288
#define TRAINER_P_GERODE              289
#define TRAINER_P_MEZRA              290
#define TRAINER_P_LANE              291
#define TRAINER_P_BONNIE                      292
#define TRAINER_P_HEDON                    293
#define TRAINER_P_MONICA                      294
#define TRAINER_P_GHIDORAH                    295
#define TRAINER_P_GOJIRA                    296
#define TRAINER_P_GAMERA                    297
#define TRAINER_P_SANTO                    298
#define TRAINER_P_DOROTHY                    299
#define TRAINER_P_ERIN                     300
#define TRAINER_P_AARON                     301
#define TRAINER_P_THAD                    302
#define TRAINER_P_LEELA                    303
#define TRAINER_P_ICKLE                    304
#define TRAINER_P_STAPH                    305
#define TRAINER_P_HWARANG                    306
#define TRAINER_P_TAKESHI                   307
#define TRAINER_P_BEAT                   308
#define TRAINER_P_DOTTY                   309
#define TRAINER_P_RELI                   310
#define TRAINER_P_CASTLE                   311
#define TRAINER_P_KATRINA                       312
#define TRAINER_P_CY                    313
#define TRAINER_P_GERTRUDE                    314
#define TRAINER_P_TOOTSIE                    315
#define TRAINER_P_WENDY_AND_GALE                    316
#define TRAINER_P_KAKU                    317
#define TRAINER_P_KURT                    318
#define TRAINER_P_KIRST                       319
#define TRAINER_P_ROY                        320
#define TRAINER_P_MAIA                       321
#define TRAINER_P_MIGUEL                        322
#define TRAINER_P_MCKAYLEIGH                         323
#define TRAINER_P_AIDEN                      324
#define TRAINER_P_DUSTIN                    325
#define TRAINER_P_HAYLEY                      326
#define TRAINER_P_ENA_AND_MINA                      327
#define TRAINER_P_DILL                    328
#define TRAINER_P_DELILAH                    329
#define TRAINER_P_JIYU_AND_SHIROU                    330
#define TRAINER_P_SAMUEL                    331
#define TRAINER_P_YERBA_AND_BUENA                       332
#define TRAINER_P_LEX_AND_TRISH                       333
#define TRAINER_P_DAVID                       334
#define TRAINER_WALLACE                     335
#define TRAINER_P_PANDOU_4                      336
#define TRAINER_P_ANTON                        337
#define TRAINER_P_GEIRU                      338
#define TRAINER_P_ADAM_AND_STEVE                    339
#define TRAINER_P_COTTON                         340
#define TRAINER_P_BILLY_BOB                        341
#define TRAINER_P_RHODE                       342
#define TRAINER_P_CRUZ                       343
#define TRAINER_P_MONA                        344
#define TRAINER_P_SOLO                      345
#define TRAINER_P_HICHAEL                    346
#define TRAINER_P_PENNY                    347
#define TRAINER_P_JUNIOR                    348
#define TRAINER_P_HICHAELSON                    349
#define TRAINER_P_LULU                      350
#define TRAINER_P_KAIRA                       351
#define TRAINER_P_WOODY                     352
#define TRAINER_P_ANA                  353
#define TRAINER_P_YOKO                  354
#define TRAINER_P_FLATS                  355
#define TRAINER_P_PHILLIP                  356
#define TRAINER_P_NUE                  357
#define TRAINER_P_GARY                   358
#define TRAINER_P_MOON                     359
#define TRAINER_P_VENUS                   360
#define TRAINER_P_FIGLIOSI                   361
#define TRAINER_P_OLLY                   362
#define TRAINER_P_POLLY                   363
#define TRAINER_P_EDWARD                     364
#define TRAINER_P_YANCY                     365
#define TRAINER_P_ERNEST                     366
#define TRAINER_P_LATTY                     367
#define TRAINER_P_ALICE                     368
#define TRAINER_P_ANON                     369
#define TRAINER_P_ROBIN                     370
#define TRAINER_P_CHARITY                     371
#define TRAINER_P_SIN                     372
#define TRAINER_P_BOB                     373
#define TRAINER_P_SAM                      374
#define TRAINER_P_VEGETABLE                   375
#define TRAINER_P_ALEXA                    376
#define TRAINER_P_BIXBY                     377
#define TRAINER_P_RUBY                       378
#define TRAINER_P_PASCAL                    379
#define TRAINER_P_BONZI                    380
#define TRAINER_P_JELLO                    381
#define TRAINER_P_LEN                    382
#define TRAINER_P_RIN                      383
#define TRAINER_P_ROSE_AND_THORN                       384
#define TRAINER_P_TEX                       385
#define TRAINER_P_DAWN                   386
#define TRAINER_P_LOUISE                     387
#define TRAINER_P_PRAG                   388
#define TRAINER_P_MARK                   389
#define TRAINER_P_SACRED                   390
#define TRAINER_P_MANDALORE                   391
#define TRAINER_P_BEAST                   392
#define TRAINER_P_KAISENAT                   393
#define TRAINER_P_CHAD                   394
#define TRAINER_P_CHAZ                   395
#define TRAINER_P_BRODY                   396
#define TRAINER_P_DELA                       397
#define TRAINER_P_KIERA                       398
#define TRAINER_P_ANTO                        399
#define TRAINER_P_MARY                        400
#define TRAINER_P_JOSE                       401
#define TRAINER_P_DARIA                    402
#define TRAINER_P_JEAN                     403
#define TRAINER_P_LYNN                     404
#define TRAINER_P_AIOFE                       405
#define TRAINER_P_DICK_AND_JANE                    406
#define TRAINER_P_ROSIE_AND_PALMS                       407
#define TRAINER_P_MAOMAO                     408
#define TRAINER_P_BARNABY                    409
#define TRAINER_P_VALERIE                    410
#define TRAINER_P_QUEEQUEG                    411
#define TRAINER_P_JESS                    412
#define TRAINER_P_AMI                        413
#define TRAINER_P_MARCY                        414
#define TRAINER_P_SPONGE                        415
#define TRAINER_P_WALTON                     416
#define TRAINER_P_JOSHU                      417
#define TRAINER_P_JANELLE                        418
#define TRAINER_P_NUNYA                       419
#define TRAINER_P_JACK                        420
#define TRAINER_P_ROSE                       421
#define TRAINER_P_SANDEEP                       422
#define TRAINER_P_JOAN                       423
#define TRAINER_P_LUDI                       424
#define TRAINER_P_SOLAIRE                     425
#define TRAINER_P_LUNA                       426
#define TRAINER_P_MAGNUS                     427
#define TRAINER_P_WU                        428
#define TRAINER_P_TANG                       429
#define TRAINER_P_JUNEAU                     430
#define TRAINER_P_ALASKA                     431
#define TRAINER_P_TAHOE                     432
#define TRAINER_P_HURON                     433
#define TRAINER_P_EYRE                  434
#define TRAINER_P_CASPIAN                    435
#define TRAINER_P_VICTORIA                    436
#define TRAINER_P_ALBERT                  437
#define TRAINER_P_MARCEL                  438
#define TRAINER_P_NESSIE                  439
#define TRAINER_P_DAPHNE                  440
#define TRAINER_P_VELMA                     441
#define TRAINER_P_FRED                       442
#define TRAINER_P_SCOOB                        443
#define TRAINER_P_SHAGGY                      444
#define TRAINER_P_HOWLEE                        445
#define TRAINER_P_MOWGLI                        446
#define TRAINER_P_MEENAH                       447
#define TRAINER_P_FEFERI                       448
#define TRAINER_P_MIMI                     449
#define TRAINER_P_SEAMUS                       450
#define TRAINER_P_LAURA                       451
#define TRAINER_P_LAHARL                      452
#define TRAINER_P_ETNA                       453
#define TRAINER_BRENDA                      454
#define TRAINER_P_FLONNE                       455
#define TRAINER_P_YASUKE                       456
#define TRAINER_P_GATHERER                        457
#define TRAINER_P_YUE                        458
#define TRAINER_P_PRINCE                      459
#define TRAINER_P_KING                       460
#define TRAINER_P_SAI_AND_MISHA                       461
#define TRAINER_P_JOSHUONE                      462
#define TRAINER_P_ASTOLFO                      463
#define TRAINER_P_JIGGLES                      464
#define TRAINER_P_DAHLIA                     465
#define TRAINER_P_ROBERTS                     466
#define TRAINER_P_BUTTERCUP                     467
#define TRAINER_P_JUNE                     468
#define TRAINER_P_AUGUST                       469
#define TRAINER_P_GWUNNETTE                       470
#define TRAINER_P_CODY                       471
#define TRAINER_P_MILDRED                       472
#define TRAINER_P_MICHIKO                      473
#define TRAINER_P_GREY                     474
#define TRAINER_P_XERXES                      475
#define TRAINER_P_YVETTE                       476
#define TRAINER_P_PI_AND_SEES                     477
#define TRAINER_P_KU_AND_MORI                     478
#define TRAINER_P_PERSEPHONE                     479
#define TRAINER_P_XAVIER                     480
#define TRAINER_P_NAFI               481
#define TRAINER_P_MADELINE               482
#define TRAINER_P_ENRIQUE              483
#define TRAINER_P_MARIA                484
#define TRAINER_P_FERN               485
#define TRAINER_P_DUDLEY              486
#define TRAINER_P_GUSTAVO               487
#define TRAINER_P_NEIL               488
#define TRAINER_P_BRITNEY               489
#define TRAINER_P_CORA                        490
#define TRAINER_P_MEL                      491
#define TRAINER_P_LINE                    492
#define TRAINER_P_HOOK                      493
#define TRAINER_P_YUKARI                     494
#define TRAINER_P_MAKOTO                     495
#define TRAINER_P_INIGO                      496
#define TRAINER_P_FEZZIK                    497
#define TRAINER_P_JEAN_AND_JACKITT                    498
#define TRAINER_P_LUNA_AND_STAR                    499
#define TRAINER_P_LANCE                    500
#define TRAINER_P_MICYCLE                         501
#define TRAINER_P_SKIPPER                      502
#define TRAINER_P_TWOFFANY                      503
#define TRAINER_P_OLIVIER                       504
#define TRAINER_P_TIKTAALIK                      505
#define TRAINER_P_PATRICK                       506
#define TRAINER_P_GUNTILDA                      507
#define TRAINER_P_LAIOS                      508
#define TRAINER_P_GIO                       509
#define TRAINER_P_EUNMI                      510
#define TRAINER_P_THYME                       511
#define TRAINER_P_BASIL                     512
#define TRAINER_P_COHEED                      513
#define TRAINER_TABITHA_MOSSDEEP            514
#define TRAINER_P_CAMBRIA                     515
#define TRAINER_P_SERLING                     516
#define TRAINER_P_MARIANA                     517
#define TRAINER_P_CORAL                     518
#define TRAINER_WALLY_VR_1                  519
#define TRAINER_BRENDAN_ROUTE_103_MUDKIP    520
#define TRAINER_BRENDAN_ROUTE_110_MUDKIP    521
#define TRAINER_BRENDAN_ROUTE_119_MUDKIP    522
#define TRAINER_BRENDAN_ROUTE_103_TREECKO   523
#define TRAINER_BRENDAN_ROUTE_110_TREECKO   524
#define TRAINER_BRENDAN_ROUTE_119_TREECKO   525
#define TRAINER_BRENDAN_ROUTE_103_TORCHIC   526
#define TRAINER_BRENDAN_ROUTE_110_TORCHIC   527
#define TRAINER_BRENDAN_ROUTE_119_TORCHIC   528
#define TRAINER_MAY_ROUTE_103_MUDKIP        529
#define TRAINER_MAY_ROUTE_110_MUDKIP        530
#define TRAINER_MAY_ROUTE_119_MUDKIP        531
#define TRAINER_MAY_ROUTE_103_TREECKO       532
#define TRAINER_MAY_ROUTE_110_TREECKO       533
#define TRAINER_MAY_ROUTE_119_TREECKO       534
#define TRAINER_MAY_ROUTE_103_TORCHIC       535
#define TRAINER_MAY_ROUTE_110_TORCHIC       536
#define TRAINER_MAY_ROUTE_119_TORCHIC       537
#define TRAINER_P_GUS                     538
#define TRAINER_P_LIL_FAX                       539
#define TRAINER_P_HER_CHILD                    540
#define TRAINER_P_JEAN_PAUL                     541
#define TRAINER_P_SIMONE                     542
#define TRAINER_P_PLATO_AND_ARIS                     543
#define TRAINER_P_DIOGENES                     544
#define TRAINER_P_GOOMBELLA                     545
#define TRAINER_P_TIMPANI                       546
#define TRAINER_P_MARX                    547
#define TRAINER_P_QIU                     548
#define TRAINER_P_TUTU                     549
#define TRAINER_P_DUCK                     550
#define TRAINER_P_VIOLET                     551
#define TRAINER_P_ELIZABETH                   552
#define TRAINER_P_ARTIE                     553
#define TRAINER_P_GYOMARU                   554
#define TRAINER_P_SUZUME                   555
#define TRAINER_P_MIO                   556
#define TRAINER_P_LEMMY                   557
#define TRAINER_P_ICHI                   558
#define TRAINER_P_INU_AND_PERSIA                 559
#define TRAINER_P_NATASHA                       560
#define TRAINER_P_JOEY                      561
#define TRAINER_P_JOSEPHINE                 562
#define TRAINER_P_LENNY                 563
#define TRAINER_P_BRIDGET                 564
#define TRAINER_P_DARWIN                 565
#define TRAINER_P_GUMBALL                       566
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_5     567
#define TRAINER_GRUNT_UNUSED                568
#define TRAINER_GRUNT_MT_PYRE_4             569
#define TRAINER_GRUNT_JAGGED_PASS           570
#define TRAINER_P_JIMMY_2                        571
#define TRAINER_P_TIMMY_2                     572
#define TRAINER_P_JOE                      573
#define TRAINER_P_SASHA                    574
#define TRAINER_P_ELLE                      575
#define TRAINER_P_TAY                    576
#define TRAINER_P_ETHAN_AND_KAI                      577
#define TRAINER_P_GUNFRIED                    578
#define TRAINER_GRUNT_MT_CHIMNEY_2          579
#define TRAINER_P_REX                    580
#define TRAINER_P_GUINDA                       581
#define TRAINER_P_GUNDER                        582
#define TRAINER_P_GUNHILD                    583
#define TRAINER_P_ELON                    584
#define TRAINER_P_LILITH                    585
#define TRAINER_GRUNT_SPACE_CENTER_3        586
#define TRAINER_GRUNT_SPACE_CENTER_4        587
#define TRAINER_GRUNT_SPACE_CENTER_5        588
#define TRAINER_GRUNT_SPACE_CENTER_6        589
#define TRAINER_GRUNT_SPACE_CENTER_7        590
#define TRAINER_P_SOD_AND_SANDY                       591
#define TRAINER_BRENDAN_RUSTBORO_TREECKO    592
#define TRAINER_BRENDAN_RUSTBORO_MUDKIP     593
#define TRAINER_P_PENDRAGON                      594
#define TRAINER_P_AKAGI                    595
#define TRAINER_GRUNT_WEATHER_INST_5        596
#define TRAINER_TABITHA_MT_CHIMNEY          597
#define TRAINER_P_LINCOLN                    598
#define TRAINER_BRENDAN_RUSTBORO_TORCHIC    599
#define TRAINER_MAY_RUSTBORO_MUDKIP         600
#define TRAINER_MAXIE_MAGMA_HIDEOUT         601
#define TRAINER_MAXIE_MT_CHIMNEY            602
#define TRAINER_P_MONEYWELL                       603
#define TRAINER_P_DANTE                     604
#define TRAINER_P_SHINJIRO                      605
#define TRAINER_P_PENN                        606
#define TRAINER_P_ARI                     607
#define TRAINER_P_SKYLER                     608
#define TRAINER_P_WALTER                     609
#define TRAINER_P_KNUCKLES                     610
#define TRAINER_P_FINGERS                       611
#define TRAINER_P_RYE                       612
#define TRAINER_P_INGRID                      613
#define TRAINER_P_BLAISE_AND_MAR                      614
#define TRAINER_RICK                        615
#define TRAINER_P_MEIYU                        616
#define TRAINER_P_CENTAURI                        617
#define TRAINER_P_CATT_2                        618
#define TRAINER_P_TAII                        619
#define TRAINER_P_ERKIN_AND_KAYA                        620
#define TRAINER_P_GRISELDA                     621
#define TRAINER_P_MORGANA                     622
#define TRAINER_P_ZEPHYR                     623
#define TRAINER_P_ANTHREENY                     624
#define TRAINER_P_SCHULI                     625
#define TRAINER_P_GERIER                       626
#define TRAINER_P_GONZEROS                     627
#define TRAINER_P_TOPAZ_1                       628
#define TRAINER_P_TOPAZ_2                     629
#define TRAINER_P_UNSELD                        630
#define TRAINER_P_IMMY                       631
#define TRAINER_P_MELULU                        632
#define TRAINER_P_PYORIN                     633
#define TRAINER_P_MIN                      634
#define TRAINER_P_MAX                      635
#define TRAINER_P_TOPAZ_3                     636
#define TRAINER_P_FINAL_MONK                     637
#define TRAINER_P_GARENA                     638
#define TRAINER_P_GORO                     639
#define TRAINER_P_MIERNIE                640
#define TRAINER_P_BADUMKA                 641
#define TRAINER_P_TOPAZ_4              642
#define TRAINER_P_TOPAZ_5              643
#define TRAINER_P_TOPAZ_6              644
#define TRAINER_P_TOPAZ_7              645
#define TRAINER_P_TOPAZ_8              646
#define TRAINER_P_TOPAZ_9                     647
#define TRAINER_P_TOPAZ_10                      648
#define TRAINER_P_KUMQOT                      649
#define TRAINER_P_DORIAN                    650
#define TRAINER_P_LYTXI                       651
#define TRAINER_P_SHERIMOYA                       652
#define TRAINER_P_PANDOU_6                       653
#define TRAINER_P_PANDOU_5                       654
#define TRAINER_P_PETER                      655
#define TRAINER_WALLY_MAUVILLE              656
#define TRAINER_WALLY_VR_2                  657
#define TRAINER_WALLY_VR_3                  658
#define TRAINER_WALLY_VR_4                  659
#define TRAINER_WALLY_VR_5                  660
#define TRAINER_BRENDAN_LILYCOVE_MUDKIP     661
#define TRAINER_BRENDAN_LILYCOVE_TREECKO    662
#define TRAINER_BRENDAN_LILYCOVE_TORCHIC    663
#define TRAINER_MAY_LILYCOVE_MUDKIP         664
#define TRAINER_MAY_LILYCOVE_TREECKO        665
#define TRAINER_MAY_LILYCOVE_TORCHIC        666
#define TRAINER_P_WINONA                       667
#define TRAINER_P_AARUNE                       668
#define TRAINER_P_TABITHA_2                       669
#define TRAINER_P_FLANNERY                       670
#define TRAINER_P_MR_MOORE                       671
#define TRAINER_P_MATT_2                      672
#define TRAINER_P_MR_BONDING                       673
#define TRAINER_P_WATTSON                       674
#define TRAINER_P_SCOTT                        675
#define TRAINER_P_BRAWLY                       676
#define TRAINER_P_SHELLY_1                677
#define TRAINER_P_ROXANNE                678
#define TRAINER_P_LANNETTE                679
#define TRAINER_P_NORMAN                680
#define TRAINER_P_SIDNEY              681
#define TRAINER_P_LUCY              682
#define TRAINER_P_WALLY              683
#define TRAINER_P_RAY_3              684
#define TRAINER_P_RAY_4              685
#define TRAINER_P_RAY_5                686
#define TRAINER_P_RAY_6              687
#define TRAINER_P_RAY_7              688
#define TRAINER_P_TABITHA_3              689
#define TRAINER_P_MATT_3              690
#define TRAINER_P_COURTNEY_1              691
#define TRAINER_P_COURTNEY_2                692
#define TRAINER_P_SHELLY_2                       693
#define TRAINER_P_MAXIE                      694
#define TRAINER_P_ARCHIE                       695
#define TRAINER_P_WALLACE                      696
#define TRAINER_P_STEVEN                      697
#define TRAINER_P_BRENDAN_FINAL                    698
#define TRAINER_P_MAY_FINAL                       699
#define TRAINER_P_CENTAURIPH                      700
#define TRAINER_ALYSSA                      701
#define TRAINER_P_JIMMYOS                      702
#define TRAINER_RHETT                       703
#define TRAINER_TYRON                       704
#define TRAINER_CELINA                      705
#define TRAINER_BIANCA                      706
#define TRAINER_HAYDEN                      707
#define TRAINER_SOPHIE                      708
#define TRAINER_COBY                        709
#define TRAINER_LAWRENCE                    710
#define TRAINER_WYATT                       711
#define TRAINER_ANGELINA                    712
#define TRAINER_KAI                         713
#define TRAINER_CHARLOTTE                   714
#define TRAINER_DEANDRE                     715
#define TRAINER_GRUNT_MAGMA_HIDEOUT_1       716
#define TRAINER_GRUNT_MAGMA_HIDEOUT_2       717
#define TRAINER_GRUNT_MAGMA_HIDEOUT_3       718
#define TRAINER_GRUNT_MAGMA_HIDEOUT_4       719
#define TRAINER_GRUNT_MAGMA_HIDEOUT_5       720
#define TRAINER_GRUNT_MAGMA_HIDEOUT_6       721
#define TRAINER_GRUNT_MAGMA_HIDEOUT_7       722
#define TRAINER_GRUNT_MAGMA_HIDEOUT_8       723
#define TRAINER_GRUNT_MAGMA_HIDEOUT_9       724
#define TRAINER_GRUNT_MAGMA_HIDEOUT_10      725
#define TRAINER_GRUNT_MAGMA_HIDEOUT_11      726
#define TRAINER_GRUNT_MAGMA_HIDEOUT_12      727
#define TRAINER_GRUNT_MAGMA_HIDEOUT_13      728
#define TRAINER_GRUNT_MAGMA_HIDEOUT_14      729
#define TRAINER_GRUNT_MAGMA_HIDEOUT_15      730
#define TRAINER_GRUNT_MAGMA_HIDEOUT_16      731
#define TRAINER_TABITHA_MAGMA_HIDEOUT       732
#define TRAINER_DARCY                       733
#define TRAINER_MAXIE_MOSSDEEP              734
#define TRAINER_PETE                        735
#define TRAINER_ISABELLE                    736
#define TRAINER_ANDRES_1                    737
#define TRAINER_JOSUE                       738
#define TRAINER_CAMRON                      739
#define TRAINER_CORY_1                      740
#define TRAINER_P_CODYINA                    741
#define TRAINER_P_MICYCLEJAH                      742
#define TRAINER_CELIA                       743
#define TRAINER_BRYAN                       744
#define TRAINER_BRANDEN                     745
#define TRAINER_BRYANT                      746
#define TRAINER_SHAYLA                      747
#define TRAINER_KYRA                        748
#define TRAINER_JAIDEN                      749
#define TRAINER_ALIX                        750
#define TRAINER_HELENE                      751
#define TRAINER_MARLENE                     752
#define TRAINER_DEVAN                       753
#define TRAINER_JOHNSON                     754
#define TRAINER_MELINA                      755
#define TRAINER_BRANDI                      756
#define TRAINER_AISHA                       757
#define TRAINER_MAKAYLA                     758
#define TRAINER_FABIAN                      759
#define TRAINER_DAYTON                      760
#define TRAINER_RACHEL                      761
#define TRAINER_LEONEL                      762
#define TRAINER_CALLIE                      763
#define TRAINER_CALE                        764
#define TRAINER_MYLES                       765
#define TRAINER_PAT                         766
#define TRAINER_CRISTIN_1                   767
#define TRAINER_MAY_RUSTBORO_TREECKO        768
#define TRAINER_MAY_RUSTBORO_TORCHIC        769
#define TRAINER_ROXANNE_2                   770
#define TRAINER_ROXANNE_3                   771
#define TRAINER_ROXANNE_4                   772
#define TRAINER_ROXANNE_5                   773
#define TRAINER_BRAWLY_2                    774
#define TRAINER_BRAWLY_3                    775
#define TRAINER_BRAWLY_4                    776
#define TRAINER_BRAWLY_5                    777
#define TRAINER_WATTSON_2                   778
#define TRAINER_WATTSON_3                   779
#define TRAINER_WATTSON_4                   780
#define TRAINER_WATTSON_5                   781
#define TRAINER_FLANNERY_2                  782
#define TRAINER_FLANNERY_3                  783
#define TRAINER_FLANNERY_4                  784
#define TRAINER_FLANNERY_5                  785
#define TRAINER_NORMAN_2                    786
#define TRAINER_NORMAN_3                    787
#define TRAINER_NORMAN_4                    788
#define TRAINER_NORMAN_5                    789
#define TRAINER_WINONA_2                    790
#define TRAINER_WINONA_3                    791
#define TRAINER_WINONA_4                    792
#define TRAINER_WINONA_5                    793
#define TRAINER_TATE_AND_LIZA_2             794
#define TRAINER_TATE_AND_LIZA_3             795
#define TRAINER_TATE_AND_LIZA_4             796
#define TRAINER_TATE_AND_LIZA_5             797
#define TRAINER_JUAN_2                      798
#define TRAINER_JUAN_3                      799
#define TRAINER_JUAN_4                      800
#define TRAINER_JUAN_5                      801
#define TRAINER_ANGELO                      802
#define TRAINER_DARIUS                      803
#define TRAINER_STEVEN                      804
#define TRAINER_ANABEL                      805
#define TRAINER_TUCKER                      806
#define TRAINER_SPENSER                     807
#define TRAINER_GRETA                       808
#define TRAINER_P_RHODED                      809
#define TRAINER_LUCY                        810
#define TRAINER_BRANDON                     811
#define TRAINER_ANDRES_2                    812
#define TRAINER_ANDRES_3                    813
#define TRAINER_ANDRES_4                    814
#define TRAINER_ANDRES_5                    815
#define TRAINER_CORY_2                      816
#define TRAINER_CORY_3                      817
#define TRAINER_CORY_4                      818
#define TRAINER_CORY_5                      819
#define TRAINER_PABLO_2                     820
#define TRAINER_PABLO_3                     821
#define TRAINER_PABLO_4                     822
#define TRAINER_PABLO_5                     823
#define TRAINER_KOJI_2                      824
#define TRAINER_KOJI_3                      825
#define TRAINER_KOJI_4                      826
#define TRAINER_KOJI_5                      827
#define TRAINER_CRISTIN_2                   828
#define TRAINER_CRISTIN_3                   829
#define TRAINER_CRISTIN_4                   830
#define TRAINER_CRISTIN_5                   831
#define TRAINER_FERNANDO_2                  832
#define TRAINER_FERNANDO_3                  833
#define TRAINER_FERNANDO_4                  834
#define TRAINER_FERNANDO_5                  835
#define TRAINER_SAWYER_2                    836
#define TRAINER_SAWYER_3                    837
#define TRAINER_SAWYER_4                    838
#define TRAINER_SAWYER_5                    839
#define TRAINER_GABRIELLE_2                 840
#define TRAINER_GABRIELLE_3                 841
#define TRAINER_GABRIELLE_4                 842
#define TRAINER_GABRIELLE_5                 843
#define TRAINER_THALIA_2                    844
#define TRAINER_THALIA_3                    845
#define TRAINER_THALIA_4                    846
#define TRAINER_THALIA_5                    847
#define TRAINER_MARIELA                     848
#define TRAINER_ALVARO                      849
#define TRAINER_EVERETT                     850
#define TRAINER_RED                         851
#define TRAINER_LEAF                        852
#define TRAINER_BRENDAN_PLACEHOLDER         853
#define TRAINER_MAY_PLACEHOLDER             854

// NOTE: Because each Trainer uses a flag to determine when they are defeated, there is only space for 9 additional trainers before trainer flag space overflows
//       More space can be made by shifting flags around in constants/flags.h or changing how trainer flags are handled
//       MAX_TRAINERS_COUNT can be increased but will take up additional saveblock space

#define TRAINERS_COUNT                      855
#define MAX_TRAINERS_COUNT                  864

#endif  // GUARD_CONSTANTS_OPPONENTS_H
