#ifndef GUARD_CONSTANTS_POKEDEX_H
#define GUARD_CONSTANTS_POKEDEX_H

// National Pokedex order.
// These constants are NOT disabled by P_GEN_X_POKEMON to keep pokedex_orders.h clean.
enum {
    NATIONAL_DEX_NONE,
    // Kanto
    NATIONAL_DEX_BULBASAUR,
    NATIONAL_DEX_IVYSAUR,
    NATIONAL_DEX_VENUSAUR,
    NATIONAL_DEX_CHARMANDER,
    NATIONAL_DEX_CHARMELEON,
    NATIONAL_DEX_CHARIZARD,
    NATIONAL_DEX_SQUIRTLE,
    NATIONAL_DEX_WARTORTLE,
    NATIONAL_DEX_BLASTOISE,    
    NATIONAL_DEX_RATTATA,
    NATIONAL_DEX_RATICATE,
   
    NATIONAL_DEX_PIKACHU,
    NATIONAL_DEX_RAICHU,
    NATIONAL_DEX_SANDSHREW,
    NATIONAL_DEX_SANDSLASH,
    
    NATIONAL_DEX_VULPIX,
    NATIONAL_DEX_NINETALES,
    
    NATIONAL_DEX_DIGLETT,
    NATIONAL_DEX_DUGTRIO,
    NATIONAL_DEX_MEOWTH,
    NATIONAL_DEX_PERSIAN,
   
    NATIONAL_DEX_GEODUDE,
    NATIONAL_DEX_GRAVELER,
    NATIONAL_DEX_GOLEM,
    NATIONAL_DEX_PONYTA,
    NATIONAL_DEX_RAPIDASH,
    NATIONAL_DEX_SLOWPOKE,
    NATIONAL_DEX_SLOWBRO,
   
    NATIONAL_DEX_FARFETCHD,
    
    NATIONAL_DEX_GRIMER,
    NATIONAL_DEX_MUK,
    
    NATIONAL_DEX_MR_MIME,
    
    NATIONAL_DEX_DITTO,
    
    NATIONAL_DEX_ARTICUNO,
    NATIONAL_DEX_ZAPDOS,
    NATIONAL_DEX_MOLTRES,

    NATIONAL_DEX_MEWTWO,
    NATIONAL_DEX_MEW,
    // Johto
    
    NATIONAL_DEX_SHUCKLE,
    
    NATIONAL_DEX_RAIKOU,
    NATIONAL_DEX_ENTEI,
    NATIONAL_DEX_SUICUNE,

    NATIONAL_DEX_LUGIA,
    NATIONAL_DEX_HO_OH,
    NATIONAL_DEX_CELEBI,
    // Hoenn
    NATIONAL_DEX_TREECKO,
    NATIONAL_DEX_GROVYLE,
    NATIONAL_DEX_SCEPTILE,
    NATIONAL_DEX_TORCHIC,
    NATIONAL_DEX_COMBUSKEN,
    NATIONAL_DEX_BLAZIKEN,
    NATIONAL_DEX_MUDKIP,
    NATIONAL_DEX_MARSHTOMP,
    NATIONAL_DEX_SWAMPERT,
    
    NATIONAL_DEX_NINCADA,
    NATIONAL_DEX_NINJASK,
    NATIONAL_DEX_SHEDINJA,
    
    NATIONAL_DEX_REGIROCK,
    NATIONAL_DEX_REGICE,
    NATIONAL_DEX_REGISTEEL,
    NATIONAL_DEX_LATIAS,
    NATIONAL_DEX_LATIOS,
    NATIONAL_DEX_KYOGRE,
    NATIONAL_DEX_GROUDON,
    NATIONAL_DEX_RAYQUAZA,
    NATIONAL_DEX_JIRACHI,
    NATIONAL_DEX_DEOXYS,
    // Sinnoh
    NATIONAL_DEX_CHERUBI,
    NATIONAL_DEX_CHERRIM,
    NATIONAL_DEX_SHELLOS,
    NATIONAL_DEX_GASTRODON,
    
    NATIONAL_DEX_ROTOM,
    NATIONAL_DEX_UXIE,
    NATIONAL_DEX_MESPRIT,
    NATIONAL_DEX_AZELF,
    NATIONAL_DEX_DIALGA,
    NATIONAL_DEX_PALKIA,
    NATIONAL_DEX_HEATRAN,
    NATIONAL_DEX_REGIGIGAS,
    NATIONAL_DEX_GIRATINA,
    NATIONAL_DEX_CRESSELIA,
    NATIONAL_DEX_PHIONE,
    NATIONAL_DEX_MANAPHY,
    NATIONAL_DEX_DARKRAI,
    NATIONAL_DEX_SHAYMIN,
    NATIONAL_DEX_ARCEUS,
    // Unova
    NATIONAL_DEX_VICTINI,
    
    NATIONAL_DEX_ZORUA,
    NATIONAL_DEX_ZOROARK,
    
    NATIONAL_DEX_DEERLING,
    NATIONAL_DEX_SAWSBUCK,
    
    NATIONAL_DEX_COBALION,
    NATIONAL_DEX_TERRAKION,
    NATIONAL_DEX_VIRIZION,
    NATIONAL_DEX_TORNADUS,
    NATIONAL_DEX_THUNDURUS,
    NATIONAL_DEX_RESHIRAM,
    NATIONAL_DEX_ZEKROM,
    NATIONAL_DEX_LANDORUS,
    NATIONAL_DEX_KYUREM,
    NATIONAL_DEX_KELDEO,
    NATIONAL_DEX_MELOETTA,
    NATIONAL_DEX_GENESECT,
    // Kalos
    NATIONAL_DEX_FROAKIE,
    NATIONAL_DEX_FROGADIER,
    NATIONAL_DEX_GRENINJA,
    
    NATIONAL_DEX_SCATTERBUG,
    NATIONAL_DEX_SPEWPA,
    NATIONAL_DEX_VIVILLON,
    
    NATIONAL_DEX_FLABEBE,
    NATIONAL_DEX_FLOETTE,
    NATIONAL_DEX_FLORGES,
    
    NATIONAL_DEX_FURFROU,
    
    NATIONAL_DEX_HONEDGE,
    NATIONAL_DEX_DOUBLADE,
    NATIONAL_DEX_AEGISLASH,
    
    NATIONAL_DEX_PUMPKABOO,
    NATIONAL_DEX_GOURGEIST,
    NATIONAL_DEX_BERGMITE,
    NATIONAL_DEX_AVALUGG,
    
    NATIONAL_DEX_XERNEAS,
    NATIONAL_DEX_YVELTAL,
    NATIONAL_DEX_ZYGARDE,
    NATIONAL_DEX_DIANCIE,
    NATIONAL_DEX_HOOPA,
    NATIONAL_DEX_VOLCANION,
    // Alola
    NATIONAL_DEX_ORICORIO,
    
    NATIONAL_DEX_ROCKRUFF,
    NATIONAL_DEX_LYCANROC,
    NATIONAL_DEX_WISHIWASHI,
    
    NATIONAL_DEX_TYPE_NULL,
    NATIONAL_DEX_SILVALLY,
    NATIONAL_DEX_MINIOR,
    
    NATIONAL_DEX_MIMIKYU,
    
    NATIONAL_DEX_TAPU_KOKO,
    NATIONAL_DEX_TAPU_LELE,
    NATIONAL_DEX_TAPU_BULU,
    NATIONAL_DEX_TAPU_FINI,
    NATIONAL_DEX_COSMOG,
    NATIONAL_DEX_COSMOEM,
    NATIONAL_DEX_SOLGALEO,
    NATIONAL_DEX_LUNALA,
    NATIONAL_DEX_NIHILEGO,
    NATIONAL_DEX_BUZZWOLE,
    NATIONAL_DEX_PHEROMOSA,
    NATIONAL_DEX_XURKITREE,
    NATIONAL_DEX_CELESTEELA,
    NATIONAL_DEX_KARTANA,
    NATIONAL_DEX_GUZZLORD,
    NATIONAL_DEX_NECROZMA,
    NATIONAL_DEX_MAGEARNA,
    NATIONAL_DEX_MARSHADOW,
    NATIONAL_DEX_POIPOLE,
    NATIONAL_DEX_NAGANADEL,
    NATIONAL_DEX_STAKATAKA,
    NATIONAL_DEX_BLACEPHALON,
    NATIONAL_DEX_ZERAORA,
    // Unknown
    NATIONAL_DEX_MELTAN,
    NATIONAL_DEX_MELMETAL,
    // Galar
    
    NATIONAL_DEX_CRAMORANT,
    
    NATIONAL_DEX_TOXEL,
    NATIONAL_DEX_TOXTRICITY,
    
    NATIONAL_DEX_SINISTEA,
    NATIONAL_DEX_POLTEAGEIST,
    
    NATIONAL_DEX_PERRSERKER,
    NATIONAL_DEX_CURSOLA,
    NATIONAL_DEX_SIRFETCHD,
    NATIONAL_DEX_MR_RIME,
    NATIONAL_DEX_RUNERIGUS,
    NATIONAL_DEX_MILCERY,
    NATIONAL_DEX_ALCREMIE,

    NATIONAL_DEX_EISCUE,
    NATIONAL_DEX_INDEEDEE,
    NATIONAL_DEX_MORPEKO,
    
    NATIONAL_DEX_ZACIAN,
    NATIONAL_DEX_ZAMAZENTA,
    NATIONAL_DEX_ETERNATUS,
    NATIONAL_DEX_KUBFU,
    NATIONAL_DEX_URSHIFU,
    NATIONAL_DEX_ZARUDE,
    NATIONAL_DEX_REGIELEKI,
    NATIONAL_DEX_REGIDRAGO,
    NATIONAL_DEX_GLASTRIER,
    NATIONAL_DEX_SPECTRIER,
    NATIONAL_DEX_CALYREX,
    NATIONAL_DEX_WYRDEER,
    NATIONAL_DEX_KLEAVOR,
    NATIONAL_DEX_URSALUNA,
    NATIONAL_DEX_BASCULEGION,
    NATIONAL_DEX_SNEASLER,
    NATIONAL_DEX_OVERQWIL,
    NATIONAL_DEX_ENAMORUS,
    NATIONAL_DEX_TIDPIT,
    NATIONAL_DEX_SLIDLOW,
    NATIONAL_DEX_CARDIOVOR,
    NATIONAL_DEX_FIEFREET,
    NATIONAL_DEX_BALBYRN,
    NATIONAL_DEX_BLAZIZAHAK,
    NATIONAL_DEX_PRONGY,
    NATIONAL_DEX_TRIDALIER,
    NATIONAL_DEX_TRITONAUT,
    NATIONAL_DEX_SNELFREND,
    NATIONAL_DEX_SYCOPLOD,
    NATIONAL_DEX_SYCOSTROM,
    NATIONAL_DEX_GUPSPAR,
    NATIONAL_DEX_VANGAR,
    NATIONAL_DEX_GHAERIAL,
    NATIONAL_DEX_MARINAROC,
    NATIONAL_DEX_METTATOLL,
    NATIONAL_DEX_ICKSQUEEK,
    NATIONAL_DEX_KOMORODE,
    NATIONAL_DEX_KYUDI,
    NATIONAL_DEX_KOMBAKYU,
    NATIONAL_DEX_FLUFFSIR,
    NATIONAL_DEX_FLUFFREAR,
    NATIONAL_DEX_SAINTISOW,
    NATIONAL_DEX_SANCTISOW,
    NATIONAL_DEX_SOWPHIROTH,
    NATIONAL_DEX_TOXEXOT,
    NATIONAL_DEX_PSEUDRA,
    NATIONAL_DEX_MANDIMYTE,
    NATIONAL_DEX_TERMINYTE,
    NATIONAL_DEX_SNOTLOUD,
    NATIONAL_DEX_SICKBEAT,
    NATIONAL_DEX_SPRYTE,
    NATIONAL_DEX_GUMONA,
    NATIONAL_DEX_NANGGAL,
    NATIONAL_DEX_SHEEDRAKE,
    NATIONAL_DEX_TRANSERA,
    NATIONAL_DEX_BIVAGUE,
    NATIONAL_DEX_LUSCKAW,
    NATIONAL_DEX_SADSOD,
    NATIONAL_DEX_MAERACHOLY,
    NATIONAL_DEX_LUMELMO,
    NATIONAL_DEX_LUMENDELA,
    NATIONAL_DEX_STOMAWAY,
    NATIONAL_DEX_CRAWLAXY,
    NATIONAL_DEX_MAGNALURE,
    NATIONAL_DEX_MAGNANICOR,
    NATIONAL_DEX_CRYPLIN,
    NATIONAL_DEX_UHEFOE,
    NATIONAL_DEX_MYSTOMANIA,
    NATIONAL_DEX_LYORESA,
    NATIONAL_DEX_KODOUGH,
    NATIONAL_DEX_SLICKSLICE,
    NATIONAL_DEX_LOAFOOF,
    NATIONAL_DEX_SPIRITOAST,
};

#define KANTO_DEX_COUNT     NATIONAL_DEX_MEW
#define JOHTO_DEX_COUNT     NATIONAL_DEX_CELEBI

#if P_GEN_8_POKEMON == TRUE
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_SPIRITOAST
#elif P_GEN_7_POKEMON == TRUE
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_MELMETAL
#elif P_GEN_6_POKEMON == TRUE
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_VOLCANION
#elif P_GEN_5_POKEMON == TRUE
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_GENESECT
#elif P_GEN_4_POKEMON == TRUE
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_ARCEUS
#else
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_DEOXYS
#endif

#define POKEMON_SLOTS_NUMBER (NATIONAL_DEX_COUNT + 1)

// Hoenn Pokedex order
enum {
    HOENN_DEX_NONE,
    HOENN_DEX_TIDPIT,
    HOENN_DEX_SLIDLOW,
    HOENN_DEX_CARDIOVOR,
    HOENN_DEX_FIEFREET,
    HOENN_DEX_BALBYRN,
    HOENN_DEX_BLAZIZAHAK,
    HOENN_DEX_PRONGY,
    HOENN_DEX_TRIDALIER,
    HOENN_DEX_TRITONAUT,
    HOENN_DEX_SNELFREND,
    HOENN_DEX_SYCOPLOD,
    HOENN_DEX_SYCOSTROM,
    HOENN_DEX_GUPSPAR,
    HOENN_DEX_VANGAR,
    HOENN_DEX_GHAERIAL,
    HOENN_DEX_MARINAROC,
    HOENN_DEX_METTATOLL,
    HOENN_DEX_ICKSQUEEK,
    HOENN_DEX_KOMORODE,
    HOENN_DEX_KYUDI,
    HOENN_DEX_KOMBAKYU,
    HOENN_DEX_FLUFFSIR,
    HOENN_DEX_FLUFFREAR,
    HOENN_DEX_SAINTISOW,
    HOENN_DEX_SANCTISOW,
    HOENN_DEX_SOWPHIROTH,
    HOENN_DEX_TOXEXOT,
    HOENN_DEX_PSEUDRA,
    HOENN_DEX_MANDIMYTE,
    HOENN_DEX_TERMINYTE,
    HOENN_DEX_SNOTLOUD,
    HOENN_DEX_SICKBEAT,
    HOENN_DEX_SPRYTE,
    HOENN_DEX_GUMONA,
    HOENN_DEX_NANGGAL,
    HOENN_DEX_SHEEDRAKE,
    HOENN_DEX_TRANSERA,
    HOENN_DEX_BIVAGUE,
    HOENN_DEX_LUSCKAW,
    HOENN_DEX_SADSOD,
    HOENN_DEX_MAERACHOLY,
    HOENN_DEX_LUMELMO,
    HOENN_DEX_LUMENDELA,
    HOENN_DEX_STOMAWAY,
    HOENN_DEX_CRAWLAXY,
    HOENN_DEX_MAGNALURE,
    HOENN_DEX_MAGNANICOR,
    HOENN_DEX_CRYPLIN,
    HOENN_DEX_UHEFOE,
    HOENN_DEX_MYSTOMANIA,
    HOENN_DEX_LYORESA,
    HOENN_DEX_MINIOR,
    HOENN_DEX_LEDYBA,
    HOENN_DEX_LEDIAN,
    HOENN_DEX_ZIGZAGOON,
    HOENN_DEX_LINOONE,
    HOENN_DEX_SPOINK,
    HOENN_DEX_GRUMPIG,
    HOENN_DEX_KODOUGH,
    HOENN_DEX_SLICKSLICE,
    HOENN_DEX_LOAFOOF,
    HOENN_DEX_SPIRITOAST,
};

#define HOENN_DEX_COUNT (HOENN_DEX_SPIRITOAST + 1)

#endif // GUARD_CONSTANTS_POKEDEX_H
