#ifndef GUARD_CONSTANTS_SPECIES_H
#define GUARD_CONSTANTS_SPECIES_H

#define SPECIES_NONE 0 
#define SPECIES_BULBASAUR 1 
#define SPECIES_IVYSAUR 2 
#define SPECIES_VENUSAUR 3 
#define SPECIES_CHARMANDER 4 
#define SPECIES_CHARMELEON 5 
#define SPECIES_CHARIZARD 6 
#define SPECIES_SQUIRTLE 7 
#define SPECIES_WARTORTLE 8 
#define SPECIES_BLASTOISE 9 


#define SPECIES_RATTATA 10 
#define SPECIES_RATICATE 11 

#define SPECIES_PIKACHU 12 
#define SPECIES_RAICHU 13 
#define SPECIES_SANDSHREW 14 
#define SPECIES_SANDSLASH 15 

#define SPECIES_VULPIX 16 
#define SPECIES_NINETALES 17 

#define SPECIES_DIGLETT 18 
#define SPECIES_DUGTRIO 19 
#define SPECIES_MEOWTH 20 
#define SPECIES_PERSIAN 21 
 

#define SPECIES_GEODUDE 22 
#define SPECIES_GRAVELER 23 
#define SPECIES_GOLEM 24 
#define SPECIES_PONYTA 25 
#define SPECIES_RAPIDASH 26 
#define SPECIES_SLOWPOKE 27 
#define SPECIES_SLOWBRO 28 

#define SPECIES_FARFETCHD 29 

#define SPECIES_GRIMER 30 
#define SPECIES_MUK 31 

#define SPECIES_MR_MIME 32 

#define SPECIES_DITTO 33 

#define SPECIES_ARTICUNO 34 
#define SPECIES_ZAPDOS 35 
#define SPECIES_MOLTRES 36 

#define SPECIES_MEWTWO 37 
#define SPECIES_MEW 38 

#define SPECIES_SHUCKLE 39 

#define SPECIES_RAIKOU 40 
#define SPECIES_ENTEI 41 
#define SPECIES_SUICUNE 42 

#define SPECIES_LUGIA 43 
#define SPECIES_HO_OH 44 
#define SPECIES_CELEBI 45 
#define SPECIES_TREECKO 46 
#define SPECIES_GROVYLE 47 
#define SPECIES_SCEPTILE 48 
#define SPECIES_TORCHIC 49 
#define SPECIES_COMBUSKEN 50 
#define SPECIES_BLAZIKEN 51 
#define SPECIES_MUDKIP 52 
#define SPECIES_MARSHTOMP 53 
#define SPECIES_SWAMPERT 54 

#define SPECIES_NINCADA 55 
#define SPECIES_NINJASK 56 
#define SPECIES_SHEDINJA 57 

#define SPECIES_REGIROCK 58 
#define SPECIES_REGICE 59 
#define SPECIES_REGISTEEL 60 
#define SPECIES_LATIAS 61 
#define SPECIES_LATIOS 62 
#define SPECIES_KYOGRE 63 
#define SPECIES_GROUDON 64 
#define SPECIES_RAYQUAZA 65 
#define SPECIES_JIRACHI 66 
#define SPECIES_DEOXYS 67 

#define SPECIES_CHERUBI 68 
#define SPECIES_CHERRIM 69 
#define SPECIES_SHELLOS 70 
#define SPECIES_GASTRODON 71 

#define SPECIES_ROTOM 72 
#define SPECIES_UXIE 73 
#define SPECIES_MESPRIT 74 
#define SPECIES_AZELF 75 
#define SPECIES_DIALGA 76 
#define SPECIES_PALKIA 77 
#define SPECIES_HEATRAN 78 
#define SPECIES_REGIGIGAS 79 
#define SPECIES_GIRATINA 80 
#define SPECIES_CRESSELIA 81 
#define SPECIES_PHIONE 82 
#define SPECIES_MANAPHY 83 
#define SPECIES_DARKRAI 84 
#define SPECIES_SHAYMIN 85 
#define SPECIES_ARCEUS 86 
#define SPECIES_VICTINI 87 

#define SPECIES_ZORUA 88 
#define SPECIES_ZOROARK 89 

#define SPECIES_DEERLING 90 
#define SPECIES_SAWSBUCK 91 


#define SPECIES_COBALION 92 
#define SPECIES_TERRAKION 93 
#define SPECIES_VIRIZION 94 
#define SPECIES_TORNADUS 95 
#define SPECIES_THUNDURUS 96 
#define SPECIES_RESHIRAM 97 
#define SPECIES_ZEKROM 98 
#define SPECIES_LANDORUS 99 
#define SPECIES_KYUREM 100 
#define SPECIES_KELDEO 101 
#define SPECIES_MELOETTA 102 
#define SPECIES_GENESECT 103 

#define SPECIES_FROAKIE 104 
#define SPECIES_FROGADIER 105 
#define SPECIES_GRENINJA 106 

#define SPECIES_SCATTERBUG 107 
#define SPECIES_SPEWPA 108 
#define SPECIES_VIVILLON 109 // Icy Snow Pattern 

#define SPECIES_FLABEBE 110 // Red Flower 
#define SPECIES_FLOETTE 111 
#define SPECIES_FLORGES 112 

#define SPECIES_FURFROU 113 

#define SPECIES_HONEDGE 114 
#define SPECIES_DOUBLADE 115 
#define SPECIES_AEGISLASH 116 

#define SPECIES_PUMPKABOO 117 
#define SPECIES_GOURGEIST 118 
#define SPECIES_BERGMITE 119 
#define SPECIES_AVALUGG 120 

#define SPECIES_XERNEAS 121 
#define SPECIES_YVELTAL 122 
#define SPECIES_ZYGARDE 123 
#define SPECIES_DIANCIE 124 
#define SPECIES_HOOPA 125 
#define SPECIES_VOLCANION 126 

#define SPECIES_ORICORIO 127 

#define SPECIES_ROCKRUFF 128 
#define SPECIES_LYCANROC 129 
#define SPECIES_WISHIWASHI 130 
#define SPECIES_TYPE_NULL 131 
#define SPECIES_SILVALLY 132 
#define SPECIES_MINIOR 133 

#define SPECIES_MIMIKYU 134 

#define SPECIES_TAPU_KOKO 135 
#define SPECIES_TAPU_LELE 136 
#define SPECIES_TAPU_BULU 137 
#define SPECIES_TAPU_FINI 138 
#define SPECIES_COSMOG 139 
#define SPECIES_COSMOEM 140 
#define SPECIES_SOLGALEO 141 
#define SPECIES_LUNALA 142 
#define SPECIES_NIHILEGO 143 
#define SPECIES_BUZZWOLE 144 
#define SPECIES_PHEROMOSA 145 
#define SPECIES_XURKITREE 146 
#define SPECIES_CELESTEELA 147 
#define SPECIES_KARTANA 148 
#define SPECIES_GUZZLORD 149 
#define SPECIES_NECROZMA 150 
#define SPECIES_MAGEARNA 151 
#define SPECIES_MARSHADOW 152 
#define SPECIES_POIPOLE 153 
#define SPECIES_NAGANADEL 154 
#define SPECIES_STAKATAKA 155 
#define SPECIES_BLACEPHALON 156 
#define SPECIES_ZERAORA 157 
#define SPECIES_MELTAN 158 
#define SPECIES_MELMETAL 159 

#define SPECIES_CRAMORANT 160 
#define SPECIES_TOXEL 161 
#define SPECIES_TOXTRICITY 162 
#define SPECIES_SINISTEA 163 
#define SPECIES_POLTEAGEIST 164 
#define SPECIES_OBSTAGOON 165 
#define SPECIES_PERRSERKER 166 
#define SPECIES_CURSOLA 167 
#define SPECIES_SIRFETCHD 168 
#define SPECIES_MR_RIME 169 
#define SPECIES_RUNERIGUS 170 
#define SPECIES_MILCERY 171 
#define SPECIES_ALCREMIE 172 
#define SPECIES_EISCUE 173 
#define SPECIES_MORPEKO 174 
#define SPECIES_ZACIAN 175 
#define SPECIES_ZAMAZENTA 176 
#define SPECIES_ETERNATUS 177 
#define SPECIES_KUBFU 178 
#define SPECIES_URSHIFU 179 
#define SPECIES_ZARUDE 180 
#define SPECIES_REGIELEKI 181 
#define SPECIES_REGIDRAGO 182 
#define SPECIES_GLASTRIER 183 
#define SPECIES_SPECTRIER 184 
#define SPECIES_CALYREX 185 
#define SPECIES_WYRDEER 186 
#define SPECIES_KLEAVOR 187 
#define SPECIES_URSALUNA 188 
#define SPECIES_BASCULEGION 189 
#define SPECIES_SNEASLER 190 
#define SPECIES_OVERQWIL 191 
#define SPECIES_ENAMORUS 192 

#define NEW_MONS_START   (SPECIES_ENAMORUS + 1)

#define SPECIES_TIDPIT 193 
#define SPECIES_SLIDLOW 194 
#define SPECIES_CARDIOVOR 195 
#define SPECIES_FIEFREET 196 
#define SPECIES_BALBYRN 197 
#define SPECIES_BLAZIZAHAK 198 
#define SPECIES_PRONGY 199 
#define SPECIES_TRIDALIER 200 
#define SPECIES_TRITONAUT 201 
#define SPECIES_SNELFREND 202 
#define SPECIES_SYCOPLOD 203 
#define SPECIES_SYCOSTROM 204 
#define SPECIES_GUPSPAR 205 
#define SPECIES_VANGAR 206 
#define SPECIES_GHAERIAL 207 
#define SPECIES_MARINAROC 208 
#define SPECIES_METTATOLL 209 
#define SPECIES_ICKSQUEEK 210 
#define SPECIES_KOMORODE 211 
#define SPECIES_KYUDI 212 
#define SPECIES_KOMBAKYU 213 
#define SPECIES_FLUFFSIR 214 
#define SPECIES_FLUFFREAR 215 
#define SPECIES_SAINTISOW 216 
#define SPECIES_SANCTISOW 217 
#define SPECIES_SOWPHIROTH 218 
#define SPECIES_TOXEXOT 219 
#define SPECIES_PSEUDRA 220 
#define SPECIES_MANDIMYTE 221 
#define SPECIES_TERMINYTE 222 
#define SPECIES_SNOTLOUD 223 
#define SPECIES_SICKBEAT 224 
#define SPECIES_SPRYTE 225 
#define SPECIES_GUMONA 226 
#define SPECIES_NANGGAL 227 
#define SPECIES_SHEEDRAKE 228 
#define SPECIES_TRANSERA 229 
#define SPECIES_BIVAGUE 230 
#define SPECIES_LUSCKAW 231 
#define SPECIES_SADSOD 232 
#define SPECIES_MAERACHOLY 233 
#define SPECIES_LUMELMO 234 
#define SPECIES_LUMENDELA 235 
#define SPECIES_STOMAWAY 236 
#define SPECIES_CRAWLAXY 237 
#define SPECIES_MAGNALURE 238 
#define SPECIES_MAGNANICOR 239 
#define SPECIES_CRYPLIN 240 
#define SPECIES_UHEFOE 241 
#define SPECIES_MYSTOMANIA 242 
#define SPECIES_LYORESA 243 
#define SPECIES_KODOUGH 244 
#define SPECIES_SLICKSLICE 245 
#define SPECIES_LOAFOOF 246 
#define SPECIES_SPIRITOAST 247 

#define NEW_MONS_END (SPECIES_SPIRITOAST)
#define NUM_NEW_MONS (NEW_MONS_END - NEW_MONS_START)
// Megas
#define SPECIES_VENUSAUR_MEGA FORMS_START + 1 
#define SPECIES_CHARIZARD_MEGA_X FORMS_START + 2 
#define SPECIES_CHARIZARD_MEGA_Y FORMS_START + 3 
#define SPECIES_BLASTOISE_MEGA FORMS_START + 4 
#define SPECIES_SLOWBRO_MEGA FORMS_START + 5 
#define SPECIES_MEWTWO_MEGA_X FORMS_START + 6 
#define SPECIES_MEWTWO_MEGA_Y FORMS_START + 7 
#define SPECIES_SCEPTILE_MEGA FORMS_START + 8 
#define SPECIES_BLAZIKEN_MEGA FORMS_START + 9 
#define SPECIES_SWAMPERT_MEGA FORMS_START + 10 
#define SPECIES_LATIAS_MEGA FORMS_START + 11 
#define SPECIES_LATIOS_MEGA FORMS_START + 12 

// Special Mega + Primals
#define SPECIES_RAYQUAZA_MEGA FORMS_START + 13 
#define SPECIES_KYOGRE_PRIMAL FORMS_START + 14 
#define SPECIES_GROUDON_PRIMAL FORMS_START + 15 

// Alolan Forms
#define SPECIES_RATTATA_ALOLAN FORMS_START + 16 
#define SPECIES_RATICATE_ALOLAN FORMS_START + 17 
#define SPECIES_RAICHU_ALOLAN FORMS_START + 18 
#define SPECIES_SANDSHREW_ALOLAN FORMS_START + 19 
#define SPECIES_SANDSLASH_ALOLAN FORMS_START + 20 
#define SPECIES_VULPIX_ALOLAN FORMS_START + 21 
#define SPECIES_NINETALES_ALOLAN FORMS_START + 22 
#define SPECIES_DIGLETT_ALOLAN FORMS_START + 23 
#define SPECIES_DUGTRIO_ALOLAN FORMS_START + 24 
#define SPECIES_MEOWTH_ALOLAN FORMS_START + 25 
#define SPECIES_PERSIAN_ALOLAN FORMS_START + 26 
#define SPECIES_GEODUDE_ALOLAN FORMS_START + 27 
#define SPECIES_GRAVELER_ALOLAN FORMS_START + 28 
#define SPECIES_GOLEM_ALOLAN FORMS_START + 29 
#define SPECIES_GRIMER_ALOLAN FORMS_START + 30 
#define SPECIES_MUK_ALOLAN FORMS_START + 31 

// Galarian Forms
#define SPECIES_MEOWTH_GALARIAN FORMS_START + 32 
#define SPECIES_PONYTA_GALARIAN FORMS_START + 33 
#define SPECIES_RAPIDASH_GALARIAN FORMS_START + 34 
#define SPECIES_SLOWPOKE_GALARIAN FORMS_START + 35 
#define SPECIES_SLOWBRO_GALARIAN FORMS_START + 36 
#define SPECIES_FARFETCHD_GALARIAN FORMS_START + 37 
#define SPECIES_MR_MIME_GALARIAN FORMS_START + 38 
#define SPECIES_ARTICUNO_GALARIAN FORMS_START + 39 
#define SPECIES_ZAPDOS_GALARIAN FORMS_START + 40 
#define SPECIES_MOLTRES_GALARIAN FORMS_START + 41 
#define SPECIES_CORSOLA_GALARIAN FORMS_START + 42 
#define SPECIES_ZIGZAGOON_GALARIAN FORMS_START + 43 
#define SPECIES_LINOONE_GALARIAN FORMS_START + 44 
#define SPECIES_DARUMAKA_GALARIAN FORMS_START + 45 
#define SPECIES_DARMANITAN_GALARIAN FORMS_START + 46 
#define SPECIES_YAMASK_GALARIAN FORMS_START + 47 
#define SPECIES_STUNFISK_GALARIAN FORMS_START + 48 

//Hisuian Forms
#define SPECIES_ZORUA_HISUIAN FORMS_START + 49 
#define SPECIES_ZOROARK_HISUIAN FORMS_START + 50 
#define SPECIES_AVALUGG_HISUIAN FORMS_START + 51 

// Misc Forms

// Cosplay Pikachu
#define SPECIES_PIKACHU_COSPLAY FORMS_START + 52 
#define SPECIES_PIKACHU_ROCK_STAR FORMS_START + 53 
#define SPECIES_PIKACHU_BELLE FORMS_START + 54 
#define SPECIES_PIKACHU_POP_STAR FORMS_START + 55 
#define SPECIES_PIKACHU_PH_D FORMS_START + 56 
#define SPECIES_PIKACHU_LIBRE FORMS_START + 57 

// Cap Pikachu
#define SPECIES_PIKACHU_ORIGINAL_CAP FORMS_START + 58 
#define SPECIES_PIKACHU_HOENN_CAP FORMS_START + 59 
#define SPECIES_PIKACHU_SINNOH_CAP FORMS_START + 60 
#define SPECIES_PIKACHU_UNOVA_CAP FORMS_START + 61 
#define SPECIES_PIKACHU_KALOS_CAP FORMS_START + 62 
#define SPECIES_PIKACHU_ALOLA_CAP FORMS_START + 63 
#define SPECIES_PIKACHU_PARTNER_CAP FORMS_START + 64 
#define SPECIES_PIKACHU_WORLD_CAP FORMS_START + 65 

// Pichu
#define SPECIES_PICHU_SPIKY_EARED FORMS_START + 66 

// Unown
#define SPECIES_UNOWN_B FORMS_START + 67 
#define SPECIES_UNOWN_C FORMS_START + 68 
#define SPECIES_UNOWN_D FORMS_START + 69 
#define SPECIES_UNOWN_E FORMS_START + 70 
#define SPECIES_UNOWN_F FORMS_START + 71 
#define SPECIES_UNOWN_G FORMS_START + 72 
#define SPECIES_UNOWN_H FORMS_START + 73 
#define SPECIES_UNOWN_I FORMS_START + 74 
#define SPECIES_UNOWN_J FORMS_START + 75 
#define SPECIES_UNOWN_K FORMS_START + 76 
#define SPECIES_UNOWN_L FORMS_START + 77 
#define SPECIES_UNOWN_M FORMS_START + 78 
#define SPECIES_UNOWN_N FORMS_START + 79 
#define SPECIES_UNOWN_O FORMS_START + 80 
#define SPECIES_UNOWN_P FORMS_START + 81 
#define SPECIES_UNOWN_Q FORMS_START + 82 
#define SPECIES_UNOWN_R FORMS_START + 83 
#define SPECIES_UNOWN_S FORMS_START + 84 
#define SPECIES_UNOWN_T FORMS_START + 85 
#define SPECIES_UNOWN_U FORMS_START + 86 
#define SPECIES_UNOWN_V FORMS_START + 87 
#define SPECIES_UNOWN_W FORMS_START + 88 
#define SPECIES_UNOWN_X FORMS_START + 89 
#define SPECIES_UNOWN_Y FORMS_START + 90 
#define SPECIES_UNOWN_Z FORMS_START + 91 
#define SPECIES_UNOWN_EMARK FORMS_START + 92 
#define SPECIES_UNOWN_QMARK FORMS_START + 93 

// Castform
#define SPECIES_CASTFORM_SUNNY FORMS_START + 94 
#define SPECIES_CASTFORM_RAINY FORMS_START + 95 
#define SPECIES_CASTFORM_SNOWY FORMS_START + 96 

// Deoxys
#define SPECIES_DEOXYS_ATTACK FORMS_START + 97 
#define SPECIES_DEOXYS_DEFENSE FORMS_START + 98 
#define SPECIES_DEOXYS_SPEED FORMS_START + 99 

// Cherrim
#define SPECIES_CHERRIM_SUNSHINE FORMS_START + 100 

// Shellos
#define SPECIES_SHELLOS_EAST_SEA FORMS_START + 101 

// Gastrodon
#define SPECIES_GASTRODON_EAST_SEA FORMS_START + 102 

// Rotom
#define SPECIES_ROTOM_HEAT FORMS_START + 103 
#define SPECIES_ROTOM_WASH FORMS_START + 104 
#define SPECIES_ROTOM_FROST FORMS_START + 105 
#define SPECIES_ROTOM_FAN FORMS_START + 106 
#define SPECIES_ROTOM_MOW FORMS_START + 107 

// Origin Forme
#define SPECIES_DIALGA_ORIGIN FORMS_START + 108 
#define SPECIES_PALKIA_ORIGIN FORMS_START + 109 
#define SPECIES_GIRATINA_ORIGIN FORMS_START + 110 

// Shaymin
#define SPECIES_SHAYMIN_SKY FORMS_START + 111 

// Arceus
#define SPECIES_ARCEUS_FIGHTING FORMS_START + 112 
#define SPECIES_ARCEUS_FLYING FORMS_START + 113 
#define SPECIES_ARCEUS_POISON FORMS_START + 114 
#define SPECIES_ARCEUS_GROUND FORMS_START + 115 
#define SPECIES_ARCEUS_ROCK FORMS_START + 116 
#define SPECIES_ARCEUS_BUG FORMS_START + 117 
#define SPECIES_ARCEUS_GHOST FORMS_START + 118 
#define SPECIES_ARCEUS_STEEL FORMS_START + 119 
#define SPECIES_ARCEUS_FIRE FORMS_START + 120 
#define SPECIES_ARCEUS_WATER FORMS_START + 121 
#define SPECIES_ARCEUS_GRASS FORMS_START + 122 
#define SPECIES_ARCEUS_ELECTRIC FORMS_START + 123 
#define SPECIES_ARCEUS_PSYCHIC FORMS_START + 124 
#define SPECIES_ARCEUS_ICE FORMS_START + 125 
#define SPECIES_ARCEUS_DRAGON FORMS_START + 126 
#define SPECIES_ARCEUS_DARK FORMS_START + 127 
#define SPECIES_ARCEUS_FAIRY FORMS_START + 128 

// Basculin
#define SPECIES_BASCULIN_BLUE_STRIPED FORMS_START + 129 
#define SPECIES_BASCULIN_WHITE_STRIPED FORMS_START + 130 

// Darmanitan
#define SPECIES_DARMANITAN_ZEN_MODE FORMS_START + 131 
#define SPECIES_DARMANITAN_ZEN_MODE_GALARIAN FORMS_START + 132 

// Deerling
#define SPECIES_DEERLING_SUMMER FORMS_START + 133 
#define SPECIES_DEERLING_AUTUMN FORMS_START + 134 
#define SPECIES_DEERLING_WINTER FORMS_START + 135 

// Sawsbuck
#define SPECIES_SAWSBUCK_SUMMER FORMS_START + 136 
#define SPECIES_SAWSBUCK_AUTUMN FORMS_START + 137 
#define SPECIES_SAWSBUCK_WINTER FORMS_START + 138 

// Therian Forms
#define SPECIES_TORNADUS_THERIAN FORMS_START + 139 
#define SPECIES_THUNDURUS_THERIAN FORMS_START + 140 
#define SPECIES_LANDORUS_THERIAN FORMS_START + 141 
#define SPECIES_ENAMORUS_THERIAN FORMS_START + 142 

// Kyurem
#define SPECIES_KYUREM_WHITE FORMS_START + 143 
#define SPECIES_KYUREM_BLACK FORMS_START + 144 

// Keldeo
#define SPECIES_KELDEO_RESOLUTE FORMS_START + 145 

// Meloetta
#define SPECIES_MELOETTA_PIROUETTE FORMS_START + 146 

// Genesect
#define SPECIES_GENESECT_DOUSE_DRIVE FORMS_START + 147 
#define SPECIES_GENESECT_SHOCK_DRIVE FORMS_START + 148 
#define SPECIES_GENESECT_BURN_DRIVE FORMS_START + 149 
#define SPECIES_GENESECT_CHILL_DRIVE FORMS_START + 150 

// Greninja
#define SPECIES_GRENINJA_BATTLE_BOND FORMS_START + 151 
#define SPECIES_GRENINJA_ASH FORMS_START + 152 

// Vivillon
#define SPECIES_VIVILLON_POLAR FORMS_START + 153 
#define SPECIES_VIVILLON_TUNDRA FORMS_START + 154 
#define SPECIES_VIVILLON_CONTINENTAL FORMS_START + 155 
#define SPECIES_VIVILLON_GARDEN FORMS_START + 156 
#define SPECIES_VIVILLON_ELEGANT FORMS_START + 157 
#define SPECIES_VIVILLON_MEADOW FORMS_START + 158 
#define SPECIES_VIVILLON_MODERN FORMS_START + 159 
#define SPECIES_VIVILLON_MARINE FORMS_START + 160 
#define SPECIES_VIVILLON_ARCHIPELAGO FORMS_START + 161 
#define SPECIES_VIVILLON_HIGH_PLAINS FORMS_START + 162 
#define SPECIES_VIVILLON_SANDSTORM FORMS_START + 163 
#define SPECIES_VIVILLON_RIVER FORMS_START + 164 
#define SPECIES_VIVILLON_MONSOON FORMS_START + 165 
#define SPECIES_VIVILLON_SAVANNA FORMS_START + 166 
#define SPECIES_VIVILLON_SUN FORMS_START + 167 
#define SPECIES_VIVILLON_OCEAN FORMS_START + 168 
#define SPECIES_VIVILLON_JUNGLE FORMS_START + 169 
#define SPECIES_VIVILLON_FANCY FORMS_START + 170 
#define SPECIES_VIVILLON_POKE_BALL FORMS_START + 171 

// Flabébé
#define SPECIES_FLABEBE_YELLOW_FLOWER FORMS_START + 172 
#define SPECIES_FLABEBE_ORANGE_FLOWER FORMS_START + 173 
#define SPECIES_FLABEBE_BLUE_FLOWER FORMS_START + 174 
#define SPECIES_FLABEBE_WHITE_FLOWER FORMS_START + 175 

// Floette
#define SPECIES_FLOETTE_YELLOW_FLOWER FORMS_START + 176 
#define SPECIES_FLOETTE_ORANGE_FLOWER FORMS_START + 177 
#define SPECIES_FLOETTE_BLUE_FLOWER FORMS_START + 178 
#define SPECIES_FLOETTE_WHITE_FLOWER FORMS_START + 179 
#define SPECIES_FLOETTE_ETERNAL_FLOWER FORMS_START + 180 

// Florges
#define SPECIES_FLORGES_YELLOW_FLOWER FORMS_START + 181 
#define SPECIES_FLORGES_ORANGE_FLOWER FORMS_START + 182 
#define SPECIES_FLORGES_BLUE_FLOWER FORMS_START + 183 
#define SPECIES_FLORGES_WHITE_FLOWER FORMS_START + 184 

// Furfrou
#define SPECIES_FURFROU_HEART_TRIM FORMS_START + 185 
#define SPECIES_FURFROU_STAR_TRIM FORMS_START + 186 
#define SPECIES_FURFROU_DIAMOND_TRIM FORMS_START + 187 
#define SPECIES_FURFROU_DEBUTANTE_TRIM FORMS_START + 188 
#define SPECIES_FURFROU_MATRON_TRIM FORMS_START + 189 
#define SPECIES_FURFROU_DANDY_TRIM FORMS_START + 190 
#define SPECIES_FURFROU_LA_REINE_TRIM FORMS_START + 191 
#define SPECIES_FURFROU_KABUKI_TRIM FORMS_START + 192 
#define SPECIES_FURFROU_PHARAOH_TRIM FORMS_START + 193 

// Aegislash
#define SPECIES_AEGISLASH_BLADE FORMS_START + 194 

// Pumpkaboo
#define SPECIES_PUMPKABOO_SMALL FORMS_START + 195 
#define SPECIES_PUMPKABOO_LARGE FORMS_START + 196 
#define SPECIES_PUMPKABOO_SUPER FORMS_START + 197 

// Gourgeist
#define SPECIES_GOURGEIST_SMALL FORMS_START + 198 
#define SPECIES_GOURGEIST_LARGE FORMS_START + 199 
#define SPECIES_GOURGEIST_SUPER FORMS_START + 200 

// Xerneas
#define SPECIES_XERNEAS_ACTIVE FORMS_START + 201 

// Zygarde
#define SPECIES_ZYGARDE_10 FORMS_START + 202 
#define SPECIES_ZYGARDE_10_POWER_CONSTRUCT FORMS_START + 203 
#define SPECIES_ZYGARDE_50_POWER_CONSTRUCT FORMS_START + 204 
#define SPECIES_ZYGARDE_COMPLETE FORMS_START + 205 

// Hoopa
#define SPECIES_HOOPA_UNBOUND FORMS_START + 206 

// Oricorio
#define SPECIES_ORICORIO_POM_POM FORMS_START + 207 
#define SPECIES_ORICORIO_PAU FORMS_START + 208 
#define SPECIES_ORICORIO_SENSU FORMS_START + 209 

// Rockruff
#define SPECIES_ROCKRUFF_OWN_TEMPO FORMS_START + 210 

// Lycanroc
#define SPECIES_LYCANROC_MIDNIGHT FORMS_START + 211 
#define SPECIES_LYCANROC_DUSK FORMS_START + 212 

// Wishiwashi
#define SPECIES_WISHIWASHI_SCHOOL FORMS_START + 213 

// Silvally
#define SPECIES_SILVALLY_FIGHTING FORMS_START + 214 
#define SPECIES_SILVALLY_FLYING FORMS_START + 215 
#define SPECIES_SILVALLY_POISON FORMS_START + 216 
#define SPECIES_SILVALLY_GROUND FORMS_START + 217 
#define SPECIES_SILVALLY_ROCK FORMS_START + 218 
#define SPECIES_SILVALLY_BUG FORMS_START + 219 
#define SPECIES_SILVALLY_GHOST FORMS_START + 220 
#define SPECIES_SILVALLY_STEEL FORMS_START + 221 
#define SPECIES_SILVALLY_FIRE FORMS_START + 222 
#define SPECIES_SILVALLY_WATER FORMS_START + 223 
#define SPECIES_SILVALLY_GRASS FORMS_START + 224 
#define SPECIES_SILVALLY_ELECTRIC FORMS_START + 225 
#define SPECIES_SILVALLY_PSYCHIC FORMS_START + 226 
#define SPECIES_SILVALLY_ICE FORMS_START + 227 
#define SPECIES_SILVALLY_DRAGON FORMS_START + 228 
#define SPECIES_SILVALLY_DARK FORMS_START + 229 
#define SPECIES_SILVALLY_FAIRY FORMS_START + 230 

// Minior
#define SPECIES_MINIOR_METEOR_ORANGE FORMS_START + 231 
#define SPECIES_MINIOR_METEOR_YELLOW FORMS_START + 232 
#define SPECIES_MINIOR_METEOR_GREEN FORMS_START + 233 
#define SPECIES_MINIOR_METEOR_BLUE FORMS_START + 234 
#define SPECIES_MINIOR_METEOR_INDIGO FORMS_START + 235 
#define SPECIES_MINIOR_METEOR_VIOLET FORMS_START + 236 
#define SPECIES_MINIOR_CORE_RED FORMS_START + 237 
#define SPECIES_MINIOR_CORE_ORANGE FORMS_START + 238 
#define SPECIES_MINIOR_CORE_YELLOW FORMS_START + 239 
#define SPECIES_MINIOR_CORE_GREEN FORMS_START + 240 
#define SPECIES_MINIOR_CORE_BLUE FORMS_START + 241 
#define SPECIES_MINIOR_CORE_INDIGO FORMS_START + 242 
#define SPECIES_MINIOR_CORE_VIOLET FORMS_START + 243 

// Mimikyu
#define SPECIES_MIMIKYU_BUSTED FORMS_START + 244 

// Necrozma
#define SPECIES_NECROZMA_DUSK_MANE FORMS_START + 245 
#define SPECIES_NECROZMA_DAWN_WINGS FORMS_START + 246 
#define SPECIES_NECROZMA_ULTRA FORMS_START + 247 

// Magearna
#define SPECIES_MAGEARNA_ORIGINAL_COLOR FORMS_START + 248 

// Cramorant
#define SPECIES_CRAMORANT_GULPING FORMS_START + 249 
#define SPECIES_CRAMORANT_GORGING FORMS_START + 250 

// Toxtricity
#define SPECIES_TOXTRICITY_LOW_KEY FORMS_START + 251 

// Sinistea
#define SPECIES_SINISTEA_ANTIQUE FORMS_START + 252 

// Polteageist
#define SPECIES_POLTEAGEIST_ANTIQUE FORMS_START + 253 

// Alcremie
#define SPECIES_ALCREMIE_RUBY_CREAM FORMS_START + 254 
#define SPECIES_ALCREMIE_MATCHA_CREAM FORMS_START + 255 
#define SPECIES_ALCREMIE_MINT_CREAM FORMS_START + 256 
#define SPECIES_ALCREMIE_LEMON_CREAM FORMS_START + 257 
#define SPECIES_ALCREMIE_SALTED_CREAM FORMS_START + 258 
#define SPECIES_ALCREMIE_RUBY_SWIRL FORMS_START + 259 
#define SPECIES_ALCREMIE_CARAMEL_SWIRL FORMS_START + 260 
#define SPECIES_ALCREMIE_RAINBOW_SWIRL FORMS_START + 261 

// Eiscue
#define SPECIES_EISCUE_NOICE_FACE FORMS_START + 262 

// Morpeko
#define SPECIES_MORPEKO_HANGRY FORMS_START + 263 

// Zacian
#define SPECIES_ZACIAN_CROWNED_SWORD FORMS_START + 264 

// Zamazenta
#define SPECIES_ZAMAZENTA_CROWNED_SHIELD FORMS_START + 265 

// Eternatus
#define SPECIES_ETERNATUS_ETERNAMAX FORMS_START + 266 

// Urshifu
#define SPECIES_URSHIFU_RAPID_STRIKE_STYLE FORMS_START + 267 

// Zarude
#define SPECIES_ZARUDE_DADA FORMS_START + 268 

// Calyrex
#define SPECIES_CALYREX_ICE_RIDER FORMS_START + 269 
#define SPECIES_CALYREX_SHADOW_RIDER FORMS_START + 270 

// Basculegion
#define SPECIES_BASCULEGION_FEMALE FORMS_START + 271 

#define FORMS_START SPECIES_SPIRITOAST
#define SPECIES_EGG SPECIES_BASCULEGION_FEMALE + 272 

#define NUM_SPECIES SPECIES_EGG

#endif  // GUARD_CONSTANTS_SPECIES_H
