#ifndef GUARD_CONSTANTS_SPECIES_H
#define GUARD_CONSTANTS_SPECIES_H

#define SPECIES_NONE 0 
#define SPECIES_BULBASAUR 1 
#define SPECIES_IVYSAUR 2 
#define SPECIES_VENUSAUR 3 
#define SPECIES_CHARMANDER 4 
#define SPECIES_CHARMELEON 5 
#define SPECIES_CHARIZARD 6 
#define SPECIES_SQUIRTLE 7 
#define SPECIES_WARTORTLE 8 
#define SPECIES_BLASTOISE 9 
#define SPECIES_CATERPIE 10 
#define SPECIES_METAPOD 11 
#define SPECIES_BUTTERFREE 12 
#define SPECIES_WEEDLE 13 
#define SPECIES_KAKUNA 14 
#define SPECIES_BEEDRILL 15 
#define SPECIES_PIDGEY 16 
#define SPECIES_PIDGEOTTO 17 
#define SPECIES_PIDGEOT 18 
#define SPECIES_RATTATA 19 
#define SPECIES_RATICATE 20 
#define SPECIES_SPEAROW 21 
#define SPECIES_FEAROW 22 
#define SPECIES_EKANS 23 
#define SPECIES_ARBOK 24 
#define SPECIES_PIKACHU 25 
#define SPECIES_RAICHU 26 
#define SPECIES_SANDSHREW 27 
#define SPECIES_SANDSLASH 28 
#define SPECIES_NIDORAN_F 29 
#define SPECIES_NIDORINA 30 
#define SPECIES_NIDOQUEEN 31 
#define SPECIES_NIDORAN_M 32 
#define SPECIES_NIDORINO 33 
#define SPECIES_NIDOKING 34 
#define SPECIES_CLEFAIRY 35 
#define SPECIES_CLEFABLE 36 
#define SPECIES_VULPIX 37 
#define SPECIES_NINETALES 38 
#define SPECIES_JIGGLYPUFF 39 
#define SPECIES_WIGGLYTUFF 40 
#define SPECIES_ZUBAT 41 
#define SPECIES_GOLBAT 42 
#define SPECIES_ODDISH 43 
#define SPECIES_GLOOM 44 
#define SPECIES_VILEPLUME 45 
#define SPECIES_PARAS 46 
#define SPECIES_PARASECT 47 
#define SPECIES_VENONAT 48 
#define SPECIES_VENOMOTH 49 
#define SPECIES_DIGLETT 50 
#define SPECIES_DUGTRIO 51 
#define SPECIES_MEOWTH 52 
#define SPECIES_PERSIAN 53 
#define SPECIES_PSYDUCK 54 
#define SPECIES_GOLDUCK 55 
#define SPECIES_MANKEY 56 
#define SPECIES_PRIMEAPE 57 
#define SPECIES_GROWLITHE 58 
#define SPECIES_ARCANINE 59 
#define SPECIES_POLIWAG 60 
#define SPECIES_POLIWHIRL 61 
#define SPECIES_POLIWRATH 62 
#define SPECIES_ABRA 63 
#define SPECIES_KADABRA 64 
#define SPECIES_ALAKAZAM 65 
#define SPECIES_MACHOP 66 
#define SPECIES_MACHOKE 67 
#define SPECIES_MACHAMP 68 
#define SPECIES_BELLSPROUT 69 
#define SPECIES_WEEPINBELL 70 
#define SPECIES_VICTREEBEL 71 
#define SPECIES_TENTACOOL 72 
#define SPECIES_TENTACRUEL 73 
#define SPECIES_GEODUDE 74 
#define SPECIES_GRAVELER 75 
#define SPECIES_GOLEM 76 
#define SPECIES_PONYTA 77 
#define SPECIES_RAPIDASH 78 
#define SPECIES_SLOWPOKE 79 
#define SPECIES_SLOWBRO 80 
#define SPECIES_MAGNEMITE 81 
#define SPECIES_MAGNETON 82 
#define SPECIES_FARFETCHD 83 
#define SPECIES_DODUO 84 
#define SPECIES_DODRIO 85 
#define SPECIES_SEEL 86 
#define SPECIES_DEWGONG 87 
#define SPECIES_GRIMER 88 
#define SPECIES_MUK 89 
#define SPECIES_SHELLDER 90 
#define SPECIES_CLOYSTER 91 
#define SPECIES_GASTLY 92 
#define SPECIES_HAUNTER 93 
#define SPECIES_GENGAR 94 
#define SPECIES_ONIX 95 
#define SPECIES_DROWZEE 96 
#define SPECIES_HYPNO 97 
#define SPECIES_KRABBY 98 
#define SPECIES_KINGLER 99 
#define SPECIES_VOLTORB 100 
#define SPECIES_ELECTRODE 101 
#define SPECIES_EXEGGCUTE 102 
#define SPECIES_EXEGGUTOR 103 
#define SPECIES_CUBONE 104 
#define SPECIES_MAROWAK 105 
#define SPECIES_HITMONLEE 106 
#define SPECIES_HITMONCHAN 107 
#define SPECIES_LICKITUNG 108 
#define SPECIES_KOFFING 109 
#define SPECIES_WEEZING 110 
#define SPECIES_RHYHORN 111 
#define SPECIES_RHYDON 112 
#define SPECIES_CHANSEY 113 
#define SPECIES_TANGELA 114 
#define SPECIES_KANGASKHAN 115 
#define SPECIES_HORSEA 116 
#define SPECIES_SEADRA 117 
#define SPECIES_GOLDEEN 118 
#define SPECIES_SEAKING 119 
#define SPECIES_STARYU 120 
#define SPECIES_STARMIE 121 
#define SPECIES_MR_MIME 122 
#define SPECIES_SCYTHER 123 
#define SPECIES_JYNX 124 
#define SPECIES_ELECTABUZZ 125 
#define SPECIES_MAGMAR 126 
#define SPECIES_PINSIR 127 
#define SPECIES_TAUROS 128 
#define SPECIES_MAGIKARP 129 
#define SPECIES_GYARADOS 130 
#define SPECIES_LAPRAS 131 
#define SPECIES_DITTO 132 
#define SPECIES_EEVEE 133 
#define SPECIES_VAPOREON 134 
#define SPECIES_JOLTEON 135 
#define SPECIES_FLAREON 136 
#define SPECIES_PORYGON 137 
#define SPECIES_OMANYTE 138 
#define SPECIES_OMASTAR 139 
#define SPECIES_KABUTO 140 
#define SPECIES_KABUTOPS 141 
#define SPECIES_AERODACTYL 142 
#define SPECIES_SNORLAX 143 
#define SPECIES_ARTICUNO 144 
#define SPECIES_ZAPDOS 145 
#define SPECIES_MOLTRES 146 
#define SPECIES_DRATINI 147 
#define SPECIES_DRAGONAIR 148 
#define SPECIES_DRAGONITE 149 
#define SPECIES_MEWTWO 150 
#define SPECIES_MEW 151 
#define SPECIES_CHIKORITA 152 
#define SPECIES_BAYLEEF 153 
#define SPECIES_MEGANIUM 154 
#define SPECIES_CYNDAQUIL 155 
#define SPECIES_QUILAVA 156 
#define SPECIES_TYPHLOSION 157 
#define SPECIES_TOTODILE 158 
#define SPECIES_CROCONAW 159 
#define SPECIES_FERALIGATR 160 
#define SPECIES_SENTRET 161 
#define SPECIES_FURRET 162 
#define SPECIES_HOOTHOOT 163 
#define SPECIES_NOCTOWL 164 
#define SPECIES_LEDYBA 165 
#define SPECIES_LEDIAN 166 
#define SPECIES_SPINARAK 167 
#define SPECIES_ARIADOS 168 
#define SPECIES_CROBAT 169 
#define SPECIES_CHINCHOU 170 
#define SPECIES_LANTURN 171 
#define SPECIES_PICHU 172 
#define SPECIES_CLEFFA 173 
#define SPECIES_IGGLYBUFF 174 
#define SPECIES_TOGEPI 175 
#define SPECIES_TOGETIC 176 
#define SPECIES_NATU 177 
#define SPECIES_XATU 178 
#define SPECIES_MAREEP 179 
#define SPECIES_FLAAFFY 180 
#define SPECIES_AMPHAROS 181 
#define SPECIES_BELLOSSOM 182 
#define SPECIES_MARILL 183 
#define SPECIES_AZUMARILL 184 
#define SPECIES_SUDOWOODO 185 
#define SPECIES_POLITOED 186 
#define SPECIES_HOPPIP 187 
#define SPECIES_SKIPLOOM 188 
#define SPECIES_JUMPLUFF 189 
#define SPECIES_AIPOM 190 
#define SPECIES_SUNKERN 191 
#define SPECIES_SUNFLORA 192 
#define SPECIES_YANMA 193 
#define SPECIES_WOOPER 194 
#define SPECIES_QUAGSIRE 195 
#define SPECIES_ESPEON 196 
#define SPECIES_UMBREON 197 
#define SPECIES_MURKROW 198 
#define SPECIES_SLOWKING 199 
#define SPECIES_MISDREAVUS 200 
#define SPECIES_UNOWN 201 
#define SPECIES_WOBBUFFET 202 
#define SPECIES_GIRAFARIG 203 
#define SPECIES_PINECO 204 
#define SPECIES_FORRETRESS 205 
#define SPECIES_DUNSPARCE 206 
#define SPECIES_GLIGAR 207 
#define SPECIES_STEELIX 208 
#define SPECIES_SNUBBULL 209 
#define SPECIES_GRANBULL 210 
#define SPECIES_QWILFISH 211 
#define SPECIES_SCIZOR 212 
#define SPECIES_SHUCKLE 213 
#define SPECIES_HERACROSS 214 
#define SPECIES_SNEASEL 215 
#define SPECIES_TEDDIURSA 216 
#define SPECIES_URSARING 217 
#define SPECIES_SLUGMA 218 
#define SPECIES_MAGCARGO 219 
#define SPECIES_SWINUB 220 
#define SPECIES_PILOSWINE 221 
#define SPECIES_CORSOLA 222 
#define SPECIES_REMORAID 223 
#define SPECIES_OCTILLERY 224 
#define SPECIES_DELIBIRD 225 
#define SPECIES_MANTINE 226 
#define SPECIES_SKARMORY 227 
#define SPECIES_HOUNDOUR 228 
#define SPECIES_HOUNDOOM 229 
#define SPECIES_KINGDRA 230 
#define SPECIES_PHANPY 231 
#define SPECIES_DONPHAN 232 
#define SPECIES_PORYGON2 233 
#define SPECIES_STANTLER 234 
#define SPECIES_SMEARGLE 235 
#define SPECIES_TYROGUE 236 
#define SPECIES_HITMONTOP 237 
#define SPECIES_SMOOCHUM 238 
#define SPECIES_ELEKID 239 
#define SPECIES_MAGBY 240 
#define SPECIES_MILTANK 241 
#define SPECIES_BLISSEY 242 
#define SPECIES_RAIKOU 243 
#define SPECIES_ENTEI 244 
#define SPECIES_SUICUNE 245 
#define SPECIES_LARVITAR 246 
#define SPECIES_PUPITAR 247 
#define SPECIES_TYRANITAR 248 
#define SPECIES_LUGIA 249 
#define SPECIES_HO_OH 250 
#define SPECIES_CELEBI 251 
#define SPECIES_TREECKO 252 
#define SPECIES_GROVYLE 253 
#define SPECIES_SCEPTILE 254 
#define SPECIES_TORCHIC 255 
#define SPECIES_COMBUSKEN 256 
#define SPECIES_BLAZIKEN 257 
#define SPECIES_MUDKIP 258 
#define SPECIES_MARSHTOMP 259 
#define SPECIES_SWAMPERT 260 
#define SPECIES_POOCHYENA 261 
#define SPECIES_MIGHTYENA 262 
#define SPECIES_ZIGZAGOON 263 
#define SPECIES_LINOONE 264 
#define SPECIES_WURMPLE 265 
#define SPECIES_SILCOON 266 
#define SPECIES_BEAUTIFLY 267 
#define SPECIES_CASCOON 268 
#define SPECIES_DUSTOX 269 
#define SPECIES_LOTAD 270 
#define SPECIES_LOMBRE 271 
#define SPECIES_LUDICOLO 272 
#define SPECIES_SEEDOT 273 
#define SPECIES_NUZLEAF 274 
#define SPECIES_SHIFTRY 275 
#define SPECIES_TAILLOW 276 
#define SPECIES_SWELLOW 277 
#define SPECIES_WINGULL 278 
#define SPECIES_PELIPPER 279 
#define SPECIES_RALTS 280 
#define SPECIES_KIRLIA 281 
#define SPECIES_GARDEVOIR 282 
#define SPECIES_SURSKIT 283 
#define SPECIES_MASQUERAIN 284 
#define SPECIES_SHROOMISH 285 
#define SPECIES_BRELOOM 286 
#define SPECIES_SLAKOTH 287 
#define SPECIES_VIGOROTH 288 
#define SPECIES_SLAKING 289 
#define SPECIES_NINCADA 290 
#define SPECIES_NINJASK 291 
#define SPECIES_SHEDINJA 292 
#define SPECIES_WHISMUR 293 
#define SPECIES_LOUDRED 294 
#define SPECIES_EXPLOUD 295 
#define SPECIES_MAKUHITA 296 
#define SPECIES_HARIYAMA 297 
#define SPECIES_AZURILL 298 
#define SPECIES_NOSEPASS 299 
#define SPECIES_SKITTY 300 
#define SPECIES_DELCATTY 301 
#define SPECIES_SABLEYE 302 
#define SPECIES_MAWILE 303 
#define SPECIES_ARON 304 
#define SPECIES_LAIRON 305 
#define SPECIES_AGGRON 306 
#define SPECIES_MEDITITE 307 
#define SPECIES_MEDICHAM 308 
#define SPECIES_ELECTRIKE 309 
#define SPECIES_MANECTRIC 310 
#define SPECIES_PLUSLE 311 
#define SPECIES_MINUN 312 
#define SPECIES_VOLBEAT 313 
#define SPECIES_ILLUMISE 314 
#define SPECIES_ROSELIA 315 
#define SPECIES_GULPIN 316 
#define SPECIES_SWALOT 317 
#define SPECIES_CARVANHA 318 
#define SPECIES_SHARPEDO 319 
#define SPECIES_WAILMER 320 
#define SPECIES_WAILORD 321 
#define SPECIES_NUMEL 322 
#define SPECIES_CAMERUPT 323 
#define SPECIES_TORKOAL 324 
#define SPECIES_SPOINK 325 
#define SPECIES_GRUMPIG 326 
#define SPECIES_SPINDA 327 
#define SPECIES_TRAPINCH 328 
#define SPECIES_VIBRAVA 329 
#define SPECIES_FLYGON 330 
#define SPECIES_CACNEA 331 
#define SPECIES_CACTURNE 332 
#define SPECIES_SWABLU 333 
#define SPECIES_ALTARIA 334 
#define SPECIES_ZANGOOSE 335 
#define SPECIES_SEVIPER 336 
#define SPECIES_LUNATONE 337 
#define SPECIES_SOLROCK 338 
#define SPECIES_BARBOACH 339 
#define SPECIES_WHISCASH 340 
#define SPECIES_CORPHISH 341 
#define SPECIES_CRAWDAUNT 342 
#define SPECIES_BALTOY 343 
#define SPECIES_CLAYDOL 344 
#define SPECIES_LILEEP 345 
#define SPECIES_CRADILY 346 
#define SPECIES_ANORITH 347 
#define SPECIES_ARMALDO 348 
#define SPECIES_FEEBAS 349 
#define SPECIES_MILOTIC 350 
#define SPECIES_CASTFORM 351 
#define SPECIES_KECLEON 352 
#define SPECIES_SHUPPET 353 
#define SPECIES_BANETTE 354 
#define SPECIES_DUSKULL 355 
#define SPECIES_DUSCLOPS 356 
#define SPECIES_TROPIUS 357 
#define SPECIES_CHIMECHO 358 
#define SPECIES_ABSOL 359 
#define SPECIES_WYNAUT 360 
#define SPECIES_SNORUNT 361 
#define SPECIES_GLALIE 362 
#define SPECIES_SPHEAL 363 
#define SPECIES_SEALEO 364 
#define SPECIES_WALREIN 365 
#define SPECIES_CLAMPERL 366 
#define SPECIES_HUNTAIL 367 
#define SPECIES_GOREBYSS 368 
#define SPECIES_RELICANTH 369 
#define SPECIES_LUVDISC 370 
#define SPECIES_BAGON 371 
#define SPECIES_SHELGON 372 
#define SPECIES_SALAMENCE 373 
#define SPECIES_BELDUM 374 
#define SPECIES_METANG 375 
#define SPECIES_METAGROSS 376 
#define SPECIES_REGIROCK 377 
#define SPECIES_REGICE 378 
#define SPECIES_REGISTEEL 379 
#define SPECIES_LATIAS 380 
#define SPECIES_LATIOS 381 
#define SPECIES_KYOGRE 382 
#define SPECIES_GROUDON 383 
#define SPECIES_RAYQUAZA 384 
#define SPECIES_JIRACHI 385 
#define SPECIES_DEOXYS 386 

#define SPECIES_CHERUBI 387 
#define SPECIES_CHERRIM 388 
#define SPECIES_SHELLOS 389 
#define SPECIES_GASTRODON 390 
#define SPECIES_AMBIPOM 391 
#define SPECIES_DRIFLOON 392 
#define SPECIES_DRIFBLIM 393 
#define SPECIES_BUNEARY 394 
#define SPECIES_LOPUNNY 395 
#define SPECIES_MISMAGIUS 396 
#define SPECIES_HONCHKROW 397 
#define SPECIES_GLAMEOW 398 
#define SPECIES_PURUGLY 399 
#define SPECIES_CHINGLING 400 
#define SPECIES_STUNKY 401 
#define SPECIES_SKUNTANK 402 
#define SPECIES_BRONZOR 403 
#define SPECIES_BRONZONG 404 
#define SPECIES_BONSLY 405 
#define SPECIES_MIME_JR 406 
#define SPECIES_HAPPINY 407 
#define SPECIES_CHATOT 408 
#define SPECIES_SPIRITOMB 409 
#define SPECIES_GIBLE 410 
#define SPECIES_GABITE 411 
#define SPECIES_GARCHOMP 412 
#define SPECIES_MUNCHLAX 413 
#define SPECIES_RIOLU 414 
#define SPECIES_LUCARIO 415 
#define SPECIES_HIPPOPOTAS 416 
#define SPECIES_HIPPOWDON 417 
#define SPECIES_SKORUPI 418 
#define SPECIES_DRAPION 419 
#define SPECIES_CROAGUNK 420 
#define SPECIES_TOXICROAK 421 
#define SPECIES_CARNIVINE 422 
#define SPECIES_FINNEON 423 
#define SPECIES_LUMINEON 424 
#define SPECIES_MANTYKE 425 
#define SPECIES_SNOVER 426 
#define SPECIES_ABOMASNOW 427 
#define SPECIES_WEAVILE 428 
#define SPECIES_MAGNEZONE 429 
#define SPECIES_LICKILICKY 430 
#define SPECIES_RHYPERIOR 431 
#define SPECIES_TANGROWTH 432 
#define SPECIES_ELECTIVIRE 433 
#define SPECIES_MAGMORTAR 434 
#define SPECIES_TOGEKISS 435 
#define SPECIES_YANMEGA 436 
#define SPECIES_LEAFEON 437 
#define SPECIES_GLACEON 438 
#define SPECIES_GLISCOR 439 
#define SPECIES_MAMOSWINE 440 
#define SPECIES_PORYGON_Z 441 
#define SPECIES_GALLADE 442 
#define SPECIES_PROBOPASS 443 
#define SPECIES_DUSKNOIR 444 
#define SPECIES_FROSLASS 445 
#define SPECIES_ROTOM 446 
#define SPECIES_UXIE 447 
#define SPECIES_MESPRIT 448 
#define SPECIES_AZELF 449 
#define SPECIES_DIALGA 450 
#define SPECIES_PALKIA 451 
#define SPECIES_HEATRAN 452 
#define SPECIES_REGIGIGAS 453 
#define SPECIES_GIRATINA 454 
#define SPECIES_CRESSELIA 455 
#define SPECIES_PHIONE 456 
#define SPECIES_MANAPHY 457 
#define SPECIES_DARKRAI 458 
#define SPECIES_SHAYMIN 459 
#define SPECIES_ARCEUS 460 
#define SPECIES_VICTINI 461 
#define SPECIES_SNIVY 462 
#define SPECIES_SERVINE 463 
#define SPECIES_SERPERIOR 464 
#define SPECIES_TEPIG 465 
#define SPECIES_PIGNITE 466 
#define SPECIES_EMBOAR 467 
#define SPECIES_OSHAWOTT 468 
#define SPECIES_DEWOTT 469 
#define SPECIES_SAMUROTT 470 
#define SPECIES_PATRAT 471 
#define SPECIES_WATCHOG 472 
#define SPECIES_LILLIPUP 473 
#define SPECIES_HERDIER 474 
#define SPECIES_STOUTLAND 475 
#define SPECIES_PURRLOIN 476 
#define SPECIES_LIEPARD 477 
#define SPECIES_PANSAGE 478 
#define SPECIES_SIMISAGE 479 
#define SPECIES_PANSEAR 480 
#define SPECIES_SIMISEAR 481 
#define SPECIES_PANPOUR 482 
#define SPECIES_SIMIPOUR 483 
#define SPECIES_MUNNA 484 
#define SPECIES_MUSHARNA 485 
#define SPECIES_PIDOVE 486 
#define SPECIES_TRANQUILL 487 
#define SPECIES_UNFEZANT 488 
#define SPECIES_BLITZLE 489 
#define SPECIES_ZEBSTRIKA 490 
#define SPECIES_ROGGENROLA 491 
#define SPECIES_BOLDORE 492 
#define SPECIES_GIGALITH 493 
#define SPECIES_WOOBAT 494 
#define SPECIES_SWOOBAT 495 
#define SPECIES_DRILBUR 496 
#define SPECIES_EXCADRILL 497 
#define SPECIES_AUDINO 498 
#define SPECIES_TIMBURR 499 
#define SPECIES_GURDURR 500 
#define SPECIES_CONKELDURR 501 
#define SPECIES_TYMPOLE 502 
#define SPECIES_PALPITOAD 503 
#define SPECIES_SEISMITOAD 504 
#define SPECIES_THROH 505 
#define SPECIES_SAWK 506 
#define SPECIES_SEWADDLE 507 
#define SPECIES_SWADLOON 508 
#define SPECIES_LEAVANNY 509 
#define SPECIES_VENIPEDE 510 
#define SPECIES_WHIRLIPEDE 511 
#define SPECIES_SCOLIPEDE 512 
#define SPECIES_COTTONEE 513 
#define SPECIES_WHIMSICOTT 514 
#define SPECIES_PETILIL 515 
#define SPECIES_LILLIGANT 516 
#define SPECIES_BASCULIN 517 
#define SPECIES_SANDILE 518 
#define SPECIES_KROKOROK 519 
#define SPECIES_KROOKODILE 520 
#define SPECIES_DARUMAKA 521 
#define SPECIES_DARMANITAN 522 
#define SPECIES_MARACTUS 523 
#define SPECIES_DWEBBLE 524 
#define SPECIES_CRUSTLE 525 
#define SPECIES_SCRAGGY 526 
#define SPECIES_SCRAFTY 527 
#define SPECIES_SIGILYPH 528 
#define SPECIES_YAMASK 529 
#define SPECIES_COFAGRIGUS 530 
#define SPECIES_TIRTOUGA 531 
#define SPECIES_CARRACOSTA 532 
#define SPECIES_ARCHEN 533 
#define SPECIES_ARCHEOPS 534 
#define SPECIES_TRUBBISH 535 
#define SPECIES_GARBODOR 536 
#define SPECIES_ZORUA 537 
#define SPECIES_ZOROARK 538 
#define SPECIES_MINCCINO 539 
#define SPECIES_CINCCINO 540 
#define SPECIES_GOTHITA 541 
#define SPECIES_GOTHORITA 542 
#define SPECIES_GOTHITELLE 543 
#define SPECIES_SOLOSIS 544 
#define SPECIES_DUOSION 545 
#define SPECIES_REUNICLUS 546 
#define SPECIES_DUCKLETT 547 
#define SPECIES_SWANNA 548 
#define SPECIES_VANILLITE 549 
#define SPECIES_VANILLISH 550 
#define SPECIES_VANILLUXE 551 
#define SPECIES_DEERLING 552 
#define SPECIES_SAWSBUCK 553 
#define SPECIES_EMOLGA 554 
#define SPECIES_KARRABLAST 555 
#define SPECIES_ESCAVALIER 556 
#define SPECIES_FOONGUS 557 
#define SPECIES_AMOONGUSS 558 
#define SPECIES_FRILLISH 559 
#define SPECIES_JELLICENT 560 
#define SPECIES_ALOMOMOLA 561 
#define SPECIES_JOLTIK 562 
#define SPECIES_GALVANTULA 563 
#define SPECIES_FERROSEED 564 
#define SPECIES_FERROTHORN 565 
#define SPECIES_KLINK 566 
#define SPECIES_KLANG 567 
#define SPECIES_KLINKLANG 568 
#define SPECIES_TYNAMO 569 
#define SPECIES_EELEKTRIK 570 
#define SPECIES_EELEKTROSS 571 
#define SPECIES_ELGYEM 572 
#define SPECIES_BEHEEYEM 573 
#define SPECIES_LITWICK 574 
#define SPECIES_LAMPENT 575 
#define SPECIES_CHANDELURE 576 
#define SPECIES_AXEW 577 
#define SPECIES_FRAXURE 578 
#define SPECIES_HAXORUS 579 
#define SPECIES_CUBCHOO 580 
#define SPECIES_BEARTIC 581 
#define SPECIES_CRYOGONAL 582 
#define SPECIES_SHELMET 583 
#define SPECIES_ACCELGOR 584 
#define SPECIES_STUNFISK 585 
#define SPECIES_MIENFOO 586 
#define SPECIES_MIENSHAO 587 
#define SPECIES_DRUDDIGON 588 
#define SPECIES_GOLETT 589 
#define SPECIES_GOLURK 590 
#define SPECIES_PAWNIARD 591 
#define SPECIES_BISHARP 592 
#define SPECIES_BOUFFALANT 593 
#define SPECIES_RUFFLET 594 
#define SPECIES_BRAVIARY 595 
#define SPECIES_VULLABY 596 
#define SPECIES_MANDIBUZZ 597 
#define SPECIES_HEATMOR 598 
#define SPECIES_DURANT 599 
#define SPECIES_DEINO 600 
#define SPECIES_ZWEILOUS 601 
#define SPECIES_HYDREIGON 602 
#define SPECIES_LARVESTA 603 
#define SPECIES_VOLCARONA 604 
#define SPECIES_COBALION 605 
#define SPECIES_TERRAKION 606 
#define SPECIES_VIRIZION 607 
#define SPECIES_TORNADUS 608 
#define SPECIES_THUNDURUS 609 
#define SPECIES_RESHIRAM 610 
#define SPECIES_ZEKROM 611 
#define SPECIES_LANDORUS 612 
#define SPECIES_KYUREM 613 
#define SPECIES_KELDEO 614 
#define SPECIES_MELOETTA 615 
#define SPECIES_GENESECT 616 
#define SPECIES_CHESPIN 617 
#define SPECIES_QUILLADIN 618 
#define SPECIES_CHESNAUGHT 619 
#define SPECIES_FENNEKIN 620 
#define SPECIES_BRAIXEN 621 
#define SPECIES_DELPHOX 622 
#define SPECIES_FROAKIE 623 
#define SPECIES_FROGADIER 624 
#define SPECIES_GRENINJA 625 
#define SPECIES_BUNNELBY 626 
#define SPECIES_DIGGERSBY 627 
#define SPECIES_FLETCHLING 628 
#define SPECIES_FLETCHINDER 629 
#define SPECIES_TALONFLAME 630 
#define SPECIES_SCATTERBUG 631 
#define SPECIES_SPEWPA 632 
#define SPECIES_VIVILLON 633 // Icy Snow Pattern 
#define SPECIES_LITLEO 634 
#define SPECIES_PYROAR 635 
#define SPECIES_FLABEBE 636 // Red Flower 
#define SPECIES_FLOETTE 637 
#define SPECIES_FLORGES 638 
#define SPECIES_SKIDDO 639 
#define SPECIES_GOGOAT 640 
#define SPECIES_PANCHAM 641 
#define SPECIES_PANGORO 642 
#define SPECIES_FURFROU 643 
#define SPECIES_ESPURR 644 
#define SPECIES_MEOWSTIC 645 
#define SPECIES_HONEDGE 646 
#define SPECIES_DOUBLADE 647 
#define SPECIES_AEGISLASH 648 
#define SPECIES_SPRITZEE 649 
#define SPECIES_AROMATISSE 650 
#define SPECIES_SWIRLIX 651 
#define SPECIES_SLURPUFF 652 
#define SPECIES_INKAY 653 
#define SPECIES_MALAMAR 654 
#define SPECIES_BINACLE 655 
#define SPECIES_BARBARACLE 656 
#define SPECIES_SKRELP 657 
#define SPECIES_DRAGALGE 658 
#define SPECIES_CLAUNCHER 659 
#define SPECIES_CLAWITZER 660 
#define SPECIES_HELIOPTILE 661 
#define SPECIES_HELIOLISK 662 
#define SPECIES_TYRUNT 663 
#define SPECIES_TYRANTRUM 664 
#define SPECIES_AMAURA 665 
#define SPECIES_AURORUS 666 
#define SPECIES_SYLVEON 667 
#define SPECIES_HAWLUCHA 668 
#define SPECIES_DEDENNE 669 
#define SPECIES_CARBINK 670 
#define SPECIES_GOOMY 671 
#define SPECIES_SLIGGOO 672 
#define SPECIES_GOODRA 673 
#define SPECIES_KLEFKI 674 
#define SPECIES_PHANTUMP 675 
#define SPECIES_TREVENANT 676 
#define SPECIES_PUMPKABOO 677 
#define SPECIES_GOURGEIST 678 
#define SPECIES_BERGMITE 679 
#define SPECIES_AVALUGG 680 
#define SPECIES_NOIBAT 681 
#define SPECIES_NOIVERN 682 
#define SPECIES_XERNEAS 683 
#define SPECIES_YVELTAL 684 
#define SPECIES_ZYGARDE 685 
#define SPECIES_DIANCIE 686 
#define SPECIES_HOOPA 687 
#define SPECIES_VOLCANION 688 
#define SPECIES_ROWLET 689 
#define SPECIES_DARTRIX 690 
#define SPECIES_DECIDUEYE 691 
#define SPECIES_LITTEN 692 
#define SPECIES_TORRACAT 693 
#define SPECIES_INCINEROAR 694 
#define SPECIES_POPPLIO 695 
#define SPECIES_BRIONNE 696 
#define SPECIES_PRIMARINA 697 
#define SPECIES_PIKIPEK 698 
#define SPECIES_TRUMBEAK 699 
#define SPECIES_TOUCANNON 700 
#define SPECIES_YUNGOOS 701 
#define SPECIES_GUMSHOOS 702 
#define SPECIES_GRUBBIN 703 
#define SPECIES_CHARJABUG 704 
#define SPECIES_VIKAVOLT 705 
#define SPECIES_CRABRAWLER 706 
#define SPECIES_CRABOMINABLE 707 
#define SPECIES_ORICORIO 708 
#define SPECIES_CUTIEFLY 709 
#define SPECIES_RIBOMBEE 710 
#define SPECIES_ROCKRUFF 711 
#define SPECIES_LYCANROC 712 
#define SPECIES_WISHIWASHI 713 
#define SPECIES_MAREANIE 714 
#define SPECIES_TOXAPEX 715 
#define SPECIES_MUDBRAY 716 
#define SPECIES_MUDSDALE 717 
#define SPECIES_DEWPIDER 718 
#define SPECIES_ARAQUANID 719 
#define SPECIES_FOMANTIS 720 
#define SPECIES_LURANTIS 721 
#define SPECIES_MORELULL 722 
#define SPECIES_SHIINOTIC 723 
#define SPECIES_SALANDIT 724 
#define SPECIES_SALAZZLE 725 
#define SPECIES_STUFFUL 726 
#define SPECIES_BEWEAR 727 
#define SPECIES_BOUNSWEET 728 
#define SPECIES_STEENEE 729 
#define SPECIES_TSAREENA 730 
#define SPECIES_COMFEY 731 
#define SPECIES_ORANGURU 732 
#define SPECIES_PASSIMIAN 733 
#define SPECIES_WIMPOD 734 
#define SPECIES_GOLISOPOD 735 
#define SPECIES_SANDYGAST 736 
#define SPECIES_PALOSSAND 737 
#define SPECIES_PYUKUMUKU 738 
#define SPECIES_TYPE_NULL 739 
#define SPECIES_SILVALLY 740 
#define SPECIES_MINIOR 741 
#define SPECIES_KOMALA 742 
#define SPECIES_TURTONATOR 743 
#define SPECIES_TOGEDEMARU 744 
#define SPECIES_MIMIKYU 745 
#define SPECIES_BRUXISH 746 
#define SPECIES_DRAMPA 747 
#define SPECIES_DHELMISE 748 
#define SPECIES_JANGMO_O 749 
#define SPECIES_HAKAMO_O 750 
#define SPECIES_KOMMO_O 751 
#define SPECIES_TAPU_KOKO 752 
#define SPECIES_TAPU_LELE 753 
#define SPECIES_TAPU_BULU 754 
#define SPECIES_TAPU_FINI 755 
#define SPECIES_COSMOG 756 
#define SPECIES_COSMOEM 757 
#define SPECIES_SOLGALEO 758 
#define SPECIES_LUNALA 759 
#define SPECIES_NIHILEGO 760 
#define SPECIES_BUZZWOLE 761 
#define SPECIES_PHEROMOSA 762 
#define SPECIES_XURKITREE 763 
#define SPECIES_CELESTEELA 764 
#define SPECIES_KARTANA 765 
#define SPECIES_GUZZLORD 766 
#define SPECIES_NECROZMA 767 
#define SPECIES_MAGEARNA 768 
#define SPECIES_MARSHADOW 769 
#define SPECIES_POIPOLE 770 
#define SPECIES_NAGANADEL 771 
#define SPECIES_STAKATAKA 772 
#define SPECIES_BLACEPHALON 773 
#define SPECIES_ZERAORA 774 
#define SPECIES_MELTAN 775 
#define SPECIES_MELMETAL 776 
#define SPECIES_GROOKEY 777 
#define SPECIES_THWACKEY 778 
#define SPECIES_RILLABOOM 779 
#define SPECIES_SCORBUNNY 780 
#define SPECIES_RABOOT 781 
#define SPECIES_CINDERACE 782 
#define SPECIES_SOBBLE 783 
#define SPECIES_DRIZZILE 784 
#define SPECIES_INTELEON 785 
#define SPECIES_SKWOVET 786 
#define SPECIES_GREEDENT 787 
#define SPECIES_ROOKIDEE 788 
#define SPECIES_CORVISQUIRE 789 
#define SPECIES_CORVIKNIGHT 790 
#define SPECIES_BLIPBUG 791 
#define SPECIES_DOTTLER 792 
#define SPECIES_ORBEETLE 793 
#define SPECIES_NICKIT 794 
#define SPECIES_THIEVUL 795 
#define SPECIES_GOSSIFLEUR 796 
#define SPECIES_ELDEGOSS 797 
#define SPECIES_WOOLOO 798 
#define SPECIES_DUBWOOL 799 
#define SPECIES_CHEWTLE 800 
#define SPECIES_DREDNAW 801 
#define SPECIES_YAMPER 802 
#define SPECIES_BOLTUND 803 
#define SPECIES_ROLYCOLY 804 
#define SPECIES_CARKOL 805 
#define SPECIES_COALOSSAL 806 
#define SPECIES_APPLIN 807 
#define SPECIES_FLAPPLE 808 
#define SPECIES_APPLETUN 809 
#define SPECIES_SILICOBRA 810 
#define SPECIES_SANDACONDA 811 
#define SPECIES_CRAMORANT 812 
#define SPECIES_ARROKUDA 813 
#define SPECIES_BARRASKEWDA 814 
#define SPECIES_TOXEL 815 
#define SPECIES_TOXTRICITY 816 
#define SPECIES_SIZZLIPEDE 817 
#define SPECIES_CENTISKORCH 818 
#define SPECIES_CLOBBOPUS 819 
#define SPECIES_GRAPPLOCT 820 
#define SPECIES_SINISTEA 821 
#define SPECIES_POLTEAGEIST 822 
#define SPECIES_HATENNA 823 
#define SPECIES_HATTREM 824 
#define SPECIES_HATTERENE 825 
#define SPECIES_IMPIDIMP 826 
#define SPECIES_MORGREM 827 
#define SPECIES_GRIMMSNARL 828 
#define SPECIES_OBSTAGOON 829 
#define SPECIES_PERRSERKER 830 
#define SPECIES_CURSOLA 831 
#define SPECIES_SIRFETCHD 832 
#define SPECIES_MR_RIME 833 
#define SPECIES_RUNERIGUS 834 
#define SPECIES_MILCERY 835 
#define SPECIES_ALCREMIE 836 
#define SPECIES_FALINKS 837 
#define SPECIES_PINCURCHIN 838 
#define SPECIES_SNOM 839 
#define SPECIES_FROSMOTH 840 
#define SPECIES_STONJOURNER 841 
#define SPECIES_EISCUE 842 
#define SPECIES_INDEEDEE 843 
#define SPECIES_MORPEKO 844 
#define SPECIES_CUFANT 845 
#define SPECIES_COPPERAJAH 846 
#define SPECIES_DRACOZOLT 847 
#define SPECIES_ARCTOZOLT 848 
#define SPECIES_DRACOVISH 849 
#define SPECIES_ARCTOVISH 850 
#define SPECIES_DURALUDON 851 
#define SPECIES_DREEPY 852 
#define SPECIES_DRAKLOAK 853 
#define SPECIES_DRAGAPULT 854 
#define SPECIES_ZACIAN 855 
#define SPECIES_ZAMAZENTA 856 
#define SPECIES_ETERNATUS 857 
#define SPECIES_KUBFU 858 
#define SPECIES_URSHIFU 859 
#define SPECIES_ZARUDE 860 
#define SPECIES_REGIELEKI 861 
#define SPECIES_REGIDRAGO 862 
#define SPECIES_GLASTRIER 863 
#define SPECIES_SPECTRIER 864 
#define SPECIES_CALYREX 865 
#define SPECIES_WYRDEER 866 
#define SPECIES_KLEAVOR 867 
#define SPECIES_URSALUNA 868 
#define SPECIES_BASCULEGION 869 
#define SPECIES_SNEASLER 870 
#define SPECIES_OVERQWIL 871 
#define SPECIES_ENAMORUS 872 

#define NEW_MONS_START   (SPECIES_ENAMORUS + 1)

#define SPECIES_TIDPIT 873 
#define SPECIES_SLIDLOW 874 
#define SPECIES_CARDIOVOR 875 
#define SPECIES_FIEFREET 876 
#define SPECIES_BALBYRN 877 
#define SPECIES_BLAZIZAHAK 878 
#define SPECIES_PRONGY 879 
#define SPECIES_TRIDALIER 880 
#define SPECIES_TRITONAUT 881 
#define SPECIES_SNELFREND 882 
#define SPECIES_SYCOPLOD 883 
#define SPECIES_SYCOSTROM 884 
#define SPECIES_GUPSPAR 885 
#define SPECIES_VANGAR 886 
#define SPECIES_GHAERIAL 887 
#define SPECIES_QUILWARD 888 
#define SPECIES_BONFEU 889 
#define SPECIES_INFRAREC 890 
#define SPECIES_BERM 891 
#define SPECIES_MOODA 892 
#define SPECIES_BERMUDON 893 
#define SPECIES_MARINAROC 894 
#define SPECIES_METTATOLL 895 
#define SPECIES_ICKSQUEEK 896 
#define SPECIES_KOMORODE 897 
#define SPECIES_ANNIHILAPE 898 
#define SPECIES_EBIBI 899 
#define SPECIES_MAKIBI 900 
#define SPECIES_EBIROSASHI 901 
#define SPECIES_KITIKITI 902 
#define SPECIES_MOSKOPO 903 
#define SPECIES_ABSOLARIA 904 
#define SPECIES_KYUDI 905 
#define SPECIES_KOMBAKYU 906 
#define SPECIES_FLUFFSIR 907 
#define SPECIES_FLUFFREAR 908 
#define SPECIES_SAINTISOW 909 
#define SPECIES_SANCTISOW 910 
#define SPECIES_SOWPHIROTH 911 
#define SPECIES_TOXEXOT 912 
#define SPECIES_PSEUDRA 913 
#define SPECIES_MANDIMYTE 914 
#define SPECIES_TERMINYTE 915 
#define SPECIES_SNOTLOUD 916 
#define SPECIES_SICKBEAT 917 
#define SPECIES_SPRYTE 918 
#define SPECIES_GUMONA 919 
#define SPECIES_NANGGAL 920 
#define SPECIES_SHEEDRAKE 921 
#define SPECIES_TRANSERA 922 
#define SPECIES_BIVAGUE 923 
#define SPECIES_LUSCKAW 924 
#define SPECIES_SADSOD 925 
#define SPECIES_MAERACHOLY 926 
#define SPECIES_LUMELMO 927 
#define SPECIES_LUMENDELA 928 
#define SPECIES_STOMAWAY 929 
#define SPECIES_CRAWLAXY 930 
#define SPECIES_MAGNALURE 931 
#define SPECIES_MAGNANICOR 932 
#define SPECIES_CRYPLIN 933 
#define SPECIES_UHEFOE 934 
#define SPECIES_MYSTOMANIA 935 
#define SPECIES_LYORESA 936 
#define SPECIES_KODOUGH 937 
#define SPECIES_SLICKSLICE 938 
#define SPECIES_LOAFOOF 939 
#define SPECIES_SPIRITOAST 940 
#define SPECIES_HAPPEA 941 
#define SPECIES_COFFIDDLE 942 
#define SPECIES_CRAVERAVE 943 
#define SPECIES_FUZKY 944 
#define SPECIES_COOLMUTTE 945 
#define SPECIES_CREAM 946 
#define SPECIES_CREMELETTS 947 
#define SPECIES_SNURROWL 948 
#define SPECIES_STOLYCE 949 
#define SPECIES_DUDUNSPARS 950 
#define SPECIES_POMELONIAN 951 
#define SPECIES_GOURDOUG 952 
#define SPECIES_FOGGLEHIND 953 
#define SPECIES_MATCHLIT 954 
#define SPECIES_YAGANGRAN 955 
#define SPECIES_PIDIUM 956 
#define SPECIES_MEDGEON 957 
#define SPECIES_MAGGORDE 958 
#define SPECIES_FLAGUE 959 
#define SPECIES_CULTIPEX 960 
#define SPECIES_EERIKO 961 
#define SPECIES_MANNIKO 962 
#define SPECIES_KOWAKO 963 
#define SPECIES_UMBRAT 964 
#define SPECIES_CHIROBERRA 965 
#define SPECIES_WEROBERRA 966 
#define SPECIES_SACKYTWACK 967 
#define SPECIES_STRAWNGMAN 968 
#define SPECIES_LAWPARD 969 
#define SPECIES_OOHBAABA 970 
#define SPECIES_GOLDEROCK 971 
#define SPECIES_MAYNIMO 972 
#define SPECIES_BUTTERWEE 973 
#define SPECIES_PETRIPA 974 
#define SPECIES_CATTOWYRM 975 
#define SPECIES_BRAMBOOZLE 976 
#define SPECIES_HOAXPOCUS 977 
#define SPECIES_PITAGON 978 
#define SPECIES_PUTREGON 979 
#define SPECIES_GOLTIGATOR 980 
#define SPECIES_KAPRIKOLA 981 
#define SPECIES_BLOTTA 982 
#define SPECIES_SCHACHTTA 983 
#define SPECIES_SYLVREIGN 984 
#define SPECIES_CATTUCLID 985 
#define SPECIES_FRACTOFLY 986 
#define SPECIES_GRAVELITO 987 
#define SPECIES_MEGALITO 988 
#define SPECIES_COMBUN 989 
#define SPECIES_HAIBUN 990 
#define SPECIES_BURBUN 991 
#define SPECIES_INGBUN 992 
#define SPECIES_CHAFFAW 993 
#define SPECIES_FERROR 994 
#define SPECIES_COBBTLE 995 
#define SPECIES_MONTORT 996 
#define SPECIES_BOLTEROCK 997 
#define SPECIES_VOREON 998 
#define SPECIES_CORISP 999 
#define SPECIES_KROLPYRE 1000 
#define SPECIES_TOXITIDE 1001 
#define SPECIES_TOXITURF 1002 
#define SPECIES_PEBBLER 1003 
#define SPECIES_DUNEWICH 1004 
#define SPECIES_MAJADIJUNN 1005 
#define SPECIES_CAPYBARA 1006 
#define SPECIES_ABARBINASH 1007 
#define SPECIES_JARAMERA 1008 
#define SPECIES_BLINGUIN 1009 
#define SPECIES_BIYAKO 1010 
#define SPECIES_BEHEKO 1011 
#define SPECIES_HEMOKO 1012 
#define SPECIES_LEPUCYTE 1013 
#define SPECIES_LEUKUNEHO 1014 
#define SPECIES_WELPROOT 1015 
#define SPECIES_DRAEKAROT 1016 
#define SPECIES_KARODORAUG 1017 
#define SPECIES_COFORCHEE 1018 
#define SPECIES_MUSTYBANE 1019 
#define SPECIES_WANNEGG 1020 
#define SPECIES_EGGNEGGMA 1021 
#define SPECIES_LEVLADE 1022 
#define SPECIES_SHOCKORE 1023 
#define SPECIES_PLASMANTIS 1024 
#define SPECIES_HARACE 1025 
#define SPECIES_TORSTEVIC 1026 
#define SPECIES_CHIKA 1027 
#define SPECIES_SWORDUC 1028 
#define SPECIES_GOSMARK 1029 
#define SPECIES_CORDELICT 1030 
#define SPECIES_MERALCORE 1031 
#define SPECIES_RAITAIC 1032 
#define SPECIES_NIMBOZOA 1033 
#define SPECIES_MINOTE 1034 
#define SPECIES_TUNAP 1035 
#define SPECIES_BASSHARK 1036 
#define SPECIES_SHARGUY 1037 
#define SPECIES_SHARPREY 1038 
#define SPECIES_CHUNGRIM 1039 
#define SPECIES_SQUEESHY 1040 
#define SPECIES_SQUISHIME 1041 
#define SPECIES_OCTOHIME 1042 
#define SPECIES_COLFIN 1043 
#define SPECIES_MYSTICIAN 1044 
#define SPECIES_WALRUST 1045 
#define SPECIES_SCALLYWARG 1046 
#define SPECIES_WAARGH 1047 
#define SPECIES_SKELLYWARG 1048 
#define SPECIES_CASOWARY 1049 
#define SPECIES_PASSAWARY 1050 
#define SPECIES_BOOZARD 1051 
#define SPECIES_COCKABOO 1052 
#define SPECIES_AXELFIN 1053 
#define SPECIES_MORAGAN 1054 
#define SPECIES_SHIVERSNAP 1055 
#define SPECIES_EXCATATOR 1056 
#define SPECIES_MARSOYART 1057 
#define SPECIES_CINDRILLON 1058 
#define SPECIES_ARMAGATTON 1059 
#define SPECIES_FAKYSNAKY 1060 
#define SPECIES_PANTNEY 1061 
#define SPECIES_NYARLY 1062 
#define SPECIES_SUDCUB 1063 
#define SPECIES_TARDRITCH 1064 
#define SPECIES_BLABBU 1065 
#define SPECIES_TURRYTURRY 1066 
#define SPECIES_FAERED 1067 
#define SPECIES_PROMISCBUS 1068 
#define SPECIES_GUMBORREE 1069 
#define SPECIES_KOREMAI 1070 
#define SPECIES_KORESATO 1071 
#define SPECIES_DRAKULARK 1072 
#define SPECIES_NOSFERAPTR 1073 
#define SPECIES_OLFLOOKIE 1074 
#define SPECIES_JUSTRICHA 1075 
#define SPECIES_AJOKUJOKU 1076 
#define SPECIES_GARJIRA 1077 
#define SPECIES_GARZILLA 1078 
#define SPECIES_YANDEMIC 1079 
#define SPECIES_LUNASTER 1080 
#define SPECIES_JACKABOX 1081 
#define SPECIES_FOOLTAGE 1082 
#define SPECIES_AETHEREAL 1083 
#define SPECIES_MOTHRAMITY 1084 
#define SPECIES_GLAREYALE 1085 
#define SPECIES_LEVIALAGO 1086 
#define SPECIES_RETROROACH 1087 
#define SPECIES_NEOROACH 1088 
#define SPECIES_SPITFAX 1089 
#define SPECIES_RAPSCALEON 1090 
#define SPECIES_AGOMAGO 1091 
#define SPECIES_MORFTREE 1092 
#define SPECIES_EPOCHOTL 1093 
#define SPECIES_VIVISU 1094 
#define SPECIES_SOLASU 1095 
#define SPECIES_SUMMERASU 1096 
#define SPECIES_OROFLOW 1097 
#define SPECIES_ORROCAST 1098 
#define SPECIES_ORROWHELM 1099 
#define SPECIES_SHAYON 1100 
#define SPECIES_LUOSHAN 1101 
#define SPECIES_LOTTABATS 1102
#define SPECIES_GAOTERRA 1103
#define SPECIES_BISHOUCHA 1104
#define SPECIES_PAPYPUS 1105
#define SPECIES_SHISHIMA 1106
#define SPECIES_SHUNYONG 1107
#define SPECIES_KINGAMBIT 1108
#define SPECIES_SHELLYLOUH 1109
#define SPECIES_INFAIRNO 1110
#define SPECIES_PURGATIVAL 1111
#define SPECIES_DETERIOTL 1112
#define SPECIES_DAKKAPOD 1113
#define SPECIES_UNBERRABLE 1114
#define SPECIES_PEBLRANIUM 1115
#define SPECIES_VAIKING 1116
#define SPECIES_YOLKWEEN 1117
#define SPECIES_WALLY 1118
#define SPECIES_POTTRICIA 1119

#define NEW_MONS_END (SPECIES_POTTRICIA)
#define NUM_NEW_MONS (NEW_MONS_END - NEW_MONS_START)
// Megas
#define SPECIES_VENUSAUR_MEGA FORMS_START + 1 
#define SPECIES_CHARIZARD_MEGA_X FORMS_START + 2 
#define SPECIES_CHARIZARD_MEGA_Y FORMS_START + 3 
#define SPECIES_BLASTOISE_MEGA FORMS_START + 4 
#define SPECIES_BEEDRILL_MEGA FORMS_START + 5 
#define SPECIES_PIDGEOT_MEGA FORMS_START + 6 
#define SPECIES_ALAKAZAM_MEGA FORMS_START + 7 
#define SPECIES_SLOWBRO_MEGA FORMS_START + 8 
#define SPECIES_GENGAR_MEGA FORMS_START + 9 
#define SPECIES_KANGASKHAN_MEGA FORMS_START + 10 
#define SPECIES_PINSIR_MEGA FORMS_START + 11 
#define SPECIES_GYARADOS_MEGA FORMS_START + 12 
#define SPECIES_AERODACTYL_MEGA FORMS_START + 13 
#define SPECIES_MEWTWO_MEGA_X FORMS_START + 14 
#define SPECIES_MEWTWO_MEGA_Y FORMS_START + 15 
#define SPECIES_AMPHAROS_MEGA FORMS_START + 16 
#define SPECIES_STEELIX_MEGA FORMS_START + 17 
#define SPECIES_SCIZOR_MEGA FORMS_START + 18 
#define SPECIES_HERACROSS_MEGA FORMS_START + 19 
#define SPECIES_HOUNDOOM_MEGA FORMS_START + 20 
#define SPECIES_TYRANITAR_MEGA FORMS_START + 21 
#define SPECIES_SCEPTILE_MEGA FORMS_START + 22 
#define SPECIES_BLAZIKEN_MEGA FORMS_START + 23 
#define SPECIES_SWAMPERT_MEGA FORMS_START + 24 
#define SPECIES_GARDEVOIR_MEGA FORMS_START + 25 
#define SPECIES_SABLEYE_MEGA FORMS_START + 26 
#define SPECIES_MAWILE_MEGA FORMS_START + 27 
#define SPECIES_AGGRON_MEGA FORMS_START + 28 
#define SPECIES_MEDICHAM_MEGA FORMS_START + 29 
#define SPECIES_MANECTRIC_MEGA FORMS_START + 30 
#define SPECIES_SHARPEDO_MEGA FORMS_START + 31 
#define SPECIES_CAMERUPT_MEGA FORMS_START + 32 
#define SPECIES_ALTARIA_MEGA FORMS_START + 33 
#define SPECIES_BANETTE_MEGA FORMS_START + 34 
#define SPECIES_ABSOL_MEGA FORMS_START + 35 
#define SPECIES_GLALIE_MEGA FORMS_START + 36 
#define SPECIES_SALAMENCE_MEGA FORMS_START + 37 
#define SPECIES_METAGROSS_MEGA FORMS_START + 38 
#define SPECIES_LATIAS_MEGA FORMS_START + 39 
#define SPECIES_LATIOS_MEGA FORMS_START + 40 
#define SPECIES_LOPUNNY_MEGA FORMS_START + 41 
#define SPECIES_GARCHOMP_MEGA FORMS_START + 42 
#define SPECIES_LUCARIO_MEGA FORMS_START + 43 
#define SPECIES_ABOMASNOW_MEGA FORMS_START + 44 
#define SPECIES_GALLADE_MEGA FORMS_START + 45 
#define SPECIES_AUDINO_MEGA FORMS_START + 46 
#define SPECIES_DIANCIE_MEGA FORMS_START + 47 

// Special Mega + Primals
#define SPECIES_RAYQUAZA_MEGA FORMS_START + 48 
#define SPECIES_KYOGRE_PRIMAL FORMS_START + 49 
#define SPECIES_GROUDON_PRIMAL FORMS_START + 50 

// Alolan Forms
#define SPECIES_RATTATA_ALOLAN FORMS_START + 51 
#define SPECIES_RATICATE_ALOLAN FORMS_START + 52 
#define SPECIES_RAICHU_ALOLAN FORMS_START + 53 
#define SPECIES_SANDSHREW_ALOLAN FORMS_START + 54 
#define SPECIES_SANDSLASH_ALOLAN FORMS_START + 55 
#define SPECIES_VULPIX_ALOLAN FORMS_START + 56 
#define SPECIES_NINETALES_ALOLAN FORMS_START + 57 
#define SPECIES_DIGLETT_ALOLAN FORMS_START + 58 
#define SPECIES_DUGTRIO_ALOLAN FORMS_START + 59 
#define SPECIES_MEOWTH_ALOLAN FORMS_START + 60 
#define SPECIES_PERSIAN_ALOLAN FORMS_START + 61 
#define SPECIES_GEODUDE_ALOLAN FORMS_START + 62 
#define SPECIES_GRAVELER_ALOLAN FORMS_START + 63 
#define SPECIES_GOLEM_ALOLAN FORMS_START + 64 
#define SPECIES_GRIMER_ALOLAN FORMS_START + 65 
#define SPECIES_MUK_ALOLAN FORMS_START + 66 
#define SPECIES_EXEGGUTOR_ALOLAN FORMS_START + 67 
#define SPECIES_MAROWAK_ALOLAN FORMS_START + 68 

// Galarian Forms
#define SPECIES_MEOWTH_GALARIAN FORMS_START + 69 
#define SPECIES_PONYTA_GALARIAN FORMS_START + 70 
#define SPECIES_RAPIDASH_GALARIAN FORMS_START + 71 
#define SPECIES_SLOWPOKE_GALARIAN FORMS_START + 72 
#define SPECIES_SLOWBRO_GALARIAN FORMS_START + 73 
#define SPECIES_FARFETCHD_GALARIAN FORMS_START + 74 
#define SPECIES_WEEZING_GALARIAN FORMS_START + 75 
#define SPECIES_MR_MIME_GALARIAN FORMS_START + 76 
#define SPECIES_ARTICUNO_GALARIAN FORMS_START + 77 
#define SPECIES_ZAPDOS_GALARIAN FORMS_START + 78 
#define SPECIES_MOLTRES_GALARIAN FORMS_START + 79 
#define SPECIES_SLOWKING_GALARIAN FORMS_START + 80 
#define SPECIES_CORSOLA_GALARIAN FORMS_START + 81 
#define SPECIES_ZIGZAGOON_GALARIAN FORMS_START + 82 
#define SPECIES_LINOONE_GALARIAN FORMS_START + 83 
#define SPECIES_DARUMAKA_GALARIAN FORMS_START + 84 
#define SPECIES_DARMANITAN_GALARIAN FORMS_START + 85 
#define SPECIES_YAMASK_GALARIAN FORMS_START + 86 
#define SPECIES_STUNFISK_GALARIAN FORMS_START + 87 

//Hisuian Forms
#define SPECIES_GROWLITHE_HISUIAN FORMS_START + 88 
#define SPECIES_ARCANINE_HISUIAN FORMS_START + 89 
#define SPECIES_VOLTORB_HISUIAN FORMS_START + 90 
#define SPECIES_ELECTRODE_HISUIAN FORMS_START + 91 
#define SPECIES_TYPHLOSION_HISUIAN FORMS_START + 92 
#define SPECIES_QWILFISH_HISUIAN FORMS_START + 93 
#define SPECIES_SNEASEL_HISUIAN FORMS_START + 94 
#define SPECIES_SAMUROTT_HISUIAN FORMS_START + 95 
#define SPECIES_LILLIGANT_HISUIAN FORMS_START + 96 
#define SPECIES_ZORUA_HISUIAN FORMS_START + 97 
#define SPECIES_ZOROARK_HISUIAN FORMS_START + 98 
#define SPECIES_BRAVIARY_HISUIAN FORMS_START + 99 
#define SPECIES_SLIGGOO_HISUIAN FORMS_START + 100 
#define SPECIES_GOODRA_HISUIAN FORMS_START + 101 
#define SPECIES_AVALUGG_HISUIAN FORMS_START + 102 
#define SPECIES_DECIDUEYE_HISUIAN FORMS_START + 103 

// Misc Forms

// Cosplay Pikachu
#define SPECIES_PIKACHU_COSPLAY FORMS_START + 104 
#define SPECIES_PIKACHU_ROCK_STAR FORMS_START + 105 
#define SPECIES_PIKACHU_BELLE FORMS_START + 106 
#define SPECIES_PIKACHU_POP_STAR FORMS_START + 107 
#define SPECIES_PIKACHU_PH_D FORMS_START + 108 
#define SPECIES_PIKACHU_LIBRE FORMS_START + 109 

// Cap Pikachu
#define SPECIES_PIKACHU_ORIGINAL_CAP FORMS_START + 110 
#define SPECIES_PIKACHU_HOENN_CAP FORMS_START + 111 
#define SPECIES_PIKACHU_SINNOH_CAP FORMS_START + 112 
#define SPECIES_PIKACHU_UNOVA_CAP FORMS_START + 113 
#define SPECIES_PIKACHU_KALOS_CAP FORMS_START + 114 
#define SPECIES_PIKACHU_ALOLA_CAP FORMS_START + 115 
#define SPECIES_PIKACHU_PARTNER_CAP FORMS_START + 116 
#define SPECIES_PIKACHU_WORLD_CAP FORMS_START + 117 

// Pichu
#define SPECIES_PICHU_SPIKY_EARED FORMS_START + 118 

// Unown
#define SPECIES_UNOWN_B FORMS_START + 119 
#define SPECIES_UNOWN_C FORMS_START + 120 
#define SPECIES_UNOWN_D FORMS_START + 121 
#define SPECIES_UNOWN_E FORMS_START + 122 
#define SPECIES_UNOWN_F FORMS_START + 123 
#define SPECIES_UNOWN_G FORMS_START + 124 
#define SPECIES_UNOWN_H FORMS_START + 125 
#define SPECIES_UNOWN_I FORMS_START + 126 
#define SPECIES_UNOWN_J FORMS_START + 127 
#define SPECIES_UNOWN_K FORMS_START + 128 
#define SPECIES_UNOWN_L FORMS_START + 129 
#define SPECIES_UNOWN_M FORMS_START + 130 
#define SPECIES_UNOWN_N FORMS_START + 131 
#define SPECIES_UNOWN_O FORMS_START + 132 
#define SPECIES_UNOWN_P FORMS_START + 133 
#define SPECIES_UNOWN_Q FORMS_START + 134 
#define SPECIES_UNOWN_R FORMS_START + 135 
#define SPECIES_UNOWN_S FORMS_START + 136 
#define SPECIES_UNOWN_T FORMS_START + 137 
#define SPECIES_UNOWN_U FORMS_START + 138 
#define SPECIES_UNOWN_V FORMS_START + 139 
#define SPECIES_UNOWN_W FORMS_START + 140 
#define SPECIES_UNOWN_X FORMS_START + 141 
#define SPECIES_UNOWN_Y FORMS_START + 142 
#define SPECIES_UNOWN_Z FORMS_START + 143 
#define SPECIES_UNOWN_EMARK FORMS_START + 144 
#define SPECIES_UNOWN_QMARK FORMS_START + 145 

// Castform
#define SPECIES_CASTFORM_SUNNY FORMS_START + 146 
#define SPECIES_CASTFORM_RAINY FORMS_START + 147 
#define SPECIES_CASTFORM_SNOWY FORMS_START + 148 

// Deoxys
#define SPECIES_DEOXYS_ATTACK FORMS_START + 149 
#define SPECIES_DEOXYS_DEFENSE FORMS_START + 150 
#define SPECIES_DEOXYS_SPEED FORMS_START + 151 

// Cherrim
#define SPECIES_CHERRIM_SUNSHINE FORMS_START + 152 

// Shellos
#define SPECIES_SHELLOS_EAST_SEA FORMS_START + 153 

// Gastrodon
#define SPECIES_GASTRODON_EAST_SEA FORMS_START + 154 

// Rotom
#define SPECIES_ROTOM_HEAT FORMS_START + 155 
#define SPECIES_ROTOM_WASH FORMS_START + 156 
#define SPECIES_ROTOM_FROST FORMS_START + 157 
#define SPECIES_ROTOM_FAN FORMS_START + 158 
#define SPECIES_ROTOM_MOW FORMS_START + 159 

// Origin Forme
#define SPECIES_DIALGA_ORIGIN FORMS_START + 160 
#define SPECIES_PALKIA_ORIGIN FORMS_START + 161 
#define SPECIES_GIRATINA_ORIGIN FORMS_START + 162 

// Shaymin
#define SPECIES_SHAYMIN_SKY FORMS_START + 163 

// Arceus
#define SPECIES_ARCEUS_FIGHTING FORMS_START + 164 
#define SPECIES_ARCEUS_FLYING FORMS_START + 165 
#define SPECIES_ARCEUS_POISON FORMS_START + 166 
#define SPECIES_ARCEUS_GROUND FORMS_START + 167 
#define SPECIES_ARCEUS_ROCK FORMS_START + 168 
#define SPECIES_ARCEUS_BUG FORMS_START + 169 
#define SPECIES_ARCEUS_GHOST FORMS_START + 170 
#define SPECIES_ARCEUS_STEEL FORMS_START + 171 
#define SPECIES_ARCEUS_FIRE FORMS_START + 172 
#define SPECIES_ARCEUS_WATER FORMS_START + 173 
#define SPECIES_ARCEUS_GRASS FORMS_START + 174 
#define SPECIES_ARCEUS_ELECTRIC FORMS_START + 175 
#define SPECIES_ARCEUS_PSYCHIC FORMS_START + 176 
#define SPECIES_ARCEUS_ICE FORMS_START + 177 
#define SPECIES_ARCEUS_DRAGON FORMS_START + 178 
#define SPECIES_ARCEUS_DARK FORMS_START + 179 
#define SPECIES_ARCEUS_FAIRY FORMS_START + 180 

// Basculin
#define SPECIES_BASCULIN_BLUE_STRIPED FORMS_START + 181 
#define SPECIES_BASCULIN_WHITE_STRIPED FORMS_START + 182 

// Darmanitan
#define SPECIES_DARMANITAN_ZEN_MODE FORMS_START + 183 
#define SPECIES_DARMANITAN_ZEN_MODE_GALARIAN FORMS_START + 184 

// Deerling
#define SPECIES_DEERLING_SUMMER FORMS_START + 185 
#define SPECIES_DEERLING_AUTUMN FORMS_START + 186 
#define SPECIES_DEERLING_WINTER FORMS_START + 187 

// Sawsbuck
#define SPECIES_SAWSBUCK_SUMMER FORMS_START + 188 
#define SPECIES_SAWSBUCK_AUTUMN FORMS_START + 189 
#define SPECIES_SAWSBUCK_WINTER FORMS_START + 190 

// Therian Forms
#define SPECIES_TORNADUS_THERIAN FORMS_START + 191 
#define SPECIES_THUNDURUS_THERIAN FORMS_START + 192 
#define SPECIES_LANDORUS_THERIAN FORMS_START + 193 
#define SPECIES_ENAMORUS_THERIAN FORMS_START + 194 

// Kyurem
#define SPECIES_KYUREM_WHITE FORMS_START + 195 
#define SPECIES_KYUREM_BLACK FORMS_START + 196 

// Keldeo
#define SPECIES_KELDEO_RESOLUTE FORMS_START + 197 

// Meloetta
#define SPECIES_MELOETTA_PIROUETTE FORMS_START + 198 

// Genesect
#define SPECIES_GENESECT_DOUSE_DRIVE FORMS_START + 199 
#define SPECIES_GENESECT_SHOCK_DRIVE FORMS_START + 200 
#define SPECIES_GENESECT_BURN_DRIVE FORMS_START + 201 
#define SPECIES_GENESECT_CHILL_DRIVE FORMS_START + 202 

// Greninja
#define SPECIES_GRENINJA_BATTLE_BOND FORMS_START + 203 
#define SPECIES_GRENINJA_ASH FORMS_START + 204 

// Vivillon
#define SPECIES_VIVILLON_POLAR FORMS_START + 205 
#define SPECIES_VIVILLON_TUNDRA FORMS_START + 206 
#define SPECIES_VIVILLON_CONTINENTAL FORMS_START + 207 
#define SPECIES_VIVILLON_GARDEN FORMS_START + 208 
#define SPECIES_VIVILLON_ELEGANT FORMS_START + 209 
#define SPECIES_VIVILLON_MEADOW FORMS_START + 210 
#define SPECIES_VIVILLON_MODERN FORMS_START + 211 
#define SPECIES_VIVILLON_MARINE FORMS_START + 212 
#define SPECIES_VIVILLON_ARCHIPELAGO FORMS_START + 213 
#define SPECIES_VIVILLON_HIGH_PLAINS FORMS_START + 214 
#define SPECIES_VIVILLON_SANDSTORM FORMS_START + 215 
#define SPECIES_VIVILLON_RIVER FORMS_START + 216 
#define SPECIES_VIVILLON_MONSOON FORMS_START + 217 
#define SPECIES_VIVILLON_SAVANNA FORMS_START + 218 
#define SPECIES_VIVILLON_SUN FORMS_START + 219 
#define SPECIES_VIVILLON_OCEAN FORMS_START + 220 
#define SPECIES_VIVILLON_JUNGLE FORMS_START + 221 
#define SPECIES_VIVILLON_FANCY FORMS_START + 222 
#define SPECIES_VIVILLON_POKE_BALL FORMS_START + 223 

// Flabébé
#define SPECIES_FLABEBE_YELLOW_FLOWER FORMS_START + 224 
#define SPECIES_FLABEBE_ORANGE_FLOWER FORMS_START + 225 
#define SPECIES_FLABEBE_BLUE_FLOWER FORMS_START + 226 
#define SPECIES_FLABEBE_WHITE_FLOWER FORMS_START + 227 

// Floette
#define SPECIES_FLOETTE_YELLOW_FLOWER FORMS_START + 228 
#define SPECIES_FLOETTE_ORANGE_FLOWER FORMS_START + 229 
#define SPECIES_FLOETTE_BLUE_FLOWER FORMS_START + 230 
#define SPECIES_FLOETTE_WHITE_FLOWER FORMS_START + 231 
#define SPECIES_FLOETTE_ETERNAL_FLOWER FORMS_START + 232 

// Florges
#define SPECIES_FLORGES_YELLOW_FLOWER FORMS_START + 233 
#define SPECIES_FLORGES_ORANGE_FLOWER FORMS_START + 234 
#define SPECIES_FLORGES_BLUE_FLOWER FORMS_START + 235 
#define SPECIES_FLORGES_WHITE_FLOWER FORMS_START + 236 

// Furfrou
#define SPECIES_FURFROU_HEART_TRIM FORMS_START + 237 
#define SPECIES_FURFROU_STAR_TRIM FORMS_START + 238 
#define SPECIES_FURFROU_DIAMOND_TRIM FORMS_START + 239 
#define SPECIES_FURFROU_DEBUTANTE_TRIM FORMS_START + 240 
#define SPECIES_FURFROU_MATRON_TRIM FORMS_START + 241 
#define SPECIES_FURFROU_DANDY_TRIM FORMS_START + 242 
#define SPECIES_FURFROU_LA_REINE_TRIM FORMS_START + 243 
#define SPECIES_FURFROU_KABUKI_TRIM FORMS_START + 244 
#define SPECIES_FURFROU_PHARAOH_TRIM FORMS_START + 245 

// Meowstic
#define SPECIES_MEOWSTIC_FEMALE FORMS_START + 246 

// Aegislash
#define SPECIES_AEGISLASH_BLADE FORMS_START + 247 

// Pumpkaboo
#define SPECIES_PUMPKABOO_SMALL FORMS_START + 248 
#define SPECIES_PUMPKABOO_LARGE FORMS_START + 249 
#define SPECIES_PUMPKABOO_SUPER FORMS_START + 250 

// Gourgeist
#define SPECIES_GOURGEIST_SMALL FORMS_START + 251 
#define SPECIES_GOURGEIST_LARGE FORMS_START + 252 
#define SPECIES_GOURGEIST_SUPER FORMS_START + 253 

// Xerneas
#define SPECIES_XERNEAS_ACTIVE FORMS_START + 254 

// Zygarde
#define SPECIES_ZYGARDE_10 FORMS_START + 255 
#define SPECIES_ZYGARDE_10_DORMANT FORMS_START + 256 
#define SPECIES_ZYGARDE_50_DORMANT FORMS_START + 257 
#define SPECIES_ZYGARDE_COMPLETE FORMS_START + 258 

// Hoopa
#define SPECIES_HOOPA_UNBOUND FORMS_START + 259 

// Oricorio
#define SPECIES_ORICORIO_POM_POM FORMS_START + 260 
#define SPECIES_ORICORIO_PAU FORMS_START + 261 
#define SPECIES_ORICORIO_SENSU FORMS_START + 262 

// Rockruff
#define SPECIES_ROCKRUFF_OWN_TEMPO FORMS_START + 263 

// Lycanroc
#define SPECIES_LYCANROC_MIDNIGHT FORMS_START + 264 
#define SPECIES_LYCANROC_DUSK FORMS_START + 265 

// Wishiwashi
#define SPECIES_WISHIWASHI_SCHOOL FORMS_START + 266 

// Silvally
#define SPECIES_SILVALLY_FIGHTING FORMS_START + 267 
#define SPECIES_SILVALLY_FLYING FORMS_START + 268 
#define SPECIES_SILVALLY_POISON FORMS_START + 269 
#define SPECIES_SILVALLY_GROUND FORMS_START + 270 
#define SPECIES_SILVALLY_ROCK FORMS_START + 271 
#define SPECIES_SILVALLY_BUG FORMS_START + 272 
#define SPECIES_SILVALLY_GHOST FORMS_START + 273 
#define SPECIES_SILVALLY_STEEL FORMS_START + 274 
#define SPECIES_SILVALLY_FIRE FORMS_START + 275 
#define SPECIES_SILVALLY_WATER FORMS_START + 276 
#define SPECIES_SILVALLY_GRASS FORMS_START + 277 
#define SPECIES_SILVALLY_ELECTRIC FORMS_START + 278 
#define SPECIES_SILVALLY_PSYCHIC FORMS_START + 279 
#define SPECIES_SILVALLY_ICE FORMS_START + 280 
#define SPECIES_SILVALLY_DRAGON FORMS_START + 281 
#define SPECIES_SILVALLY_DARK FORMS_START + 282 
#define SPECIES_SILVALLY_FAIRY FORMS_START + 283 

// Minior
#define SPECIES_MINIOR_METEOR_ORANGE FORMS_START + 284 
#define SPECIES_MINIOR_METEOR_YELLOW FORMS_START + 285 
#define SPECIES_MINIOR_METEOR_GREEN FORMS_START + 286 
#define SPECIES_MINIOR_METEOR_BLUE FORMS_START + 287 
#define SPECIES_MINIOR_METEOR_INDIGO FORMS_START + 288 
#define SPECIES_MINIOR_METEOR_VIOLET FORMS_START + 289 
#define SPECIES_MINIOR_CORE_RED FORMS_START + 290 
#define SPECIES_MINIOR_CORE_ORANGE FORMS_START + 291 
#define SPECIES_MINIOR_CORE_YELLOW FORMS_START + 292 
#define SPECIES_MINIOR_CORE_GREEN FORMS_START + 293 
#define SPECIES_MINIOR_CORE_BLUE FORMS_START + 294 
#define SPECIES_MINIOR_CORE_INDIGO FORMS_START + 295 
#define SPECIES_MINIOR_CORE_VIOLET FORMS_START + 296 

// Mimikyu
#define SPECIES_MIMIKYU_BUSTED FORMS_START + 297 

// Necrozma
#define SPECIES_NECROZMA_DUSK_MANE FORMS_START + 298 
#define SPECIES_NECROZMA_DAWN_WINGS FORMS_START + 299 
#define SPECIES_NECROZMA_ULTRA FORMS_START + 300 

// Magearna
#define SPECIES_MAGEARNA_ORIGINAL_COLOR FORMS_START + 301 

// Cramorant
#define SPECIES_CRAMORANT_GULPING FORMS_START + 302 
#define SPECIES_CRAMORANT_GORGING FORMS_START + 303 

// Toxtricity
#define SPECIES_TOXTRICITY_LOW_KEY FORMS_START + 304 

// Sinistea
#define SPECIES_SINISTEA_ANTIQUE FORMS_START + 305 

// Polteageist
#define SPECIES_POLTEAGEIST_ANTIQUE FORMS_START + 306 

// Alcremie
#define SPECIES_ALCREMIE_RUBY_CREAM FORMS_START + 307 
#define SPECIES_ALCREMIE_MATCHA_CREAM FORMS_START + 308 
#define SPECIES_ALCREMIE_MINT_CREAM FORMS_START + 309 
#define SPECIES_ALCREMIE_LEMON_CREAM FORMS_START + 310 
#define SPECIES_ALCREMIE_SALTED_CREAM FORMS_START + 311 
#define SPECIES_ALCREMIE_RUBY_SWIRL FORMS_START + 312 
#define SPECIES_ALCREMIE_CARAMEL_SWIRL FORMS_START + 313 
#define SPECIES_ALCREMIE_RAINBOW_SWIRL FORMS_START + 314 

// Eiscue
#define SPECIES_EISCUE_NOICE_FACE FORMS_START + 315 

// Indeedee
#define SPECIES_INDEEDEE_FEMALE FORMS_START + 316 

// Morpeko
#define SPECIES_MORPEKO_HANGRY FORMS_START + 317 

// Zacian
#define SPECIES_ZACIAN_CROWNED_SWORD FORMS_START + 318 

// Zamazenta
#define SPECIES_ZAMAZENTA_CROWNED_SHIELD FORMS_START + 319 

// Eternatus
#define SPECIES_ETERNATUS_ETERNAMAX FORMS_START + 320 

// Urshifu
#define SPECIES_URSHIFU_RAPID_STRIKE_STYLE FORMS_START + 321 

// Zarude
#define SPECIES_ZARUDE_DADA FORMS_START + 322 

// Calyrex
#define SPECIES_CALYREX_ICE_RIDER FORMS_START + 323 
#define SPECIES_CALYREX_SHADOW_RIDER FORMS_START + 324 

// Basculegion
#define SPECIES_BASCULEGION_FEMALE FORMS_START + 325 

#define SPECIES_DUDUNSPARS_THREE_SEGMENT FORMS_START + 326 

#define SPECIES_LOTTABATS_HUDDLED FORMS_START + 327

#define SPECIES_GAOTERRA_SOLAR FORMS_START + 328
#define SPECIES_GAOTERRA_LUNAR FORMS_START + 329 

#define SPECIES_BISHOUCHA_WARMONGER FORMS_START + 330

#define SPECIES_PAPYPUS_FEMALE FORMS_START + 331

#define SPECIES_CINDRILLON_PIROUETTE FORMS_START + 332
#define SPECIES_CINDRILLON_FEAROUETTE FORMS_START + 333

#define SPECIES_SHISHIMA_PUNISHER FORMS_START + 334

#define SPECIES_SHUNYONG_GOLDEN_OFFENSE FORMS_START + 335

#define SPECIES_SPINDA_CAVE FORMS_START + 336
#define SPECIES_SPINDA_DESERT FORMS_START + 337
#define SPECIES_SPINDA_FOREST FORMS_START + 338
#define SPECIES_SPINDA_MOUNTAIN FORMS_START + 339
#define SPECIES_SPINDA_PLAINS FORMS_START + 340

#define SPECIES_DUDUNSPARS_EIGHT_SEGMENT FORMS_START + 341

#define SPECIES_KODOUGH_BLUNT FORMS_START + 342

#define SPECIES_CASTFORM_SANDY FORMS_START + 343

#define SPECIES_SHISHIMA_ALT FORMS_START + 344
#define SPECIES_SHISHIMA_PUNISHER_ALT FORMS_START + 345

#define SPECIES_LYOLICA FORMS_START + 346

#define SPECIES_POTTRICIA_SHATTERED FORMS_START + 347

#define FORMS_START SPECIES_POTTRICIA
#define SPECIES_EGG SPECIES_POTTRICIA_SHATTERED + 348

#define NUM_SPECIES SPECIES_EGG

#endif  // GUARD_CONSTANTS_SPECIES_H
