#ifndef GUARD_CONSTANTS_TMS_HMS_H
#define GUARD_CONSTANTS_TMS_HMS_H

#define FOREACH_TM(F) \
    F(REST) \
    F(WILL_O_WISP) \
    F(TOXIC) \
    F(DESTINY_BOND) \
    F(GLACIATE) \
    F(THUNDER_WAVE) \
    F(TRICK_ROOM) \
    F(PROTECT) \
    F(SLEEP_TALK) \
    F(MIST) \
    F(PARTING_SHOT) \
    F(DETECT) \
    F(STICKY_WEB) \
    F(JUNGLE_HEALING) \
    F(LIGHT_SCREEN) \
    F(ROTOTILLER) \
    F(REFLECT) \
    F(HEX) \
    F(GYRO_BALL) \
    F(NUZZLE) \
    F(ROLLOUT) \
    F(VACUUM_WAVE) \
    F(POUNCE) \
    F(CHARGE_BEAM) \
    F(SNARL) \
    F(MUD_SHOT) \
    F(ROCK_TOMB) \
    F(BREAKING_SWIPE) \
    F(FALSE_SWIPE) \
    F(DRAGON_TAIL) \
    F(COVET) \
    F(MAGICAL_LEAF) \
    F(BULLDOZE) \
    F(THIEF) \
    F(WATER_PULSE) \
    F(INFESTATION) \
    F(SKY_DROP) \
    F(INCINERATE) \
    F(AVALANCHE) \
    F(SWIFT) \
    F(DRAGON_BREATH) \
    F(KNOCK_OFF) \
    F(LOW_SWEEP) \
    F(VENOSHOCK) \
    F(TROP_KICK) \
    F(RETALIATE) \
    F(SPIRIT_BREAK) \
    F(BRICK_BREAK) \
    F(ROCK_SLIDE) \
    F(ZING_ZAP) \
    F(FLASH_CANNON) \
    F(AURORA_BEAM) \
    F(DRAGON_CLAW) \
    F(PSYSHOCK) \
    F(POWER_GEM) \
    F(DAZZLING_GLEAM) \
    F(AURA_SPHERE) \
    F(DARK_PULSE) \
    F(SHADOW_BALL) \
    F(PSYCHO_CUT) \
    F(IRON_HEAD) \
    F(DIRE_CLAW) \
    F(THROAT_CHOP) \
    F(HYDRO_PUMP) \
    F(SHADOW_CLAW) \
    F(ZEN_HEADBUTT) \
    F(LUNGE) \
    F(FIRE_LASH) \
    F(BODY_PRESS) \
    F(SCALD) \
    F(SEED_BOMB) \
    F(DRAGON_PULSE) \
    F(ICICLE_CRASH) \
    F(BODY_SLAM) \
    F(BUG_BUZZ) \
    F(THUNDERBOLT) \
    F(PLAY_ROUGH) \
    F(FLAMETHROWER) \
    F(PHANTOM_FORCE) \
    F(ENERGY_BALL) \
    F(EARTH_POWER) \
    F(ICE_BEAM) \
    F(HYPER_VOICE) \
    F(SLUDGE_BOMB) \
    F(PSYCHIC) \
    F(AQUA_TAIL) \
    F(FOUL_PLAY) \
    F(MOONBLAST) \
    F(PSYCHIC_FANGS) \
    F(STONE_EDGE) \
    F(RAZOR_WIND) \
    F(DUAL_WINGBEAT) \
    F(EARTHQUAKE) \
    F(BLEAKWIND_STORM) \
    F(ZAP_CANNON) \
    F(FIRE_BLAST) \
    F(ACROBATICS) \
    F(RAGING_FURY) \
    F(GUNK_SHOT) \
    F(IRON_TAIL)

#define FOREACH_HM(F) \
    F(CUT) \
    F(FLY) \
    F(SURF) \
    F(STRENGTH) \
    F(FLASH) \
    F(ROCK_SMASH) \
    F(WATERFALL) \
    F(DIVE)

#define FOREACH_TMHM(F) \
    FOREACH_TM(F) \
    FOREACH_HM(F)

#endif
