SweltornDesert_MapScripts::
	.byte 0

SweltornDesert_EventScript_Santo::
    trainerbattle_single TRAINER_P_SANTO, SweltornDesert_Text_SantoIntro, SweltornDesert_Text_SantoDefeated
    msgbox SweltornDesert_Text_SantoPostBattle, MSGBOX_AUTOCLOSE
    end

SweltornDesert_EventScript_Dorothy::
    trainerbattle_single TRAINER_P_DOROTHY, SweltornDesert_Text_DorothyIntro, SweltornDesert_Text_DorothyDefeated
    msgbox SweltornDesert_Text_DorothyPostBattle, MSGBOX_AUTOCLOSE
    end

SweltornDesert_EventScript_Erin::
    trainerbattle_single TRAINER_P_ERIN, SweltornDesert_Text_ErinIntro, SweltornDesert_Text_ErinDefeated
    msgbox SweltornDesert_Text_ErinPostBattle, MSGBOX_AUTOCLOSE
    end

SweltornDesert_EventScript_Aaron::
    trainerbattle_single TRAINER_P_AARON, SweltornDesert_Text_AaronIntro, SweltornDesert_Text_AaronDefeated
    msgbox SweltornDesert_Text_AaronPostBattle, MSGBOX_AUTOCLOSE
    end

SweltornDesert_EventScript_Thad::
    trainerbattle_single TRAINER_P_THAD, SweltornDesert_Text_ThadIntro, SweltornDesert_Text_ThadDefeated
    msgbox SweltornDesert_Text_ThadPostBattle, MSGBOX_AUTOCLOSE
    end

SweltornDesert_EventScript_Leela::
    trainerbattle_single TRAINER_P_LEELA, SweltornDesert_Text_LeelaIntro, SweltornDesert_Text_LeelaDefeated
    msgbox SweltornDesert_Text_LeelaPostBattle, MSGBOX_AUTOCLOSE
    end

SweltornDesert_EventScript_Ickle::
    trainerbattle_single TRAINER_P_ICKLE, SweltornDesert_Text_IckleIntro, SweltornDesert_Text_IckleDefeated
    msgbox SweltornDesert_Text_IcklePostBattle, MSGBOX_AUTOCLOSE
    end

SweltornDesert_EventScript_Staph::
    trainerbattle_single TRAINER_P_STAPH, SweltornDesert_Text_StaphIntro, SweltornDesert_Text_StaphDefeated
    msgbox SweltornDesert_Text_StaphPostBattle, MSGBOX_AUTOCLOSE
    end

SweltornDesert_EventScript_Hwarang::
    trainerbattle_single TRAINER_P_HWARANG, SweltornDesert_Text_HwarangIntro, SweltornDesert_Text_HwarangDefeated
    msgbox SweltornDesert_Text_HwarangPostBattle, MSGBOX_AUTOCLOSE
    end

SweltornDesert_EventScript_Takeshi::
    trainerbattle_single TRAINER_P_TAKESHI, SweltornDesert_Text_TakeshiIntro, SweltornDesert_Text_TakeshiDefeated
    msgbox SweltornDesert_Text_TakeshiPostBattle, MSGBOX_AUTOCLOSE
    end

SweltornDesert_EventScript_Beat::
    trainerbattle_single TRAINER_P_BEAT, SweltornDesert_Text_BeatIntro, SweltornDesert_Text_BeatDefeated
    msgbox SweltornDesert_Text_BeatPostBattle, MSGBOX_AUTOCLOSE
    end

SweltornDesert_EventScript_Dotty::
    trainerbattle_single TRAINER_P_DOTTY, SweltornDesert_Text_DottyIntro, SweltornDesert_Text_DottyDefeated
    msgbox SweltornDesert_Text_DottyPostBattle, MSGBOX_AUTOCLOSE
    end

SweltornDesert_Text_SantoIntro:
	.string "intro$"

SweltornDesert_Text_SantoDefeated:
	.string "defeat$"

SweltornDesert_Text_SantoPostBattle:
	.string "post$"

SweltornDesert_Text_DorothyIntro:
	.string "intro$"

SweltornDesert_Text_DorothyDefeated:
	.string "defeat$"

SweltornDesert_Text_DorothyPostBattle:
	.string "post$"

SweltornDesert_Text_ErinIntro:
	.string "intro$"

SweltornDesert_Text_ErinDefeated:
	.string "defeat$"

SweltornDesert_Text_ErinPostBattle:
	.string "post$"

SweltornDesert_Text_AaronIntro:
	.string "intro$"

SweltornDesert_Text_AaronDefeated:
	.string "defeat$"

SweltornDesert_Text_AaronPostBattle:
	.string "post$"

SweltornDesert_Text_ThadIntro:
	.string "intro$"

SweltornDesert_Text_ThadDefeated:
	.string "defeat$"

SweltornDesert_Text_ThadPostBattle:
	.string "post$"

SweltornDesert_Text_LeelaIntro:
	.string "intro$"

SweltornDesert_Text_LeelaDefeated:
	.string "defeat$"

SweltornDesert_Text_LeelaPostBattle:
	.string "post$"

SweltornDesert_Text_IckleIntro:
	.string "intro$"

SweltornDesert_Text_IckleDefeated:
	.string "defeat$"

SweltornDesert_Text_IcklePostBattle:
	.string "post$"

SweltornDesert_Text_StaphIntro:
	.string "intro$"

SweltornDesert_Text_StaphDefeated:
	.string "defeat$"

SweltornDesert_Text_StaphPostBattle:
	.string "post$"

SweltornDesert_Text_HwarangIntro:
	.string "intro$"

SweltornDesert_Text_HwarangDefeated:
	.string "defeat$"

SweltornDesert_Text_HwarangPostBattle:
	.string "post$"

SweltornDesert_Text_TakeshiIntro:
	.string "intro$"

SweltornDesert_Text_TakeshiDefeated:
	.string "defeat$"

SweltornDesert_Text_TakeshiPostBattle:
	.string "post$"

SweltornDesert_Text_BeatIntro:
	.string "intro$"

SweltornDesert_Text_BeatDefeated:
	.string "defeat$"

SweltornDesert_Text_BeatPostBattle:
	.string "post$"

SweltornDesert_Text_DottyIntro:
	.string "intro$"

SweltornDesert_Text_DottyDefeated:
	.string "defeat$"

SweltornDesert_Text_DottyPostBattle:
	.string "post$"
