gText_Birch_Welcome::
	.string "Ahoy!\p"
	.string "Pleased to welcome you onto my\n"
	.string "prized vessel, the S.S. Tidal.\p"
	.string "I've been sailin' the seven seas\n"
	.string "for as long as I've had memories!\p"
	.string "$"

gText_Birch_Pokemon::
	.string "I'd like to introduce you to\n"
	.string "my partner POKéMON, Peeko!\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "Ahahaha! Peeko's always eager\n"
	.string "to meet new folks on our\l"
	.string "voyages! She won't bite.\p"
	.string "Now, pleasantries aside...\p"
	.string "We are about to depart for our\n"
	.string "scheduled sail from Sevii Isle\l"
	.string "2 to the Hoenn Region.\p"
	.string "It seems you were drafted\n"
	.string "to this voyage on short notice by\l"
	.string "ol' Ultima. You must be on\l"
	.string "some kind of urgent business,\l"
	.string "I take it?\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "...Forgive a nosy old man, but\n"
	.string "I'd like to know a bit more.$"

gText_Birch_BoyOrGirl::
	.string "How would you like\n"
	.string "to be referred to?$"

gText_Birch_WhatsYourName::
	.string "That's more than fine.\n"
	.string "Can I have your name?$"

gText_Birch_SoItsPlayer::
	.string "{PLAYER}{KUN}, then?$"

gText_Birch_YourePlayer::
	.string "Oh? You are Professor Birch's\n"
	.string "child? Well now, that explains\l"
	.string "a lot! So you're wanting to\l"
	.string "catch up with your old man.\p"
	.string "Hah! I just know he'll be\n"
	.string "thrilled to see you!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "One last thing before I'll let\n"
	.string "you get settled into your room.\p"
	.string "I couldn't help but notice\n"
	.string "that you don't have any POKéMON\l"
	.string "traveling with you.\p"
	.string "I seem to recall ol' Birch\n"
	.string "saying something about his child\l"
	.string "being a POKéMON Trainer.\p"
	.string "...\p"
	.string "...I see. Gave that life up to\n"
	.string "dedicate yourself to research, eh?\p"
	.string "Hah! I very well should be\n"
	.string "calling YOU Professor, then!\p"
	.string "Alright, I've held you long enough.\n"
	.string "Welcome aboard!\p"
	.string "$"
