Route124_MapScripts::
	.byte 0

Route124_EventScript_Ariel::
    trainerbattle_single TRAINER_P_ARIEL, Route124_Text_ArielIntro, Route124_Text_ArielDefeated
    msgbox Route124_Text_ArielPostBattle, MSGBOX_AUTOCLOSE
    end

Route124_EventScript_Dolly::
    trainerbattle_single TRAINER_P_DOLLY, Route124_Text_DollyIntro, Route124_Text_DollyDefeated
    msgbox Route124_Text_DollyPostBattle, MSGBOX_AUTOCLOSE
    end

Route124_EventScript_Sinjin::
    trainerbattle_single TRAINER_P_SINJIN, Route124_Text_SinjinIntro, Route124_Text_SinjinDefeated
    msgbox Route124_Text_SinjinPostBattle, MSGBOX_AUTOCLOSE
    end

Route124_EventScript_Josuke::
    trainerbattle_single TRAINER_P_JOSUKE, Route124_Text_JosukeIntro, Route124_Text_JosukeDefeated
    msgbox Route124_Text_JosukePostBattle, MSGBOX_AUTOCLOSE
    end

Route124_EventScript_Toby::
    trainerbattle_single TRAINER_P_TOBY, Route124_Text_TobyIntro, Route124_Text_TobyDefeated
    msgbox Route124_Text_TobyPostBattle, MSGBOX_AUTOCLOSE
    end

Route124_EventScript_Arbuckle::
    trainerbattle_single TRAINER_P_ARBUCKLE, Route124_Text_ArbuckleIntro, Route124_Text_ArbuckleDefeated
    msgbox Route124_Text_ArbucklePostBattle, MSGBOX_AUTOCLOSE
    end

Route124_EventScript_Naomi::
    trainerbattle_single TRAINER_P_NAOMI, Route124_Text_NaomiIntro, Route124_Text_NaomiDefeated
    msgbox Route124_Text_NaomiPostBattle, MSGBOX_AUTOCLOSE
    end

Route124_EventScript_Betha::
    trainerbattle_single TRAINER_P_BETHA, Route124_Text_BethaIntro, Route124_Text_BethaDefeated
    msgbox Route124_Text_BethaPostBattle, MSGBOX_AUTOCLOSE
    end

Route124_EventScript_Ebb::
    trainerbattle_single TRAINER_P_EBB, Route124_Text_EbbIntro, Route124_Text_EbbDefeated
    msgbox Route124_Text_EbbPostBattle, MSGBOX_AUTOCLOSE
    end

Route124_EventScript_Flo::
    trainerbattle_single TRAINER_P_FLO, Route124_Text_FloIntro, Route124_Text_FloDefeated
    msgbox Route124_Text_FloPostBattle, MSGBOX_AUTOCLOSE
    end

Route124_EventScript_Julio::
    trainerbattle_single TRAINER_P_JULIO, Route124_Text_JulioIntro, Route124_Text_JulioDefeated
    msgbox Route124_Text_JulioPostBattle, MSGBOX_AUTOCLOSE
    end

Route124_EventScript_Homer::
    trainerbattle_single TRAINER_P_HOMER, Route124_Text_HomerIntro, Route124_Text_HomerDefeated
    msgbox Route124_Text_HomerPostBattle, MSGBOX_AUTOCLOSE
    end

Route124_EventScript_Marge::
    trainerbattle_single TRAINER_P_MARGE, Route124_Text_MargeIntro, Route124_Text_MargeDefeated
    msgbox Route124_Text_MargePostBattle, MSGBOX_AUTOCLOSE
    end

Route124_EventScript_Shala::
    trainerbattle_single TRAINER_P_SHALA, Route124_Text_ShalaIntro, Route124_Text_ShalaDefeated
    msgbox Route124_Text_ShalaPostBattle, MSGBOX_AUTOCLOSE
    end

Route124_EventScript_Lala::
    trainerbattle_single TRAINER_P_LALA, Route124_Text_LalaIntro, Route124_Text_LalaDefeated
    msgbox Route124_Text_LalaPostBattle, MSGBOX_AUTOCLOSE
    end

Route124_EventScript_La::
    trainerbattle_single TRAINER_P_LA, Route124_Text_LaIntro, Route124_Text_LaDefeated
    msgbox Route124_Text_LaPostBattle, MSGBOX_AUTOCLOSE
    end

Route124_EventScript_Shalala::
    trainerbattle_single TRAINER_P_SHALALA, Route124_Text_ShalalaIntro, Route124_Text_ShalalaDefeated
    msgbox Route124_Text_ShalalaPostBattle, MSGBOX_AUTOCLOSE
    end

Route124_EventScript_Inda::
    trainerbattle_single TRAINER_P_INDA, Route124_Text_IndaIntro, Route124_Text_IndaDefeated
    msgbox Route124_Text_IndaPostBattle, MSGBOX_AUTOCLOSE
    end

Route124_EventScript_Morning::
    trainerbattle_single TRAINER_P_MORNING, Route124_Text_MorningIntro, Route124_Text_MorningDefeated
    msgbox Route124_Text_MorningPostBattle, MSGBOX_AUTOCLOSE
    end

Route124_Text_ArielNeedTwoMons:
	.string "need 2 dood$"

Route124_Text_ArielIntro:
	.string "intro$"

Route124_Text_ArielDefeated:
	.string "defeat$"

Route124_Text_ArielPostBattle:
	.string "post$"

Route124_Text_DollyIntro:
	.string "intro$"

Route124_Text_DollyDefeated:
	.string "defeat$"

Route124_Text_DollyPostBattle:
	.string "post$"

Route124_Text_SinjinIntro:
	.string "intro$"

Route124_Text_SinjinDefeated:
	.string "defeat$"

Route124_Text_SinjinPostBattle:
	.string "post$"

Route124_Text_JosukeIntro:
	.string "intro$"

Route124_Text_JosukeDefeated:
	.string "defeat$"

Route124_Text_JosukePostBattle:
	.string "post$"

Route124_Text_TobyIntro:
	.string "intro$"

Route124_Text_TobyDefeated:
	.string "defeat$"

Route124_Text_TobyPostBattle:
	.string "post$"

Route124_Text_ArbuckleIntro:
	.string "intro$"

Route124_Text_ArbuckleDefeated:
	.string "defeat$"

Route124_Text_ArbucklePostBattle:
	.string "post$"

Route124_Text_NaomiIntro:
	.string "intro$"

Route124_Text_NaomiDefeated:
	.string "defeat$"

Route124_Text_NaomiPostBattle:
	.string "post$"

Route124_Text_BethaIntro:
	.string "intro$"

Route124_Text_BethaDefeated:
	.string "defeat$"

Route124_Text_BethaPostBattle:
	.string "post$"

Route124_Text_EbbIntro:
	.string "intro$"

Route124_Text_EbbDefeated:
	.string "defeat$"

Route124_Text_EbbPostBattle:
	.string "post$"

Route124_Text_FloIntro:
	.string "intro$"

Route124_Text_FloDefeated:
	.string "defeat$"

Route124_Text_FloPostBattle:
	.string "post$"

Route124_Text_JulioIntro:
	.string "intro$"

Route124_Text_JulioDefeated:
	.string "defeat$"

Route124_Text_JulioPostBattle:
	.string "post$"

Route124_Text_HomerIntro:
	.string "intro$"

Route124_Text_HomerDefeated:
	.string "defeat$"

Route124_Text_HomerPostBattle:
	.string "post$"

Route124_Text_MargeIntro:
	.string "intro$"

Route124_Text_MargeDefeated:
	.string "defeat$"

Route124_Text_MargePostBattle:
	.string "post$"

Route124_Text_ShalaIntro:
	.string "intro$"

Route124_Text_ShalaDefeated:
	.string "defeat$"

Route124_Text_ShalaPostBattle:
	.string "post$"

Route124_Text_LalaIntro:
	.string "intro$"

Route124_Text_LalaDefeated:
	.string "defeat$"

Route124_Text_LalaPostBattle:
	.string "post$"

Route124_Text_LaIntro:
	.string "intro$"

Route124_Text_LaDefeated:
	.string "defeat$"

Route124_Text_LaPostBattle:
	.string "post$"

Route124_Text_ShalalaIntro:
	.string "intro$"

Route124_Text_ShalalaDefeated:
	.string "defeat$"

Route124_Text_ShalalaPostBattle:
	.string "post$"

Route124_Text_IndaIntro:
	.string "intro$"

Route124_Text_IndaDefeated:
	.string "defeat$"

Route124_Text_IndaPostBattle:
	.string "post$"

Route124_Text_MorningIntro:
	.string "intro$"

Route124_Text_MorningDefeated:
	.string "defeat$"

Route124_Text_MorningPostBattle:
	.string "post$"
