CanopourWilds_MapScripts::
	.byte 0

CanopourWilds_EventScript_Justin::
    trainerbattle_single TRAINER_P_JUSTIN, CanopourWilds_Text_JustinIntro, CanopourWilds_Text_JustinDefeated
    msgbox CanopourWilds_Text_JustinPostBattle, MSGBOX_AUTOCLOSE
    end

CanopourWilds_EventScript_Juono::
    trainerbattle_single TRAINER_P_JUONO, CanopourWilds_Text_JuonoIntro, CanopourWilds_Text_JuonoDefeated
    msgbox CanopourWilds_Text_JuonoPostBattle, MSGBOX_AUTOCLOSE
    end

CanopourWilds_EventScript_Wallpress::
    trainerbattle_single TRAINER_P_WALLPRESS, CanopourWilds_Text_WallpressIntro, CanopourWilds_Text_WallpressDefeated
    msgbox CanopourWilds_Text_WallpressPostBattle, MSGBOX_AUTOCLOSE
    end

CanopourWilds_EventScript_Tawny::
    trainerbattle_single TRAINER_P_TAWNY, CanopourWilds_Text_TawnyIntro, CanopourWilds_Text_TawnyDefeated
    msgbox CanopourWilds_Text_TawnyPostBattle, MSGBOX_AUTOCLOSE
    end

CanopourWilds_EventScript_Jaiden::
    trainerbattle_single TRAINER_P_JAIDEN, CanopourWilds_Text_JaidenIntro, CanopourWilds_Text_JaidenDefeated
    msgbox CanopourWilds_Text_JaidenPostBattle, MSGBOX_AUTOCLOSE
    end

CanopourWilds_EventScript_Griseldis::
    trainerbattle_single TRAINER_P_GRISELDIS, CanopourWilds_Text_GriseldisIntro, CanopourWilds_Text_GriseldisDefeated
    msgbox CanopourWilds_Text_GriseldisPostBattle, MSGBOX_AUTOCLOSE
    end

CanopourWilds_EventScript_Cameron::
    trainerbattle_single TRAINER_P_CAMERON, CanopourWilds_Text_CameronIntro, CanopourWilds_Text_CameronDefeated
    msgbox CanopourWilds_Text_CameronPostBattle, MSGBOX_AUTOCLOSE
    end

CanopourWilds_EventScript_Flaitine::
    trainerbattle_single TRAINER_P_FLAITINE, CanopourWilds_Text_FlaitineIntro, CanopourWilds_Text_FlaitineDefeated
    msgbox CanopourWilds_Text_FlaitinePostBattle, MSGBOX_AUTOCLOSE
    end

CanopourWilds_EventScript_Jamper::
    trainerbattle_single TRAINER_P_JAMPER, CanopourWilds_Text_JamperIntro, CanopourWilds_Text_JamperDefeated
    msgbox CanopourWilds_Text_JamperPostBattle, MSGBOX_AUTOCLOSE
    end

CanopourWilds_EventScript_Englatere::
    trainerbattle_single TRAINER_P_ENGLATERE, CanopourWilds_Text_EnglatereIntro, CanopourWilds_Text_EnglatereDefeated
    msgbox CanopourWilds_Text_EnglaterePostBattle, MSGBOX_AUTOCLOSE
    end

CanopourWilds_EventScript_Koizumi::
    trainerbattle_single TRAINER_P_KOIZUMI, CanopourWilds_Text_KoizumiIntro, CanopourWilds_Text_KoizumiDefeated
    msgbox CanopourWilds_Text_KoizumiPostBattle, MSGBOX_AUTOCLOSE
    end

CanopourWilds_EventScript_Charli::
    trainerbattle_single TRAINER_P_CHARLI, CanopourWilds_Text_CharliIntro, CanopourWilds_Text_CharliDefeated
    msgbox CanopourWilds_Text_CharliPostBattle, MSGBOX_AUTOCLOSE
    end

CanopourWilds_EventScript_Shamoo::
    trainerbattle_single TRAINER_P_SHAMOO, CanopourWilds_Text_ShamooIntro, CanopourWilds_Text_ShamooDefeated
    msgbox CanopourWilds_Text_ShamooPostBattle, MSGBOX_AUTOCLOSE
    end

CanopourWilds_EventScript_Marisa::
    trainerbattle_single TRAINER_P_MARISA, CanopourWilds_Text_MarisaIntro, CanopourWilds_Text_MarisaDefeated
    msgbox CanopourWilds_Text_MarisaPostBattle, MSGBOX_AUTOCLOSE
    end

CanopourWilds_EventScript_Gunness::
    trainerbattle_single TRAINER_P_GUNNESS, CanopourWilds_Text_GunnessIntro, CanopourWilds_Text_GunnessDefeated
    msgbox CanopourWilds_Text_GunnessPostBattle, MSGBOX_AUTOCLOSE
    end

CanopourWilds_EventScript_Jason::
    trainerbattle_single TRAINER_P_JASON, CanopourWilds_Text_JasonIntro, CanopourWilds_Text_JasonDefeated
    msgbox CanopourWilds_Text_JasonPostBattle, MSGBOX_AUTOCLOSE
    end

CanopourWilds_EventScript_Leah::
    trainerbattle_single TRAINER_P_LEAH, CanopourWilds_Text_LeahIntro, CanopourWilds_Text_LeahDefeated
    msgbox CanopourWilds_Text_LeahPostBattle, MSGBOX_AUTOCLOSE
    end

CanopourWilds_EventScript_Lele::
    trainerbattle_single TRAINER_P_LELE, CanopourWilds_Text_LeleIntro, CanopourWilds_Text_LeleDefeated
    msgbox CanopourWilds_Text_LelePostBattle, MSGBOX_AUTOCLOSE
    end

CanopourWilds_EventScript_PickleLou::
    trainerbattle_single TRAINER_P_PICKLE_LOU, CanopourWilds_Text_PickleLouIntro, CanopourWilds_Text_PickleLouDefeated
    msgbox CanopourWilds_Text_PickleLouPostBattle, MSGBOX_AUTOCLOSE
    end

CanopourWilds_Text_JustinIntro:
	.string "intro$"

CanopourWilds_Text_JustinDefeated:
	.string "defeat$"

CanopourWilds_Text_JustinPostBattle:
	.string "post$"

CanopourWilds_Text_JuonoIntro:
	.string "intro$"

CanopourWilds_Text_JuonoDefeated:
	.string "defeat$"

CanopourWilds_Text_JuonoPostBattle:
	.string "post$"

CanopourWilds_Text_WallpressIntro:
	.string "intro$"

CanopourWilds_Text_WallpressDefeated:
	.string "defeat$"

CanopourWilds_Text_WallpressPostBattle:
	.string "post$"

CanopourWilds_Text_TawnyIntro:
	.string "intro$"

CanopourWilds_Text_TawnyDefeated:
	.string "defeat$"

CanopourWilds_Text_TawnyPostBattle:
	.string "post$"

CanopourWilds_Text_JaidenIntro:
	.string "intro$"

CanopourWilds_Text_JaidenDefeated:
	.string "defeat$"

CanopourWilds_Text_JaidenPostBattle:
	.string "post$"

CanopourWilds_Text_GriseldisIntro:
	.string "intro$"

CanopourWilds_Text_GriseldisDefeated:
	.string "defeat$"

CanopourWilds_Text_GriseldisPostBattle:
	.string "post$"

CanopourWilds_Text_CameronIntro:
	.string "intro$"

CanopourWilds_Text_CameronDefeated:
	.string "defeat$"

CanopourWilds_Text_CameronPostBattle:
	.string "post$"

CanopourWilds_Text_FlaitineIntro:
	.string "intro$"

CanopourWilds_Text_FlaitineDefeated:
	.string "defeat$"

CanopourWilds_Text_FlaitinePostBattle:
	.string "post$"

CanopourWilds_Text_JamperIntro:
	.string "intro$"

CanopourWilds_Text_JamperDefeated:
	.string "defeat$"

CanopourWilds_Text_JamperPostBattle:
	.string "post$"

CanopourWilds_Text_EnglatereIntro:
	.string "intro$"

CanopourWilds_Text_EnglatereDefeated:
	.string "defeat$"

CanopourWilds_Text_EnglaterePostBattle:
	.string "post$"

CanopourWilds_Text_KoizumiIntro:
	.string "intro$"

CanopourWilds_Text_KoizumiDefeated:
	.string "defeat$"

CanopourWilds_Text_KoizumiPostBattle:
	.string "post$"

CanopourWilds_Text_CharliIntro:
	.string "intro$"

CanopourWilds_Text_CharliDefeated:
	.string "defeat$"

CanopourWilds_Text_CharliPostBattle:
	.string "post$"

CanopourWilds_Text_ShamooIntro:
	.string "intro$"

CanopourWilds_Text_ShamooDefeated:
	.string "defeat$"

CanopourWilds_Text_ShamooPostBattle:
	.string "post$"

CanopourWilds_Text_MarisaIntro:
	.string "intro$"

CanopourWilds_Text_MarisaDefeated:
	.string "defeat$"

CanopourWilds_Text_MarisaPostBattle:
	.string "post$"

CanopourWilds_Text_GunnessIntro:
	.string "intro$"

CanopourWilds_Text_GunnessDefeated:
	.string "defeat$"

CanopourWilds_Text_GunnessPostBattle:
	.string "post$"

CanopourWilds_Text_JasonIntro:
	.string "intro$"

CanopourWilds_Text_JasonDefeated:
	.string "defeat$"

CanopourWilds_Text_JasonPostBattle:
	.string "post$"

CanopourWilds_Text_LeahIntro:
	.string "intro$"

CanopourWilds_Text_LeahDefeated:
	.string "defeat$"

CanopourWilds_Text_LeahPostBattle:
	.string "post$"

CanopourWilds_Text_LeleIntro:
	.string "intro$"

CanopourWilds_Text_LeleDefeated:
	.string "defeat$"

CanopourWilds_Text_LelePostBattle:
	.string "post$"

CanopourWilds_Text_PickleLouIntro:
	.string "intro$"

CanopourWilds_Text_PickleLouDefeated:
	.string "defeat$"

CanopourWilds_Text_PickleLouPostBattle:
	.string "post$"
