DetermaniteQuarry_MapScripts::
	.byte 0

DetermaniteQuarry_EventScript_Joshuone::
    trainerbattle_single TRAINER_P_JOSHUONE, DetermaniteQuarry_Text_JoshuoneIntro, DetermaniteQuarry_Text_JoshuoneDefeated
    msgbox DetermaniteQuarry_Text_JoshuonePostBattle, MSGBOX_AUTOCLOSE
    end

DetermaniteQuarry_EventScript_Astolfo::
    trainerbattle_single TRAINER_P_ASTOLFO, DetermaniteQuarry_Text_AstolfoIntro, DetermaniteQuarry_Text_AstolfoDefeated
    msgbox DetermaniteQuarry_Text_AstolfoPostBattle, MSGBOX_AUTOCLOSE
    end

DetermaniteQuarry_EventScript_Roberts::
    trainerbattle_single TRAINER_P_ROBERTS, DetermaniteQuarry_Text_RobertsIntro, DetermaniteQuarry_Text_RobertsDefeated
    msgbox DetermaniteQuarry_Text_RobertsPostBattle, MSGBOX_AUTOCLOSE
    end

DetermaniteQuarry_EventScript_Buttercup::
    trainerbattle_single TRAINER_P_BUTTERCUP, DetermaniteQuarry_Text_ButtercupIntro, DetermaniteQuarry_Text_ButtercupDefeated
    msgbox DetermaniteQuarry_Text_ButtercupPostBattle, MSGBOX_AUTOCLOSE
    end

DetermaniteQuarry_EventScript_Gwunette::
    trainerbattle_single TRAINER_P_GWUNNETTE, DetermaniteQuarry_Text_GwunetteIntro, DetermaniteQuarry_Text_GwunetteDefeated
    msgbox DetermaniteQuarry_Text_GwunettePostBattle, MSGBOX_AUTOCLOSE
    end

DetermaniteQuarry_EventScript_Cody::
    trainerbattle_single TRAINER_P_CODY, DetermaniteQuarry_Text_CodyIntro, DetermaniteQuarry_Text_CodyDefeated
    msgbox DetermaniteQuarry_Text_CodyPostBattle, MSGBOX_AUTOCLOSE
    end

DetermaniteQuarry_EventScript_Michiko::
    trainerbattle_single TRAINER_P_MICHIKO, DetermaniteQuarry_Text_MichikoIntro, DetermaniteQuarry_Text_MichikoDefeated
    msgbox DetermaniteQuarry_Text_MichikoPostBattle, MSGBOX_AUTOCLOSE
    end

DetermaniteQuarry_Text_JoshuoneIntro:
	.string "intro$"

DetermaniteQuarry_Text_JoshuoneDefeated:
	.string "defeat$"

DetermaniteQuarry_Text_JoshuonePostBattle:
	.string "post$"

DetermaniteQuarry_Text_AstolfoIntro:
	.string "intro$"

DetermaniteQuarry_Text_AstolfoDefeated:
	.string "defeat$"

DetermaniteQuarry_Text_AstolfoPostBattle:
	.string "post$"

DetermaniteQuarry_Text_RobertsIntro:
	.string "intro$"

DetermaniteQuarry_Text_RobertsDefeated:
	.string "defeat$"

DetermaniteQuarry_Text_RobertsPostBattle:
	.string "post$"

DetermaniteQuarry_Text_ButtercupIntro:
	.string "intro$"

DetermaniteQuarry_Text_ButtercupDefeated:
	.string "defeat$"

DetermaniteQuarry_Text_ButtercupPostBattle:
	.string "post$"

DetermaniteQuarry_Text_GwunetteIntro:
	.string "intro$"

DetermaniteQuarry_Text_GwunetteDefeated:
	.string "defeat$"

DetermaniteQuarry_Text_GwunettePostBattle:
	.string "post$"

DetermaniteQuarry_Text_CodyIntro:
	.string "intro$"

DetermaniteQuarry_Text_CodyDefeated:
	.string "defeat$"

DetermaniteQuarry_Text_CodyPostBattle:
	.string "post$"

DetermaniteQuarry_Text_MichikoIntro:
	.string "intro$"

DetermaniteQuarry_Text_MichikoDefeated:
	.string "defeat$"

DetermaniteQuarry_Text_MichikoPostBattle:
	.string "post$"
