Common_EventScript_SetGymTrainers::
	switch VAR_0x8008
	case 1, RustboroCity_Gym_SetGymTrainers
	case 2, DewfordTown_Gym_SetGymTrainers
	case 3, MauvilleCity_Gym_SetGymTrainers
	case 4, LavaridgeTown_Gym_SetGymTrainers
	case 5, PetalburgCity_Gym_SetGymTrainers
	case 6, FortreeCity_Gym_SetGymTrainers
	case 7, MossdeepCity_Gym_SetGymTrainers
	case 8, SootopolisCity_Gym_SetGymTrainers
	end

RustboroCity_Gym_SetGymTrainers::
	settrainerflag TRAINER_P_ROY
	settrainerflag TRAINER_P_MAIA
	settrainerflag TRAINER_P_JIMMY
	return

DewfordTown_Gym_SetGymTrainers::
	settrainerflag TRAINER_P_LEILEI
	settrainerflag TRAINER_P_SOLAIRE
	settrainerflag TRAINER_P_LUNA
	settrainerflag TRAINER_P_TIMMY_2
	settrainerflag TRAINER_P_SASHA
	settrainerflag TRAINER_P_JOE
	return

MauvilleCity_Gym_SetGymTrainers::
	settrainerflag TRAINER_P_ENGLATERE
	settrainerflag TRAINER_P_SHAMOO
	settrainerflag TRAINER_P_MCKAYLEIGH
	settrainerflag TRAINER_P_KUMQOT
	settrainerflag TRAINER_ANGELO
	return

LavaridgeTown_Gym_SetGymTrainers::
	settrainerflag TRAINER_P_PANDOU_3
	settrainerflag TRAINER_P_SUSIE
	settrainerflag TRAINER_P_FUJI
	settrainerflag TRAINER_P_TOPAZ_10
	settrainerflag TRAINER_P_DORIAN
	settrainerflag TRAINER_P_RALSEI
	settrainerflag TRAINER_P_KRIS
	settrainerflag TRAINER_P_MICYCLE
	return

PetalburgCity_Gym_SetGymTrainers::
	settrainerflag TRAINER_P_TESS
	settrainerflag TRAINER_P_HITOMI
	settrainerflag TRAINER_P_LIZA
	settrainerflag TRAINER_P_S_STEVEN_1
	settrainerflag TRAINER_P_NELLY
	settrainerflag TRAINER_P_SADFISHER_2
	settrainerflag TRAINER_P_ARIEL
	return

FortreeCity_Gym_SetGymTrainers::
	settrainerflag TRAINER_P_JOSE
	settrainerflag TRAINER_P_PANDOU_5
	settrainerflag TRAINER_P_PETER
	settrainerflag TRAINER_P_LYNN
	settrainerflag TRAINER_P_DARIA
	settrainerflag TRAINER_DARIUS
	return

MossdeepCity_Gym_SetGymTrainers::
	settrainerflag TRAINER_P_JUCIKA
	settrainerflag TRAINER_P_NARUTO
	settrainerflag TRAINER_P_KUSHINA
	settrainerflag TRAINER_P_AKI_AND_MITSU
	settrainerflag TRAINER_P_DAISY
	settrainerflag TRAINER_P_GWUNIVERE
	settrainerflag TRAINER_P_ELLE
	settrainerflag TRAINER_P_GUNDER
	settrainerflag TRAINER_P_GUNHILD
	settrainerflag TRAINER_P_ELON
	settrainerflag TRAINER_P_SOD_AND_SANDY
	settrainerflag TRAINER_P_LILITH
	return

SootopolisCity_Gym_SetGymTrainers::
	settrainerflag TRAINER_P_INGRID
	settrainerflag TRAINER_P_BLAISE_AND_MAR
	settrainerflag TRAINER_P_NATALIE
	settrainerflag TRAINER_P_LAPIZ
	settrainerflag TRAINER_P_VERGIL
	settrainerflag TRAINER_P_YOSH
	settrainerflag TRAINER_P_KAIJI
	settrainerflag TRAINER_P_AARON
	settrainerflag TRAINER_P_SKIPPER
	settrainerflag TRAINER_P_OZONE_TABITHA_1
	return
