StevenMaze_MapScripts::
	.byte 0

StevenMaze_EventScript_ShadowSteven1::
    trainerbattle_single TRAINER_P_S_STEVEN_1, StevenMaze_Text_Gugumbir, StevenMaze_Text_Gugumbir
    msgbox StevenMaze_Text_Gugumbir, MSGBOX_AUTOCLOSE
    end

StevenMaze_EventScript_ShadowSteven2::
    trainerbattle_single TRAINER_P_S_STEVEN_2, StevenMaze_Text_Gugumbir, StevenMaze_Text_Gugumbir
    msgbox StevenMaze_Text_Gugumbir, MSGBOX_AUTOCLOSE
    end

StevenMaze_EventScript_ShadowSteven3::
    trainerbattle_single TRAINER_P_S_STEVEN_3, StevenMaze_Text_Gugumbir, StevenMaze_Text_Gugumbir
    msgbox StevenMaze_Text_Gugumbir, MSGBOX_AUTOCLOSE
    end

StevenMaze_EventScript_ShadowSteven4::
    trainerbattle_single TRAINER_P_S_STEVEN_4, StevenMaze_Text_Gugumbir, StevenMaze_Text_Gugumbir
    msgbox StevenMaze_Text_Gugumbir, MSGBOX_AUTOCLOSE
    end

StevenMaze_EventScript_ShadowSteven5::
    trainerbattle_single TRAINER_P_S_STEVEN_5, StevenMaze_Text_Gugumbir, StevenMaze_Text_Gugumbir
    msgbox StevenMaze_Text_Gugumbir, MSGBOX_AUTOCLOSE
    end

StevenMaze_EventScript_ShadowSteven6::
    trainerbattle_single TRAINER_P_S_STEVEN_6, StevenMaze_Text_Gugumbir, StevenMaze_Text_Gugumbir
    msgbox StevenMaze_Text_Gugumbir, MSGBOX_AUTOCLOSE
    end

StevenMaze_Text_Gugumbir:
	.string "boo$"
